### PR TITLE
table: Make compacting reader v2.

### PR DESCRIPTION
**Pull request by mikolajsieluzycki**
This is a facade change only to add a factory function that does
upgrade_to_v2 internally. It exists side by side with the v1 version.

### CODE REVIEW

**Comment by denesb** [comment]
What is the context for this change? On its own it doesn't make much sense to me.

**Comment by mikolajsieluzycki** [comment]
It's a prerequisite for #3568. The proper solution as far as I see it is wrapping make_sstable_reader inside table::sstables_as_snapshot_source with make_compacting_reader. The expected output is in v2 version, but currently we only have v1 compacting reader.

**Comment by denesb** [comment]
Can't we do an `upgrade_to_v2()` on the spot? There is a patchset on the list currently which does the conversion ("[PATCH v2 00/15] Migrate sstable writer to v2") which does a proper conversion of the compacting reader to v2. I think an `upgrade_to_v2()` in the affected code is fine until that gets merged, which is hopefully soon.

**Comment by mikolajsieluzycki** [comment]
If that's happening soon, the patch can wait and not be merged at all. There are a couple of tests I need to fix before adding the compaction and maybe the proper fix will be merged sooner.

**Comment by denesb** [comment]
I think what would make most sense is to just use `upgrade_to_v2()` in the patch that adds the compacting reader to the cache sstable reader pipeline. Alternatively you can include this patch in that series if you want.
In general it is a good idea to send preparatory and cleanup patches separately only if these patches make sense on their own. Patches that only make sense in the context of a larger series will find it really hard to get in alone.

**Comment by mikolajsieluzycki** [comment]
Sounds good, closing.

**Pull request closed without merging**
