### PR TITLE
scylla_ntp_setup: use chrony on all distributions

### PR DESCRIPTION
**Pull request by syuu1228**
To simplify scylla_ntp_setup, use chrony on all distributions.

### CODE REVIEW

**Comment by avikivity** [comment]
Is chrony available everywhere?

I remember something about chrony being targeted at desktops while ntp is for servers, but maybe it's wrong.

**Comment by syuu1228** [comment]
> Is chrony available everywhere?
Looks like all supported distributions have it:
Debian: 8, 9, 10 Ubuntu: 16.04, 18.04, 20.04 CentOS: 7, 8

> I remember something about chrony being targeted at desktops while ntp is for servers, but maybe it's wrong.
Not sure about this, but at least RHEL7/8 and SLES15 shipped with chrony by default, and also RHEL8/SLES15 dropped ntpd, I guess it should be fine.

**Comment by avikivity** [comment]
Agree it should be fine.

**Comment by syuu1228** [comment]
Rebased, able to merge now.

**Comment by avikivity** [comment]
Conflicts (probably the scylla_util simplification).

**Comment by syuu1228** [comment]
@avikivity rebased.

**Pull request merged**
