### PR TITLE
thrift: backport thrift >= 0.11 support from #4538 to 3.1

### PR DESCRIPTION
**Pull request by ultrabug**
I'd like to backport #4538 to 3.1 please :+1: 

Tested OK here.

### CODE REVIEW

**Comment by penberg** [comment]
The upstream commit is 98bc9edf6f5967ff3d93896e6ccb10975d0b929f. It does not `git cherry-pick` cleanly, but @ultrabug already did the confict resolution for this pull request.

@avikivity This does not fit into the typical definition of fixing a regression or a critical bug so I am leaving the decision for you.

@ultrabug Could you elaborate on why you need this? That is, what specifically are you blocked on by this?

**Comment by ultrabug** [comment]
Hi @penberg 

I think this is too late for this PR to get in since 3.2 is around the corner and includes this patch (hopefully?).

Thing is that I get to maintain and backport this patch myself on the Gentoo ebuild side if it's not included by the release so it's something I'd like to keep to a minimum.

With your approval, I'd like to close this PR.

**Comment by avikivity** [comment]
I think we can include compatibility with upstream libraries as bug fixes, even though our own packages use a frozen toolchain and don't suffer from such problems (i.e. we shouldn't privilege our delivery method)

**Comment by avikivity** [comment]
Dequeueing; fails with

```
DDEBUG_LSA_SANITIZER -gz  -I. -I build/debug/gen  -c -o build/debug/thrift/handler.o thrift/handler.cc
14:04:42  thrift/handler.cc:59:28: error: 'namespace thrift_std = apache::thrift::apache::thrift::stdcxx;' conflicts with a previous declaration
14:04:42   namespace thrift_std = tcxx;
14:04:42                              ^
14:04:42  In file included from thrift/handler.cc:55:
14:04:42  ./thrift/server.hh:35:29: note: previous declaration 'namespace thrift_std = boost;'
14:04:42   namespace thrift_std = boost;
14:04:42                               ^
14:04:42  thrift/handler.cc: In member function 'virtual cassandra::CassandraCobSvIf* handler_factory::getHandler(const apache::thrift::TConnectionInfo&)':
14:04:42  thrift/handler.cc:1953:88: error: invalid new-expression of abstract class type 'thrift_handler'
14:04:42           return new thrift_handler(_db, _query_processor, _auth_service, _timeout_config);
14:04:42                                                                                          ^
14:04:42  thrift/handler.cc:203:7: note:   because the following virtual functions are pure within 'thrift_handler':
14:04:42   class thrift_handler : public CassandraCobSvIf {
14:04:42         ^~~~~~~~~~~~~~
14:04:42  In file included from thrift/handler.cc:27:
14:04:42  build/debug/gen/Cassandra.h:7349:16: note: 	'virtual void cassandra::CassandraCobSvIf::login(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::AuthenticationRequest&)'
14:04:42     virtual void login(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const AuthenticationRequest& auth_request) = 0;
14:04:42                  ^~~~~
14:04:42  build/debug/gen/Cassandra.h:7350:16: note: 	'virtual void cassandra::CassandraCobSvIf::set_keyspace(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void set_keyspace(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& keyspace) = 0;
14:04:42                  ^~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7360:16: note: 	'virtual void cassandra::CassandraCobSvIf::get(std::tr1::function<void(const cassandra::ColumnOrSuperColumn&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnPath&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void get(tcxx::function<void(ColumnOrSuperColumn const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnPath& column_path, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~
14:04:42  build/debug/gen/Cassandra.h:7371:16: note: 	'virtual void cassandra::CassandraCobSvIf::get_slice(std::tr1::function<void(const std::vector<cassandra::ColumnOrSuperColumn>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnParent&, const cassandra::SlicePredicate&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void get_slice(tcxx::function<void(std::vector<ColumnOrSuperColumn>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnParent& column_parent, const SlicePredicate& predicate, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7382:16: note: 	'virtual void cassandra::CassandraCobSvIf::get_count(std::tr1::function<void(const int&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnParent&, const cassandra::SlicePredicate&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void get_count(tcxx::function<void(int32_t const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnParent& column_parent, const SlicePredicate& predicate, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7392:16: note: 	'virtual void cassandra::CassandraCobSvIf::multiget_slice(std::tr1::function<void(const std::map<std::__cxx11::basic_string<char>, std::vector<cassandra::ColumnOrSuperColumn> >&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const std::vector<std::__cxx11::basic_string<char> >&, const cassandra::ColumnParent&, const cassandra::SlicePredicate&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void multiget_slice(tcxx::function<void(std::map<std::string, std::vector<ColumnOrSuperColumn> >  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::vector<std::string> & keys, const ColumnParent& column_parent, const SlicePredicate& predicate, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7402:16: note: 	'virtual void cassandra::CassandraCobSvIf::multiget_count(std::tr1::function<void(const std::map<std::__cxx11::basic_string<char>, int>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const std::vector<std::__cxx11::basic_string<char> >&, const cassandra::ColumnParent&, const cassandra::SlicePredicate&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void multiget_count(tcxx::function<void(std::map<std::string, int32_t>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::vector<std::string> & keys, const ColumnParent& column_parent, const SlicePredicate& predicate, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7412:16: note: 	'virtual void cassandra::CassandraCobSvIf::get_range_slices(std::tr1::function<void(const std::vector<cassandra::KeySlice>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::ColumnParent&, const cassandra::SlicePredicate&, const cassandra::KeyRange&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void get_range_slices(tcxx::function<void(std::vector<KeySlice>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const ColumnParent& column_parent, const SlicePredicate& predicate, const KeyRange& range, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7422:16: note: 	'virtual void cassandra::CassandraCobSvIf::get_paged_slice(std::tr1::function<void(const std::vector<cassandra::KeySlice>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::KeyRange&, const string&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void get_paged_slice(tcxx::function<void(std::vector<KeySlice>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& column_family, const KeyRange& range, const std::string& start_column, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7433:16: note: 	'virtual void cassandra::CassandraCobSvIf::get_indexed_slices(std::tr1::function<void(const std::vector<cassandra::KeySlice>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::ColumnParent&, const cassandra::IndexClause&, const cassandra::SlicePredicate&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void get_indexed_slices(tcxx::function<void(std::vector<KeySlice>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const ColumnParent& column_parent, const IndexClause& index_clause, const SlicePredicate& column_predicate, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7443:16: note: 	'virtual void cassandra::CassandraCobSvIf::insert(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnParent&, const cassandra::Column&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void insert(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnParent& column_parent, const Column& column, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~
14:04:42  build/debug/gen/Cassandra.h:7453:16: note: 	'virtual void cassandra::CassandraCobSvIf::add(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnParent&, const cassandra::CounterColumn&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void add(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnParent& column_parent, const CounterColumn& column, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~
14:04:42  build/debug/gen/Cassandra.h:7478:16: note: 	'virtual void cassandra::CassandraCobSvIf::cas(std::tr1::function<void(const cassandra::CASResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const string&, const std::vector<cassandra::Column>&, const std::vector<cassandra::Column>&, cassandra::ConsistencyLevel::type, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void cas(tcxx::function<void(CASResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const std::string& column_family, const std::vector<Column> & expected, const std::vector<Column> & updates, const ConsistencyLevel::type serial_consistency_level, const ConsistencyLevel::type commit_consistency_level) = 0;
14:04:42                  ^~~
14:04:42  build/debug/gen/Cassandra.h:7490:16: note: 	'virtual void cassandra::CassandraCobSvIf::remove(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnPath&, int64_t, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void remove(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnPath& column_path, const int64_t timestamp, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~
14:04:42  build/debug/gen/Cassandra.h:7501:16: note: 	'virtual void cassandra::CassandraCobSvIf::remove_counter(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const cassandra::ColumnPath&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void remove_counter(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& key, const ColumnPath& path, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7512:16: note: 	'virtual void cassandra::CassandraCobSvIf::batch_mutate(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const std::map<std::__cxx11::basic_string<char>, std::map<std::__cxx11::basic_string<char>, std::vector<cassandra::Mutation> > >&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void batch_mutate(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::map<std::string, std::map<std::string, std::vector<Mutation> > > & mutation_map, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7523:16: note: 	'virtual void cassandra::CassandraCobSvIf::atomic_batch_mutate(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const std::map<std::__cxx11::basic_string<char>, std::map<std::__cxx11::basic_string<char>, std::vector<cassandra::Mutation> > >&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void atomic_batch_mutate(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::map<std::string, std::map<std::string, std::vector<Mutation> > > & mutation_map, const ConsistencyLevel::type consistency_level) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7535:16: note: 	'virtual void cassandra::CassandraCobSvIf::truncate(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void truncate(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& cfname) = 0;
14:04:42                  ^~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7542:16: note: 	'virtual void cassandra::CassandraCobSvIf::get_multi_slice(std::tr1::function<void(const std::vector<cassandra::ColumnOrSuperColumn>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::MultiSliceRequest&)'
14:04:42     virtual void get_multi_slice(tcxx::function<void(std::vector<ColumnOrSuperColumn>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const MultiSliceRequest& request) = 0;
14:04:42                  ^~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7549:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_schema_versions(std::tr1::function<void(const std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>)'
14:04:42     virtual void describe_schema_versions(tcxx::function<void(std::map<std::string, std::vector<std::string> >  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7554:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_keyspaces(std::tr1::function<void(const std::vector<cassandra::KsDef>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>)'
14:04:42     virtual void describe_keyspaces(tcxx::function<void(std::vector<KsDef>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7559:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_cluster_name(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>)'
14:04:42     virtual void describe_cluster_name(tcxx::function<void(std::string const& _return)> cob) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7564:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_version(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>)'
14:04:42     virtual void describe_version(tcxx::function<void(std::string const& _return)> cob) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7578:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_ring(std::tr1::function<void(const std::vector<cassandra::TokenRange>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void describe_ring(tcxx::function<void(std::vector<TokenRange>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& keyspace) = 0;
14:04:42                  ^~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7585:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_local_ring(std::tr1::function<void(const std::vector<cassandra::TokenRange>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void describe_local_ring(tcxx::function<void(std::vector<TokenRange>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& keyspace) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7592:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_token_map(std::tr1::function<void(const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>)'
14:04:42     virtual void describe_token_map(tcxx::function<void(std::map<std::string, std::string>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7597:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_partitioner(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>)'
14:04:42     virtual void describe_partitioner(tcxx::function<void(std::string const& _return)> cob) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7602:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_snitch(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>)'
14:04:42     virtual void describe_snitch(tcxx::function<void(std::string const& _return)> cob) = 0;
14:04:42                  ^~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7609:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_keyspace(std::tr1::function<void(const cassandra::KsDef&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void describe_keyspace(tcxx::function<void(KsDef const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& keyspace) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7623:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_splits(std::tr1::function<void(const std::vector<std::__cxx11::basic_string<char> >&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const string&, const string&, int32_t)'
14:04:42     virtual void describe_splits(tcxx::function<void(std::vector<std::string>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& cfName, const std::string& start_token, const std::string& end_token, const int32_t keys_per_split) = 0;
14:04:42                  ^~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7629:16: note: 	'virtual void cassandra::CassandraCobSvIf::trace_next_query(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>)'
14:04:42     virtual void trace_next_query(tcxx::function<void(std::string const& _return)> cob) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7630:16: note: 	'virtual void cassandra::CassandraCobSvIf::describe_splits_ex(std::tr1::function<void(const std::vector<cassandra::CfSplit>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, const string&, const string&, int32_t)'
14:04:42     virtual void describe_splits_ex(tcxx::function<void(std::vector<CfSplit>  const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& cfName, const std::string& start_token, const std::string& end_token, const int32_t keys_per_split) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7637:16: note: 	'virtual void cassandra::CassandraCobSvIf::system_add_column_family(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::CfDef&)'
14:04:42     virtual void system_add_column_family(tcxx::function<void(std::string const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const CfDef& cf_def) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7644:16: note: 	'virtual void cassandra::CassandraCobSvIf::system_drop_column_family(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void system_drop_column_family(tcxx::function<void(std::string const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& column_family) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7651:16: note: 	'virtual void cassandra::CassandraCobSvIf::system_add_keyspace(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::KsDef&)'
14:04:42     virtual void system_add_keyspace(tcxx::function<void(std::string const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const KsDef& ks_def) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7658:16: note: 	'virtual void cassandra::CassandraCobSvIf::system_drop_keyspace(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void system_drop_keyspace(tcxx::function<void(std::string const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& keyspace) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7665:16: note: 	'virtual void cassandra::CassandraCobSvIf::system_update_keyspace(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::KsDef&)'
14:04:42     virtual void system_update_keyspace(tcxx::function<void(std::string const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const KsDef& ks_def) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7672:16: note: 	'virtual void cassandra::CassandraCobSvIf::system_update_column_family(std::tr1::function<void(const std::__cxx11::basic_string<char>&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const cassandra::CfDef&)'
14:04:42     virtual void system_update_column_family(tcxx::function<void(std::string const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const CfDef& cf_def) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7680:16: note: 	'virtual void cassandra::CassandraCobSvIf::execute_cql_query(std::tr1::function<void(const cassandra::CqlResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, cassandra::Compression::type)'
14:04:42     virtual void execute_cql_query(tcxx::function<void(CqlResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& query, const Compression::type compression) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7690:16: note: 	'virtual void cassandra::CassandraCobSvIf::execute_cql3_query(std::tr1::function<void(const cassandra::CqlResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, cassandra::Compression::type, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void execute_cql3_query(tcxx::function<void(CqlResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& query, const Compression::type compression, const ConsistencyLevel::type consistency) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7698:16: note: 	'virtual void cassandra::CassandraCobSvIf::prepare_cql_query(std::tr1::function<void(const cassandra::CqlPreparedResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, cassandra::Compression::type)'
14:04:42     virtual void prepare_cql_query(tcxx::function<void(CqlPreparedResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& query, const Compression::type compression) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7709:16: note: 	'virtual void cassandra::CassandraCobSvIf::prepare_cql3_query(std::tr1::function<void(const cassandra::CqlPreparedResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&, cassandra::Compression::type)'
14:04:42     virtual void prepare_cql3_query(tcxx::function<void(CqlPreparedResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& query, const Compression::type compression) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7717:16: note: 	'virtual void cassandra::CassandraCobSvIf::execute_prepared_cql_query(std::tr1::function<void(const cassandra::CqlResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, int32_t, const std::vector<std::__cxx11::basic_string<char> >&)'
14:04:42     virtual void execute_prepared_cql_query(tcxx::function<void(CqlResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const int32_t itemId, const std::vector<std::string> & values) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7727:16: note: 	'virtual void cassandra::CassandraCobSvIf::execute_prepared_cql3_query(std::tr1::function<void(const cassandra::CqlResult&)>, std::tr1::function<void(apache::thrift::TDelayedException*)>, int32_t, const std::vector<std::__cxx11::basic_string<char> >&, cassandra::ConsistencyLevel::type)'
14:04:42     virtual void execute_prepared_cql3_query(tcxx::function<void(CqlResult const& _return)> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const int32_t itemId, const std::vector<std::string> & values, const ConsistencyLevel::type consistency) = 0;
14:04:42                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
14:04:42  build/debug/gen/Cassandra.h:7734:16: note: 	'virtual void cassandra::CassandraCobSvIf::set_cql_version(std::tr1::function<void()>, std::tr1::function<void(apache::thrift::TDelayedException*)>, const string&)'
14:04:42     virtual void set_cql_version(tcxx::function<void()> cob, tcxx::function<void(::apache::thrift::TDelayedException* _throw)> /* exn_cob */, const std::string& version) = 0;
14:04:42                  ^~~~~~~~~~~~~~~
```

(using dbuild)

**Pull request merged**
