### PR TITLE
review-checklist: mention that the guidelines are not absolute rules and can be overridden

### PR DESCRIPTION
**Pull request by avikivity**

### CODE REVIEW

**Comment by avikivity** [comment]
@scylladb/scylla-maint ping

**Comment by tgrabiec** [comment]
@avikivity There seems to be some unrelated commits in the branch.

**Comment by avikivity** [comment]
Sorry, fixed.

**Comment by tgrabiec** [comment]
@avikivity Can you change the target branch to "next"?

**Comment by tgrabiec** [comment]
> @avikivity Can you change the target branch to "next"?

Never mind, I did it myself.

**Pull request merged**
