### PR TITLE
test.py: add missing CQL test discovery

### PR DESCRIPTION
**Pull request by alecco**
Add missing build_test_list() to CQLApproval test.

Signed-off-by: Alejo Sanchez <alejo.sanchez@scylladb.com>

### CODE REVIEW

**Comment by kostja** [comment]
You don't need it, there is self.pattern and parent's build_test_list. i thnk this patchis unnecessary.

**Comment by alecco** [comment]
> You don't need it, there is self.pattern and parent's build_test_list. i thnk this patchis unnecessary.


```
$  git switch master 
Switched to branch 'master'
Your branch is up to date with 'scylla/master'.
alecco@bruce:~/src/scylla$  ./test.py --mode dev cql/lwt_test
Test cql/lwt_test not found
alecco@bruce:~/src/scylla$  git switch testpy-fix-cql-discovery 
Switched to branch 'testpy-fix-cql-discovery'
alecco@bruce:~/src/scylla$  ./test.py --mode dev cql/lwt_test
Found 1 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/1]        cql      dev   [ PASS ] lwt_test.1
------------------------------------------------------------------------------
```

**Comment by alecco** [comment]
> You don't need it, there is self.pattern and parent's build_test_list. i thnk this patchis unnecessary.

Parent is `PythonTestSuite` an it looks for `path.rglob("*_test.py"), path.rglob("test_*.py")` so it doesn't find `*.cql`.

https://github.com/alecco/scylla/blob/testpy-fix-cql-discovery/test.py#L375

**Comment by nyh** [comment]
> > You don't need it, there is self.pattern and parent's build_test_list. i thnk this patchis unnecessary.
> 
> Parent is `PythonTestSuite` an it looks for `path.rglob("*_test.py"), path.rglob("test_*.py")` so it doesn't find `*.cql`.
> 
> https://github.com/alecco/scylla/blob/testpy-fix-cql-discovery/test.py#L375

This happened because PythonTestSuite instead of fixing "pattern" to work recursively, made it unused and added code calling rglob() instead. So this fix is good, but a different fix could have been to made "pattern" work again - just be recursive (as well as supporting multiple patterns).

**Review by nyh — APPROVED** [review]

**Comment by kostja** [comment]
> > > You don't need it, there is self.pattern and parent's build_test_list. i thnk this patchis unnecessary.
> > 
> > 
> > Parent is `PythonTestSuite` an it looks for `path.rglob("*_test.py"), path.rglob("test_*.py")` so it doesn't find `*.cql`.
> > https://github.com/alecco/scylla/blob/testpy-fix-cql-discovery/test.py#L375
> 
> This happened because PythonTestSuite instead of fixing "pattern" to work recursively, made it unused and added code calling rglob() instead. So this fix is good, but a different fix could have been to made "pattern" work again - just be recursive (as well as supporting multiple patterns).

pattern is not unused, it can be overridden with build_test_list. I still don't understand the fix. build_test_list is defined in parent TestSuite to use suite.pattern. suite.pattern is defined for CQLApprovalTestSuite, so it should be used. What am I missing?

**Comment by kostja** [comment]
Maybe a better fix is to remove pattern altogether and add a bit of a copy paste?

**Pull request closed without merging**
