### PR TITLE
database: remove variadic future from query() and query_mutations()

### PR DESCRIPTION
**Pull request by avikivity**
Variadic futures are deprecated; replace with future<std::tuple<...>>.

Tests: unit (dev)

### CODE REVIEW

**Comment by espindola** [comment]
LGTM

**Comment by denesb** [comment]
I would say we should also add a type to return from `database::query()`, but we already returned a tuple before, it is just more obvious now.

**Comment by avikivity** [comment]
ping?

**Comment by avikivity** [comment]
@scylladb/scylla-maint ping

**Comment by psarna** [comment]
queued as beaeda5234f062dc96f6

**Comment by avikivity** [comment]
Closing as merged.

**Pull request closed without merging**
