### PR TITLE
Delete table snapshot

### LINKED ISSUE #5658: Scylla API delete snapshot for a table
In backup when uploading a huge number of tables we want to release snapshot hard links as soon as possible i.e. when we know that snapshot for a given table is safely stored.

I think `DELETE /storage_service/snapshots` could get a `cf` parameter similar to `POST` endpoint.

### PR DESCRIPTION
**Pull request by amnonh**
This series adds an option to the API that supports deleting a specific table from a snapshot.
The implementation works in a similar way to the option to specify specific keyspaces when deleting a snapshot.
The motivation is to allow reducing disk-space when using the snapshot for backup.
A dtest PR is sent to the dtest repository.
Fixes #5658

Original PR #5805

Tests: (database_test) (dtest snapshot_test.py:TestSnapshot.test_cleaning_snapshot_by_cf)

### CODE REVIEW

**Comment by amnonh** [comment]
@psarna I've recreated a PR,
The original one hit an issue in the testing that used the original clear_snapshot a victim of removing the default parameter.
I've tested that it compiles and passes now

**Comment by psarna** [comment]
Thanks. If all unit tests passed, please add a `Tests: unit(dev)` footer to the commit message or issue description - this way maintainers will know that tests were run and passed without issues. Adding this footer is a good practice I took from https://github.com/scylladb/scylla/blob/master/HACKING.md and now I'm trying to revive it :)

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
@psarna is there anything else I need to change?

**Comment by psarna** [comment]
Nope, looks like we're all set, I just didn't get an e-mail from github that the description was updated, so I was unaware of the change :) I'll re-review and requeue today.

**Comment by amnonh** [comment]
@psarna sorry for that, I should have mentioned you when I did

**Comment by psarna** [comment]
don't worry, I only blame github (:

**Pull request merged**
