### PR TITLE
repair: Relax node selection in decommission for non network topology strategy

### LINKED ISSUE #6564: Nodetool decommission can not find new node in local dc despite the node exist (multi DC test)
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200521.c29ccdea7
Cluster size: 4 nodes (multi DC)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0421a30fbb1b10b4a(us-east-1), ami-0961b54b8b942b1a6(us-west-2)

[Jenkins job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/yulia/job/staging-counters-multidc/22)

Test: longevity_counters-multidc

Setup:
- 2 nodes (i3.2xlarge) in us-east-1
- 2 nodes (i3.2xlarge) in us-west-2

Nemesis: grow_shrink_cluster

This nemesis perform 2 steps:

Step 1 -  GrowCluster - add new node.
New node  5 (35.167.237.42) was joined to the cluster, DC us-west-2scylla_node_west
```
< t:2020-06-01 16:27:26,060 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: Datacenter: us-west-2scylla_node_west
< t:2020-06-01 16:27:26,069 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: =====================================
< t:2020-06-01 16:27:26,069 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: Status=Up/Down
< t:2020-06-01 16:27:26,069 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: |/ State=Normal/Leaving/Joining/Moving
< t:2020-06-01 16:27:26,069 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: --  Address        Load       Tokens       Owns    Host ID                               Rack
< t:2020-06-01 16:27:26,073 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: UN  34.217.82.82   615.81 KB  256          ?       50e8c783-c3b7-421e-96f3-c4741d700e66  2b
< t:2020-06-01 16:27:26,074 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: UN  52.37.217.41   623.52 KB  256          ?       511249ad-164b-4aff-a0d2-c7d9f70cae0c  2b
< t:2020-06-01 16:27:26,086 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: UN  35.167.237.42  1.72 MB    256          ?       fb7de323-d4a3-48d6-ae23-3ed6d40d1fc2  2b
```

Step 2 - ShrinkCLuster
Node 5 selected for decommission 
```
< t:2020-06-01 16:32:43,510 f:nemesis.py      l:1871 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: Next node will be removed Node longevity-counters-multidc-healthch-db-node-00751e96-5 [35.167.237.42 | 172.31.43.115] (seed: False)
< t:2020-06-01 16:32:43,510 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@35.167.237.42]: Running command "nodetool  decommission "...
< t:2020-06-01 16:32:53,400 f:cluster.py      l:1429 c:sdcm.cluster         p:DEBUG > 2020-06-01T16:32:45+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: starts
< t:2020-06-01 16:32:53,400 f:cluster.py      l:1429 c:sdcm.cluster         p:DEBUG > 2020-06-01T16:32:45+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] storage_service - LEAVING: sleeping 30000 ms for batch processing and pending range setup
```

After 22 sec ```nodetool decommission``` command was finished with exit code 1. Reason: ``` can not find new node in local dc=us-west-2scylla_node_west```:
```
< t:2020-06-01 16:33:15,569 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: std::runtime_error (decomm
ission_with_repair: keyspace=system_traces, range=(-8724275575448344547, -8717461350350511909], current_replica_endpoints={54.91.198.246, 35.167.237.42}, new_replica_endpoints={54.91.198.246, 3.92.224.239}, can not find new node in local
 dc=us-west-2scylla_node_west)
< t:2020-06-01 16:33:15,591 f:remote.py       l:160  c:sdcm.remote          p:ERROR > RemoteCmdRunner [centos@35.167.237.42]: Error executing command: "nodetool  decommission "; Exit status: 1
< t:2020-06-01 16:33:15,591 f:remote.py       l:162  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@35.167.237.42]: STDOUT: 461350350511909], current_replica_endpoints={54.91.198.246, 35.167.237.42}, new_replica_endpoints={54.91.198.246, 3.92.224.239}, can not find new node in local dc=us-west-2scylla_node_west)
< t:2020-06-01 16:33:15,591 f:remote.py       l:162  c:sdcm.remote          p:DEBUG > See 'nodetool help' or 'nodetool help <command>'.
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > Node longevity-counters-multidc-healthch-db-node-00751e96-5 [35.167.237.42 | 172.31.43.115] (seed: False): Command 'nodetool  decommission ' error: Encountered a bad command exit code!
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > Command: 'nodetool  decommission '
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > Exit code: 1
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > Stdout:
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: std::runtime_error (decommission_with_repair: keyspace=system_traces, range=(-8724275575448344547, -8717461350350511909], current_replica_endpoints={54.91.198.246, 35.167.237.42}, new_replica_endpoints={54.91.198.246, 3.92.224.239}, can not find new node in local dc=us-west-2scylla_node_west)
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > See 'nodetool help' or 'nodetool help <command>'.
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > Stderr:
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
< t:2020-06-01 16:33:15,591 f:cluster.py      l:2447 c:sdcm.cluster_aws     p:CRITICAL > 
```

But from node log I can see that decommissioning not failed, continue to run.

From node 5 log 

Decommissioning is started:
```
2020-06-01T16:32:45+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: starts
2020-06-01T16:32:45+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] storage_service - LEAVING: sleeping 30000 ms for batch processing and pending range setup
2020-06-01T16:33:15+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] storage_service - DECOMMISSIONING: unbootstrap starts
2020-06-01T16:33:15+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] repair - decommission_with_repair: started with keyspaces={system_traces, system_distributed, system_auth, keyspace1, scylla_bench, ks_truncate}, leaving_node=35.167.237.42
```

Gossip status is changed to LEAVING:
```
2020-06-01T16:39:29+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] gossip - My status = LEAVING
```

Shutdown completed:
```
2020-06-01T16:39:31+00:00  longevity-counters-multidc-healthch-db-node-00751e96-5 !INFO    | scylla: [shard 0] init - Scylla version 666.development-0.20200521.c29ccdea7 shutdown complete.
```

But node status was not changed to LEFT, stuck with LEAVING:
```
< t:2020-06-01 16:39:25,624 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: Datacenter: us-west-2scylla_node_west
< t:2020-06-01 16:39:25,624 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: =====================================
< t:2020-06-01 16:39:25,624 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: Status=Up/Down
< t:2020-06-01 16:39:25,625 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: |/ State=Normal/Leaving/Joining/Moving
< t:2020-06-01 16:39:25,625 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: --  Address        Load       Tokens       Owns    Host ID                               Rack
< t:2020-06-01 16:39:25,688 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: UN  34.217.82.82   615.81 KB  256          ?       50e8c783-c3b7-421e-96f3-c4741d700e66  2b
< t:2020-06-01 16:39:25,688 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: UN  52.37.217.41   623.52 KB  256          ?       511249ad-164b-4aff-a0d2-c7d9f70cae0c  2b
< t:2020-06-01 16:39:25,691 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@35.167.237.42]: UL  35.167.237.42  1.72 MB    256          ?       fb7de323-d4a3-48d6-ae23-3ed6d40d1fc2  2b
```

At ```2020-06-01T16:40:45+00:00``` node 5 was restarted by another nemesis (seems because of the node is in UP status)

Logs:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                 Log links for testrun with test id 00751e96-45b8-418d-b238-40e5e4e1cf87                                                                                                  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                                     |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20190101_010101 | prometheus  | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/prometheus_snapshot_20200601_223253.tar.gz                                                                                                           |
| 20200601_221636 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_221636/grafana-screenshot-overview-20200601_222016-longevity-counters-multidc-healthch-monitor-node-00751e96-1.png                          |
| 20200601_221636 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_221636/grafana-screenshot-scylla-per-server-metrics-nemesis-20200601_221636-longevity-counters-multidc-healthch-monitor-node-00751e96-1.png |
| 20200601_222347 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_222347/grafana-screenshot-overview-20200601_222702-longevity-counters-multidc-healthch-monitor-node-00751e96-1.png                          |
| 20200601_222347 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_222347/grafana-screenshot-scylla-per-server-metrics-nemesis-20200601_222347-longevity-counters-multidc-healthch-monitor-node-00751e96-1.png |
| 20200601_223440 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_223440/db-cluster-00751e96.zip                                                                                                              |
| 20200601_223440 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_223440/loader-set-00751e96.zip                                                                                                              |
| 20200601_223440 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_223440/monitor-set-00751e96.zip                                                                                                             |
| 20200601_223440 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/00751e96-45b8-418d-b238-40e5e4e1cf87/20200601_223440/sct-runner-00751e96.zip                                                                                                              |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by asias**
In decommission operation, current code requires a node in local dc to
sync data with. This requirement is too strong for a non network topology
strategy. For example, consider:
```
   n1 dc1
   n2 dc1
   n3 dc2
```
n2 runs decommission operation. For a keyspace with simple strategy and
RF = 2, it is possible n3 is the new owner but n3 is not in the same dc
as n2.

To fix, perform the dc check only for the network topology strategy.

Fixes #6564

### CODE REVIEW

**Comment by avikivity** [comment]
Please follow up with a break-up of this huge function into smaller pieces.

**Comment by asias** [comment]
> Please follow up with a break-up of this huge function into smaller pieces.

Do you mean splitting do_decommission_removenode_with_repair into smaller ones? It is 150 lines of code with comments and 110 lines of code without.

**Comment by avikivity** [comment]
Yes, that is long quite (for me).

**Comment by asias** [comment]
> Yes, that is quite long (for me).

ok

**Pull request merged**
