### PR TITLE
test/cql-pytest: reproducer for bug in index+filter+limit

### PR DESCRIPTION
**Pull request by nyh**
This patch adds reproducing tests for wrong handling of LIMIT in a query
which uses a secondary index *and* filtering, described in issue #10649.

In that case, Scylla incorrectly limits the number of rows found in the
index *before* the filtering, while it should limit the number of rows
*after* the filtering.

The tests in this patch (which xfail on Scylla, and pass on Cassandra)
go beyond the minimum required to reproduce this bug. It turns out that
there are different sub-cases of this problem that go through different
code paths, namely whether the base table has clustering keys or just
partition keys, and whether the overall LIMITed result spans more than
one page. So these tests attempt to also cover all these sub-cases.
Without all these test sub-cases, an incomplete and incorrect fix of this
bug may, by chance, cause the original test to succeed.

Refs #10649

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

### CODE REVIEW

**Comment by psarna** [comment]
I restarted the CI test manually - I have no idea if that's the procedure, but it's "pending" on GitHub, while Jenkins reported that the build failed with 0 failed tests. So I suspect the cause is as trivial as spot termination or something similar.

**Comment by nyh** [comment]
> I restarted the CI test manually - I have no idea if that's the procedure, but it's "pending" on GitHub, while Jenkins reported that the build failed with 0 failed tests. So I suspect the cause is as trivial as spot termination or something similar.

@benipeled it seems that a fairly high number of CI runs get "spot termination" (do you have a statistic?). Sure, one option is to automate the restart in this case. But did we also consider getting regular VMs instead of spot instances - how much will that cost? Did we consider splitting test runs in a way that allows restarting a CI run from the middle instead of doing all of it again? I'm not saying we need to do all of this now (even Rome wasn't built in a day), but maybe it's something we can think about.

**Comment by benipeled** [comment]
> > I restarted the CI test manually - I have no idea if that's the procedure, but it's "pending" on GitHub, while Jenkins reported that the build failed with 0 failed tests. So I suspect the cause is as trivial as spot termination or something similar.
> 
> @benipeled it seems that a fairly high number of CI runs get "spot termination" (do you have a statistic?). Sure, one option is to automate the restart in this case. But did we also consider getting regular VMs instead of spot instances - how much will that cost? Did we consider splitting test runs in a way that allows restarting a CI run from the middle instead of doing all of it again? I'm not saying we need to do all of this now (even Rome wasn't built in a day), but maybe it's something we can think about.

spot-termination is currently one of the big pain for scylla-ci. we have three servers at the office lab we're going to use for the CI runs (and other builds) - I hope to make them ready soon,

It should reduce the spot-termination failures but if we'll still have too many failures we'll check the on-demand options.

PS> we don't have statistics for spot-termination but I have a feeling that in the last week there have been a lot more falls than we had in the past I can see nothing that could cause it.

**Comment by benipeled** [comment]
> spot-termination is currently one of the big pain for scylla-ci. we have three servers at the office lab we're going to use for the CI runs (and other builds) - I hope to make them ready soon,
> 

https://github.com/scylladb/scylla-pkg/pull/2909/files

**Pull request closed without merging**
