### PR TITLE
fix: incorrect AWS user-data url

### PR DESCRIPTION
**Pull request by bentsi**
we used http://169.254.169.254/latest/meta-data/user-data
but correct one http://169.254.169.254/latest/user-data
Fixes: https://github.com/scylladb/scylla-machine-image/issues/63

### CODE REVIEW

**Review by fruch — APPROVED** [review]
LGTM

**Comment by bentsi** [comment]
@avikivity @penberg can you review and merge, this is blocking all SCT runs

**Comment by tzach** [comment]
@bentsi does this means user-data did not worked till this PR?
If I remember correctly I tested it myself (or did I?)

**Comment by bentsi** [comment]
@tzach it stopped working after merging #7080

**Comment by tzach** [comment]
So the bug was not part of any release, right?

**Comment by fruch** [comment]
> So the bug was not part of any release, right?

Yes, it wasn't part of any release, 
just part of our fail-fast dance on master...

**Pull request closed without merging**
