### PR TITLE
docs: dev: document pytest run convenience script

### PR DESCRIPTION
**Pull request by nuivall**

### CODE REVIEW

**Review by nyh — CHANGES_REQUESTED** [review]
I think you did not correctly explain the benefit of the test/alternator/run (et al.) compared to test.py which is the topic of this document: Running test/alternator/run isn't significantly faster than running test.py because after all, the latter simply runs the former. For cql-pytest the story is a bit different (test.py does **not** run test/cql-pytest/run but does something similar on its own) but I don't think it's much faster (unless test.py is buggy? or maybe test.py uses a slow disk or something?)

In my mind, test/{alternator,cql-pytest,redis,...}/run have other advantages over test.py (besides the theoretical benefit of non-monolithic-ness):
1. test/*/run allow you to also run your test against the "competitor" - see `test/cql-pytest/run-cassandra` and `test/alternator/run --aws`. test.py simply doesn't support this concept!
2. test/*/run allow you to run only a single test file or a single test function, which test.py can't (it does have some partial support for running a single test file - but not a single test function).
3. test/*/run can let you pass many other pytest options which can be convenient. Options like --count, -v, -s, --durations (to see the slowest tests) and so on and so on. test.py supports some of these things, but there's a whole world of pytest plugins that you can use when the run script passes all pytest options on to pytest.

CC @kostja @alecco

**Comment by nuivall** [comment]
> I think you did not correctly explain the benefit of the test/alternator/run (et al.) compared to test.py which is the topic of this document: Running test/alternator/run isn't significantly faster than running test.py because after all, the latter simply runs the former. For cql-pytest the story is a bit different (test.py does **not** run test/cql-pytest/run but does something similar on its own) but I don't think it's much faster (unless test.py is buggy? or maybe test.py uses a slow disk or something?)
> 
> In my mind, test/{alternator,cql-pytest,redis,...}/run have other advantages over test.py (besides the theoretical benefit of non-monolithic-ness):
> 
> 1. test/*/run allow you to also run your test against the "competitor" - see `test/cql-pytest/run-cassandra` and `test/alternator/run --aws`. test.py simply doesn't support this concept!
> 2. test/*/run allow you to run only a single test file or a single test function, which test.py can't (it does have some partial support for running a single test file - but not a single test function).
> 3. test/*/run can let you pass many other pytest options which can be convenient. Options like --count, -v, -s, --durations (to see the slowest tests) and so on and so on. test.py supports some of these things, but there's a whole world of pytest plugins that you can use when the run script passes all pytest options on to pytest.
> 
> CC @kostja @alecco

I wasn't really wanted to compare it any way to test.py. The section is about python tests. And before I was using simply pytest. That's why I put info about speed because it's much faster than starting scylla with typical config and there is nowhere any info about this huge advantage.

It can be improved but I didn't want to document a thing I haven't used (because didn't know about it or forgot...) just some link for people getting familiar with vast sea of scylla test approaches.

**Comment by nyh** [comment]
> I wasn't really wanted to compare it any way to test.py. The section is about python tests. And before I was using simply pytest. That's why I put info about speed because it's much faster than starting scylla with typical config and there is nowhere any info about this huge advantage.

But reading the paragraph you wrote, it's not clear what is faster than what. It sounds like you're comparing test.py (the topic of this whole document) to the alternative method you mentioned (test/cql-pytest/run). Now I understand that you are comparing test/cql-pytest/run to a third method - of running Scylla manually on your own (which is both slow and to be honest, not easy to remember which options to use) and running "pytest" against it. But this third method wasn't described anywhere in this document (as far as I can tell), so why compare to it, and how can the reader understand that you're comparing to that unmentioned third method? Maybe you should just explicitly say that this third method (cd to a directory and run "pytest" in it) exists before comparing to it. Note that this doesn't work on all "Python" suite directories - it doesn't work in test/topology ("cd topology; pytest" doesn't work) because unfortunately (in my view) the authors of this test suites decided to go "monolithic" and test/topology needs services from test.py and can't run stand-alone.

> It can be improved but I didn't want to document a thing I haven't used (because didn't know about it or forgot...) just some link for people getting familiar with vast sea of scylla test approaches.

You can mention that some (but not all! not test/topology!) of these test suites can also be run by a stand-alone script test/*/run, and refer to test/*/README.md for documentation on each one.

**Comment by nuivall** [comment]
@nyh ping

**Review by nyh — APPROVED** [review]

**Pull request closed without merging**
