### PR TITLE
config: ignore enable_sstables_mc_format flag

### PR DESCRIPTION
**Pull request by haaawk**
Don't allow users to disable MC sstables format any more.
We would like to retire some old cluster features that has been around
for years. Namely MC_SSTABLE and UNBOUNDED_RANGE_TOMBSTONES. To do this
we first have to make sure that all existing clusters have them enabled.
It is impossible to know that unless we stop supporting
enable_sstables_mc_format flag.

Test: unit(dev)

Refs #8352

Signed-off-by: Piotr Jastrzebski <piotr@scylladb.com>

### CODE REVIEW

**Comment by psarna** [comment]
I wonder if we won't have any rollback issues after this series when some of the nodes start writing in mc, and then we roll back and have a mixed set of sstables on these two nodes. Now, if we decide to stream from these two nodes to another node which doesn't have mc sstables enabled, it will still be possible for that other node to read (and compact) the received mc sstables, right?

Aside from the question above, looks good to me.

**Comment by haaawk** [comment]
This change won't make nodes to write mc. They will still write la/ka as long as at least a single node in a cluster does not have MC_SSTABLE enabled. This means during rolling upgrade if cluster was using la/ka then mc won't be used until after all the nodes are upgraded. @psarna

**Comment by avikivity** [comment]
> This change won't make nodes write mc straight away. They will still write la/ka as long as at least a single node in a cluster does not have MC_SSTABLE enabled.

I don't see that. 

> This means during rolling upgrade if cluster was using la/ka then mc won't be used until after all the nodes are upgraded. @psarna

**Comment by avikivity** [comment]
> I wonder if we won't have any rollback issues after this series when some of the nodes start writing in mc, and then we roll back and have a mixed set of sstables on these two nodes. Now, if we decide to stream from these two nodes to another node which doesn't have mc sstables enabled, it will still be possible for that other node to read (and compact) the received mc sstables, right?
> 
> Aside from the question above, looks good to me.

There's no problem writing mc sstables as long as the version you roll back to can read mc sstables. We don't send sstables over the wire, we send fragment streams, so the local sstable format has no effect on the cluster.

What does have effect is using features that are only supported by mx format - open-ended range tombstones. But we won't start using them until the entire cluster reports that it is using mx sstables.

**Comment by haaawk** [comment]
> > This change won't make nodes write mc straight away. They will still write la/ka as long as at least a single node in a cluster does not have MC_SSTABLE enabled.
> 
> I don't see that.

The flag controls only whether a particular node enables MC_SSTABLE or not. Nodes start to use MC format only after MC_SSTABLE is enabled on all nodes. When we're doing rolling upgrade from a cluster that has MC format disabled then all the old nodes have MC_SSTABLE disabled. Each upgraded node will have MC_SSTABLE enabled but the feature won't be enabled on the whole cluster until after all nodes are upgraded. Does that help @avikivity or do you want code pointers?

**Comment by haaawk** [comment]
@avikivity by default selected format is LA even when the flag is set to true -> https://github.com/scylladb/scylla/blob/fd1dd0eac7a303ceaa9f3ff643c4848506b0c85c/db/sstables-format-selector.hh#L67

The format is changed in feature_enabled_listener::on_enabled -> https://github.com/scylladb/scylla/blob/fd1dd0eac7a303ceaa9f3ff643c4848506b0c85c/db/sstables-format-selector.cc#L40

We've got _mc_feature_listener -> https://github.com/scylladb/scylla/blob/fd1dd0eac7a303ceaa9f3ff643c4848506b0c85c/db/sstables-format-selector.hh#L64

Its on_enabled member function is called only after MC_SSTABLE is enabled on the whole cluster -> https://github.com/scylladb/scylla/blob/fd1dd0eac7a303ceaa9f3ff643c4848506b0c85c/db/sstables-format-selector.cc#L78

**Comment by haaawk** [comment]
@avikivity @psarna ping

**Comment by avikivity** [comment]
> > > This change won't make nodes write mc straight away. They will still write la/ka as long as at least a single node in a cluster does not have MC_SSTABLE enabled.
> > 
> > 
> > I don't see that.
> 
> The flag controls only whether a particular node enables MC_SSTABLE or not. Nodes start to use MC format only after MC_SSTABLE is enabled on all nodes. When we're doing rolling upgrade from a cluster that has MC format disabled then all the old nodes have MC_SSTABLE disabled. Each upgraded node will have MC_SSTABLE enabled but the feature won't be enabled on the whole cluster until after all nodes are upgraded. Does that help @avikivity or do you want code pointers?

It helps (I forgot about the MC_SSTABLE feature).

**Comment by mykaul** [comment]
> @avikivity please backport to 4.5 and 2021.1

@avikivity - do we need this in 2021.1?

**Comment by denesb** [comment]
> > @avikivity please backport to 4.5 and 2021.1
> 
> @avikivity - do we need this in 2021.1?

This was a joke. We don't backport changes like this. This change is a forward-looking one, removing a feature flag that makes no sense anymore.

**Pull request closed without merging**
