### PR TITLE
Unify CQL and Redis server code

### PR DESCRIPTION
**Pull request by penberg**
The Redis server started as a copy of the CQL server, but did not
receive all the fixes of the CQL server over time. For example, commit
1a8630e ("transport: silence "broken pipe" and "connection reset by
peer" errors") was only done on the CQL server.

To remedy the situation, this pull request unifies code between the CQL
and Redis servers by introducing a "generic_server" component, and
switching CQL and Redis to use it.

Test: dtest(dev)

### CODE REVIEW

**Comment by penberg** [comment]
This is take 2 of https://github.com/scylladb/scylla/pull/8237, which had a bug in error handling.

**Comment by nyh** [comment]
@penberg why is this pull request in "draft mode"? Is it not ready for commit?
By the way, what did you end up doing on that not-working handle_exception thing?

**Comment by penberg** [comment]
@nyh There's one more full `dtest` run going on. Will switch from draft to regular once that sanity check is complete.

**Comment by nyh** [comment]
@penberg what's the status of this? Did the dtest ever finish? Do you want to commit this series?

**Comment by nyh** [comment]
@penberg just curious if the tests passed, or what?

**Comment by penberg** [comment]
@nyh There was a dtest failure that I did not yet manage to investigate (could be unrelated). Will try to wrap up this this week.

**Comment by penberg** [comment]
@nyh I investigated the test failure, and it was unrelated to this patch series. Please review.

**Comment by penberg** [comment]
@nyh ping

**Pull request merged**
