### PR TITLE
alternator: work around header case sensitivity

### LINKED ISSUE #6319: AWS Dynamodb CPP SDK can't work with scylla alternator
I use dynamodb cpp sdk to operate scylla, scylla always returns "Unsupported operation".
Python sdk works fine. 

Scylla version: 4.0 rc1
dynamodb cpp sdk version: master 

Tcpdump result of list tables operation:

```
POST / HTTP/1.1
Accept: */*
content-length: 16
content-type: application/x-amz-json-1.0
host: 10.10.10.16:8016
user-agent: aws-sdk-cpp/1.7.322 Linux/3.10.0-327.el7.x86_64 x86_64 GCC/8.3.1
x-amz-api-version: 2012-08-10
x-amz-target: DynamoDB_20120810.ListTables

{
	"Limit":	50
}HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 106
Server: Seastar httpd
Date: 29 Apr 2020 09:13:54 GMT

{"__type":"com.amazonaws.dynamodb.v20120810#UnknownOperationException","message":"Unsupported operation "}HTTP/ 404 Not Found
Content-Type: application/json
Content-Length: 37
Date: 29 Apr 2020 09:13:54 GMT
Server: Seastar httpd

{"message": "Not found", "code": 404}
```
Other operations, like create table, put item have same problems.
I use the same code to test dynamodb local, it works fine. 
Besides, it seems that scylla alternator doesn't support 100-continue header, which is enabled in cpp sdk by default.

### PR DESCRIPTION
**Pull request by psarna**
It turns out that the official AWS SDK C++ driver sends
the X-Amz-Target header in lowercase, which triggers a bug
in Seastar HTTP server.
As a quick workaround to enable more drivers to work seamlessly
with alternator, all-lowercase and all-uppercase headers
are also checked just in case.

Tests: alternator(local)
Refs https://github.com/scylladb/seastar/issues/636
Fixes #6319

### CODE REVIEW

**Comment by nyh** [comment]
I'd prefer it we get your fix into Seastar instead of doing such a workaround that we'll need to undo later.
However, we need to make sure that the Seastar fix also reaches 4.0....

**Comment by psarna** [comment]
Updating Seastar for 4.0 was precisely my concern - I'm not sure if updating seastar for a forked branch is recommended. I'm also in favour of fixing it in Seastar only, but in case we don't manage it, this workaround at least works for the cpp driver.

**Comment by nyh** [comment]
This is the second patch we're doing for Seastar's HTTP server that we need to backport to 4.0 - the previous one was the date format patch, which I added a "backport 4.0" for and I think, at least I hope (but didn't verify...) that @avikivity backported. I also don't know how we backport Seastar patches. This is so messy :-(
But your patch here seems so unnecessary if Seastar is fixed. Also in theory it's not enough because clients could spell differently a lot of headers, not just this one...

**Comment by avikivity** [comment]
Looks like this will be obsoleted by c7c8bd0978f835d61f2e4790e8dba708acce1473, no?

**Comment by nyh** [comment]
@psarna @avikivity I thought the intention was to drop this pull request, because the Seastar patch is already committed, so this patch isn't needed?

**Comment by psarna** [comment]
Yes, I'm just waiting for c7c8bd0 to get promoted and I'll close this pull request. Or actually, no point in waiting, I'll just close it now.

**Pull request closed without merging**
