### PR TITLE
[branch-4.4] database: clear inactive reads in stop()

### PR DESCRIPTION
**Pull request by denesb**
If any inactive read is left in the semaphore, it can block
`database::stop()` from shutting down, as sstables pinned by these reads
will prevent `sstables::sstables_manager::close()` from finishing. This
causes a deadlock.
It is not clear how inactive reads can be left in the semaphore, as all
users are supposed to clean up after themselves. Post 4.4 releases don't
have this problem anymore as the inactive read handle was made a RAII
object, removing the associated inactive read when destroyed. In 4.4 and
earlier release this wasn't so, so errors could be made. Normally this
is not a big issue, as these orphaned inactive reads are just evicted
when the resources they own are needed, but it does become a serious
issue during shutdown. To prevent a deadlock, clear the inactive reads
earlier, in `database::stop()` (currently they are cleared in the
destructor). This is a simple and foolproof way of ensuring any
leftover inactive reads don't cause problems.

Fixes: #8561

Tests: unit(dev)

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]

**Comment by denesb** [comment]
@avikivity I can see you added some commits referencing this PR, did those get merged? I guess the PR is not closed because it is not merged into master.

**Comment by avikivity** [comment]
Those commits are backports to 4.3.

Indeed auto-close only works on master.

**Comment by avikivity** [comment]
Closed by 840ca4139326bc3ee9398fbe8a1b124ebe668e54.

**Comment by avikivity** [comment]
Backported to 4.3.

**Pull request closed without merging**
