### PR TITLE
cql3: disentangle column_identifier from selectable

### PR DESCRIPTION
**Pull request by avikivity**
column_identifier serves two purposes: a value type used to denote an
identifier (which may or may not map to a table column), and `selectable`
implementation used for selecting table columns. This stands in the way
of further refactoring - the unification of the WHERE clause prepare path
(prepare_expression()) and the SELECT clause prepare path
(prepare_selectable()).

Reduce the entanglement by moving the selectable-specific parts to a new
type, selectable_column, and leaving column_identifier as a pure value type.

### CODE REVIEW

**Comment by avikivity** [comment]
@cvybhu review ping

**Review by psarna — APPROVED** [review]
Sounds good, I remember that returning column names not associated with any table used to be quite convoluted.

**Review by cvybhu — COMMENTED** [review]
lgtm,
although I'm not sure if I understand why are we doing this.
Do we want to have single `prepare_expression` that works for both selectables and WHERE?
Will `selectable_column` be a variant of `expression` in the future?
But then why is it hidden in a `.cc` file?

**Comment by avikivity** [comment]
> lgtm, although I'm not sure if I understand why are we doing this. Do we want to have single `prepare_expression` that works for both selectables and WHERE?

Currently, prepare_selectable does two things: it performs (very minimal) type checks (for function calls), and it creates the selectables. I'd like to have it first call prepare_expression() to perform the type checks, and then continue as usual to prepare the selectables.

> Will `selectable_column` be a variant of `expression` in the future? But then why is it hidden in a `.cc` file?

No, we have column_value. Today, prepare_selectable() takes an unresolved_identifier and creates a column_identifier from it. I'd like to have this instead: prepare_expression takes an unresolved_identifier and converts it to column_value, and prepare_selectable() converts the column_value to a selectable_column (which stays outside the expression hierarchy).

This unifies column handling in WHERE and SELECT clause. Right now prepare_expression never sees unresolved_identifier and prepare_selectable never sees column_value.

**Comment by avikivity** [comment]
v2: fix typo in comment

**Comment by avikivity** [comment]
@psarna merge ping

**Comment by psarna** [comment]
merge pong

**Pull request merged**
