### PR TITLE
rjson: Add throwing allocator

### LINKED ISSUE #8521: rapidjson's default allocator does not handle allocation failures properly
Spin-off from #8515

Scylla uses the rapidjson library for parsing JSON documents. Unfortunately, as observed in Tencent/rapidjson#1168, Tencent/rapidjson#1359 and Tencent/rapidjson#1269, once the allocation fails due to not enough memory, rapidjson's default behavior is undefined - it does not check whether its allocator returned a proper address or null and proceeds, which usually results in a segmentation fault if we're lucky or memory corruption if we're less so.

One workaround to consider is overriding the default allocator to throw an exception once it's unable to allocate/reallocate memory. The request would still fail, but at least it would do so gracefully in a controlled fashion. Rapidjson's allocator is a concept implementing 3 methods:
https://rapidjson.org/classrapidjson_1_1_allocator.html
```cpp
concept Allocator {
    static const bool kNeedFree;    //!< Whether this allocator needs to call Free().
 
    // Allocate a memory block.
    // \param size of the memory block in bytes.
    // \returns pointer to the memory block.
    void* Malloc(size_t size);
 
    // Resize a memory block.
    // \param originalPtr The pointer to current memory block. Null pointer is permitted.
    // \param originalSize The current size in bytes. (Design issue: since some allocator may not book-keep this, explicitly pass to it can save memory.)
    // \param newSize the new size in bytes.
    void* Realloc(void* originalPtr, size_t originalSize, size_t newSize);
 
    // Free a memory block.
    // \param pointer to the memory block. Null pointer is permitted.
    static void Free(void *ptr);
};
```
It should be simple enough to provide a wrapper over the default allocator, but it should be preceded with code inspection and tests to ensure that throwing does not leave internal rapidjson objects in invalid state.

### PR DESCRIPTION
**Pull request by psarna**
This series adds a wrapper for the default rjson allocator which throws on allocation/reallocation failures. It's done to work around several rapidjson (the underlying JSON parsing library) bugs - in a few cases, malloc/realloc return value is not checked, which results in dereferencing a null pointer (or an arbitrary pointer computed as 0 + `size`, with the `size` parameter being provided by the user). The new allocator will throw an `rjson:error` if it fails to allocate or reallocate memory.
This series comes with unit tests which checks the new allocator behavior and also validates that an internal rapidjson structure which we indirectly rely upon (Stack) is not left in invalid state after throwing. The last part is verified by the fact that its destructor ran without errors.

Fixes #8521 
Refs #8515

Tests:
 * unit(release)
 * YCSB: inserting data similar to the one mentioned in #8515 - 1.5MB objects clustered in partitions 30k objects in size - nothing crashed during various YCSB workloads, but nothing also crashed for me locally before this patch, so it's not 100% robust
 relevant YCSB workload config for using 1.5MB objects:
```yaml
# The number of fields in a record
fieldcount=150
# The size of each field (in bytes)
fieldlength=10000
```

### CODE REVIEW

**Comment by psarna** [comment]
If somebody has another idea how to verify that throwing inside rapidjson is always fine, I'd be glad to hear it. I suppose that throwing and leaving a rapidjson object in an unspecified state is better than continuing to use `nullptr` as if it was valid, but it would be even better to have certainty that everything still works.
I also browsed the rapidjson code, since it's all headers, and I didn't find any obvious problems.

**Comment by avikivity** [comment]
Looks fine. What about a test that injects allocation failures at random points?

**Comment by psarna** [comment]
I'll try that + ycsb. The result would be acceptable if ycsb sometimes fails, but Scylla should under no circumstances crash.

**Comment by psarna** [comment]
I ran a few hundred YCSB workloads with various concurrency and an allocator which introduces allocation/reallocation failures from time to time and didn't manage to kill Scylla. The failures definitely occurred, as witnessed both in scylla logs and in ycsb output

**Review by nyh — APPROVED** [review]

**Comment by psarna** [comment]
There's a small known issue with debug mode tests - I'll dequeue and push a fixed version soon.

**Comment by nyh** [comment]
Oh :-( I also had this problem in the past in another test (of printing unlimited precision numbers): while in release mode allocating a ridiculous amount of memory just fails, in debug mode - without Seastar's allocator - it can do all sorts of crazy stuff - such as taking all your memory.

I wonder if we shouldn't just fix Seastar's debug allocator - it should check if the allocation is larger than some limit, and if it is, it should fail immediately and not call the system malloc. After all the point of debug mode is to behave like release mode - not to create new bugs that don't exist in release mode.

**Comment by psarna** [comment]
Even after I reduce the number (to still be huge, but less than the limit printed by the address sanitizer), it actually fails immediately, and it's part of the problem - the test is aborted with a failure, instead of just letting the `malloc()` return `nullptr`, which is part of its specification. I'll just skip the test in debug and re-verify that it works on other modes without issues.

**Comment by psarna** [comment]
v2:
 - tried to make the test work with the address sanitizer in debug mode, but it's too much fuss for too little gain, so this test's execution is simply skipped in debug; release and dev works as expected
 
Tests: unit(debug, dev, release)

**Comment by avikivity** [comment]
Actually, getting the leak sanitizer to say there are no leaks would have been nice.

**Comment by psarna** [comment]
> Actually, getting the leak sanitizer to say there are no leaks would have been nice.

I can take the sometimes-failing allocator I used for manual verification for another spin in debug mode and check if it runs smoothly. It has the advantage that `::malloc` actually always succeeds and the address sanitizer would not abort, but at the same time rapidjson::Malloc() throws.

**Comment by nyh** [comment]
> Actually, getting the leak sanitizer to say there are no leaks would have been nice.

This is a good point.

There is one ugly thing you can do to counteract the ugly thing that ASAN did: My idea is to have in your new throwing allocator code, an ifdef for debug mode - and in debug mode, if the allocation is larger than some limit (we have Seastar's memory size, for example!) you can return nullptr immediately. At least this approach won't require any Seastar changes (and definitely no ASAN changes).

**Comment by psarna** [comment]
Actually, I'm half-sure that I ran these manual tests in debug mode indeed. But since I'm not 100% sure, I'll rerun the experiment.

**Comment by nyh** [comment]
> Actually, I'm half-sure that I ran these manual tests in debug mode indeed. But since I'm not 100% sure, I'll rerun the experiment.

In any case, it will be good to also have an automated test that runs every time, in addition to those test which you ran manually. It's not worth spending a day of hacking to get it to work, but maybe something as trivial as what I said above (a #ifdef for the debug case in your new allocator) can solve the testing problem.

**Comment by psarna** [comment]
@nyh that's a good idea. I see that the series got requeued, so it can be added as a follow-up. Meanwhile, I reran the manual tests in debug mode with ycsb workloads and the sanitizers had no complaints - both in malloc and realloc cases.

**Comment by avikivity** [comment]
Backported to 4.4, 4.5.

**Pull request merged**
