### PR TITLE
configure.py: don't delete build.ninja when rebuild is interrupted.

### LINKED ISSUE #4706: Interrupting "ninja" can cause build.ninja to disappear
Sometimes running "ninja" will cause `configure.py` to be rerun.

If you quickly kill it with control-C, you can end up with configure.py deleting your old `build.ninja` file but not yet creating a new one. So if you try to run "ninja" again, it will fail (and force you to manually rerun configure.py). This is annoying, and even more so for people who had a bunch of parameters for configure.py and now need to rerun it with all those parameters.

The safest option is for configure.py to atomically create build.ninja. For example, it can write to a temporary file and then rename it. 
Another, simpler, option is to trap signals like SIGINT et al. in configure.py, so it cannot be interrupted in the middle without an explicit (and hopefully deliberate) SIGKILL.

### PR DESCRIPTION
**Pull request by nyh**
In commit 9cc9facbea886ea224ffcba9a89d3dd36162d70d, I fixed issue #4706.
That issue about what happens when interrupting a rebuild of build.ninja
(which happens automatically when you run "ninja" after configure.py
changed). We don't want to leave behind a half-built build.ninja,
or leave it deleted.

The solution in that commit was for configure.py to build a temporary file
(build.ninja.tmp), and only as the very last step rename it build.ninja.

Unfortunately, since that time, we added more last steps after what
used to be that very last step :-(

If this new code running after the rename takes a noticable amount of
time, and if the user is unlucky enough to interrupt it during that
time, ninja will see a modified output file (build.ninja) and a failed
rule, and will delete the output file!

So the solution is to move the rename back to being the very last step
of configure.py. There is still a theoretical chance of interrupting
configure.py between the rename and Python's exit, but this chance is
now practically zero (and also, there is no chance for configure.py to
fail on an error at that point).

Fixes #4706 (again)

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

### CODE REVIEW

**Comment by cmm** [comment]
I wonder if it could be simpler (more disciplined and/or future-proof, anyway) to split configure.py into two scripts, where the inner one blissfully builds a temporary output and is only required to return a non-zero status if anything failed, and the outer one (probably better written in shell and kept Very Short) takes care of all this annoying, err, transaction management.

But perhaps a sternly-written comment to Please Keep This Part Last is enough by itself, so not insisting.

**Comment by nyh** [comment]
> I wonder if it could be simpler (more disciplined and/or future-proof, anyway) to split configure.py into two scripts, where the inner one blissfully builds a temporary output and is only required to return a non-zero status if anything failed, and the outer one (probably better written in shell and kept Very Short) takes care of all this annoying, err, transaction management.

Yes, I think I noted somewhere (maybe on the mailing list) a different approach I could have used: I could add an option to configure.py to write a different filename, not "ninja.build". Then what the ninja build code would do (don't even need a second script!) is to run "configure.py --out ninja.build.tmp" and then as a second step rename ninja.build.tmp to ninja.build. Then, if the first step fails, ninja will automatically remove *its* output - ninja.build.tmp - and not ninja.build.

If you think that would be better, I'll produce such a patch. I'm starting to think maybe indeed that would be better.
I also won't have to make that apology which I made in the commit message, that "There is still a theoretical chance of interrupting configure.py between the rename and Python's exit, but this chance is now practically zero".

**Comment by cmm** [comment]
> I could add an option to configure.py to write a different filename, not "ninja.build". Then what the ninja build code would do (don't even need a second script!) is to run "configure.py --out ninja.build.tmp" and then as a second step rename ninja.build.tmp to ninja.build.

That's even better indeed.

(Which also reminds me that I should separate compdb into its own explicit build target, just for people who need it.  Would make the automatic post-rebase configure.py invocations a lot faster)

**Comment by nyh** [comment]
I'm closing this PR and will create a new PR with the different solution mentioned in the previous comment.

**Pull request closed without merging**
