### PR TITLE
compaction: Clarify weight deregistration comment.

### PR DESCRIPTION
**Pull request by mikolajsieluzycki**
Removed the part ", as compactions aren't super frequent".

### CODE REVIEW

**Review by raphaelsc — APPROVED** [review]
LGTM

**Comment by raphaelsc** [comment]
```
[Test Result](https://jenkins.scylladb.com/job/releng/job/Scylla-CI/816/testReport/) (1 failure / +1)
[boost.view_complex_test.dev.test_shadowing_row_marker](https://jenkins.scylladb.com/job/releng/job/Scylla-CI/816/testReport/junit/boost.view_complex_test/dev/test_shadowing_row_marker/)
```

this indicates preexisting flakiness. @bhalevy do you know if it's a known problem?

**Comment by bhalevy** [comment]
I'm not familiar with this failure. Let's search it and if it's new open an issue and gather what we can from the CI run.  Hopefully it's reproducible with the same random seed.

**Comment by denesb** [comment]
On a related note, we have a lot of unrelated CI failures lately.

**Comment by bhalevy** [comment]
> On a related note, we have a lot of unrelated CI failures lately.

We tried to address that with 5bd2e0ccce128d726c4737a996d793666c54f6d1 and 5129280f45358962f61a411bd1cf2e73d5c542fe. But in any case, CI makes random failures more visible.  They might have been just buried in failed Jenkins jobs that we didn't care enough to analyse.

**Pull request closed without merging**
