### PR TITLE
Simplify scylla_util.py

### PR DESCRIPTION
**Pull request by syuu1228**
scylla_util.py becomes large, some code are unused, some code are only for specific script.
Drop unnecessary things, move non-common functions to caller script, make scylla_util.py simple.

### CODE REVIEW

**Comment by avikivity** [comment]
You have a bunch of unrelated commits there since you based on next instead of master.

**Comment by syuu1228** [comment]
@avikivity Rebased with latest next

**Comment by avikivity** [comment]
@syuu1228 now it contains an unrelated patch. Rebase on master and drop unrelated commits.

**Comment by syuu1228** [comment]
@avikivity Rebased.

**Comment by avikivity** [comment]
It still has "test/redis: make redis tests runnable from test.py …".

**Comment by syuu1228** [comment]
@avikivity Oops sorry, fixed.

**Comment by avikivity** [comment]
And now it has conflicts which I can't easily resolve. Please rebase.

**Comment by syuu1228** [comment]
@avikivity Rebased.

**Comment by syuu1228** [comment]
Rebased with latest next.

**Pull request merged**
