### PR TITLE
scylla-docker: fix default data_directories in scyllasetup.py

### PR DESCRIPTION
**Pull request by amoskong**
Use default data_file_directories if it's not assigned in scylla.yaml

Docker test of scylla master failed, this PR fixed that.
https://jenkins.scylladb.com/job/scylla-master/job/docker-test/label=muninn/82/console

Test: built a new image, and tested locally

/CC @penberg

### CODE REVIEW

**Comment by bhalevy** [comment]
lgtm, just change target branch to next

**Comment by bhalevy** [comment]
Also, it helps also to add "Fixes #5398" in the pr description so github connects them

**Comment by amoskong** [comment]
> Also, it helps also to add "Fixes #5398" in the pr description so github connects them

There is a 'Fixes #5298' in commitlog, is that enough?

**Comment by amoskong** [comment]
> lgtm, just change target branch to next

fixed, thanks

**Pull request merged**
