### PR TITLE
Move CQL transport code to cql3/transport

### PR DESCRIPTION
**Pull request by penberg**
The Scylla server supports multiple transport protocols. Let's move the CQL one under cql3 directory.

### CODE REVIEW

**Review by psarna — APPROVED** [review]
Looks good, I got bored after inspecting the fifth `s:transport:cql/transport` change, so I hope that the compiler already caught all the possible errors :)

**Comment by penberg** [comment]
@psarna I was counting on you to check them... (Yes, `ninja dist` passed with this.)

**Comment by psarna** [comment]
> @psarna I was counting on you to check them... (Yes, `ninja dist` passed with this.)

I officially ack the first five of them:
Reviewed-by: Piotr Sarna < sarna@scylladb.com >

**Review by nyh — APPROVED** [review]
Look reasonable to me. I'm curious what was the motivation - to clean up one item from the home directory, which now remains with "only" 250 more source files, header files and subdirectories? :-)

The only downside I see to such cleanups is that backports involving these files get more complicated.

**Comment by penberg** [comment]
@nyh I would indeed like to see some more structure in the source tree, and fewer entries at the top-level. It's an uphill battle for sure, but better start from somewhere.

**Comment by avikivity** [comment]
Well, cql can also be used from thrift. I like to think of transport and cql as separate layers, although that's not completely true.

**Comment by penberg** [comment]
@avikivity We have three components: C* query language (CQL), CQL wire protocol, and Thrift wire protocol. The main purpose of this pull request is to differentiate the CQL front-end from the Alternator and Redis front-ends. One solution is to introduce a top-level `cassandra` directory, similar to `alternator` and `redis` and move `transport`, `cql3`, and `thrift` directories there.

**Comment by avikivity** [comment]
There's also another option, do nothing.

**Comment by penberg** [comment]
@avikivity I don't think that is an option. The `transport` name is now meaningless with the introduction of `alternator` and `redis`. We could rename it to `cql3-transport` or something like that, of course.

**Comment by denesb** [comment]
> @nyh I would indeed like to see some more structure in the source tree, and fewer entries at the top-level. It's an uphill battle for sure, but better start from somewhere.

I agree, and I think if we intend to adopt modules we'll be forced to introduce some structure anyway.

**Comment by penberg** [comment]
@avikivity Ping, please let me know how to proceed with this pull request.

**Comment by nyh** [comment]
> @avikivity Ping, please let me know how to proceed with this pull request.

There is now a conflict, so you'll need to rebase.

What bothered me personally (and why I didn't rush to just commit it immediately) is that it wasn't not clear if this rename is part of grand plan to organize the source code, and if it is, whether this plan is going in the right direction or the wrong direction. The thing is, moving files around complicates various routine tasks like "git blame" or backporting, so we should avoid moving things back and forth if we can help it - and try to come up with more long-term movement plans. E.g., does it make sense to move "transport" (the so-called 'native' transport, i.e., CQL protocol) to cql3 now, but not move "thrift"? Will moving "thrift" later as well maybe cause us to move both directories to a new place, again?
Maybe it's better to just rename "transport" to "cql-protocol" (or something like that), still in the top-level directory?

**Comment by penberg** [comment]
@avikivity wanted the `cql3` (query language) module to be separate from transport layer so I am closing this pull request in favor of a new proposal: https://github.com/scylladb/scylla/pull/8266

**Pull request closed without merging**
