### PR TITLE
database.cc: Export current schema version as metrics

### PR DESCRIPTION
**Pull request by amnonh**
It is useful to be able to monitor the schema version per-node.
From the monitoring perspective, what is important is that all node
would have the same schema version.

This patch report the UUID as gauges. The UUID id reported as two gauges
one for the LSB and one for the MSB

The reported metrics loook like:

scylla_database_schema_version{shard="0",type="gauge",uuid="LSB"} -7498393077721644032.000000
scylla_database_schema_version{shard="0",type="gauge",uuid="MSB"} 6462017092514037760.000000

Fixes: #4796

Signed-off-by: Amnon Heiman <amnon@scylladb.com>

### CODE REVIEW

**Comment by avikivity** [comment]
Maybe a better way is schema{version="$version"} = 1.

**Comment by amnonh** [comment]
you cannot use labels, it will keep on changing all the time.

the idea is to identify a situation that one of the nodes has a different version than the others.

**Comment by amnonh** [comment]
@avikivity see my last comment, I prefer not to abuse the labels by continuously creating and deleting metrics.

If we want to have the full information
I can use 4 gauges instead of 2, so each unit64 will be represented by 2 doubles, will that be acceptable by you?

**Comment by avikivity** [comment]
No, it's terrible, let's look for antoher solution.

**Comment by avikivity** [comment]
I don't see a better solution than using labels. It's also recommended here: https://www.robustperception.io/exposing-the-software-version-to-prometheus.

Yes it create lots of series, but we already expose tens of thousands. Exposing one per version isn't so terrible, we don't expect more than a few versions per day.

**Comment by amnonh** [comment]
Exposing the software version as a metric is a legit solution and we are using it, but that change less than the number of restarts.

Anyone that would start creating lots of changes would add junk to the Prometheus server.

There's already a counter that changes each time a schema changed, so we get some notifications on it.

I'm against keep changing the metrics name (by changing the labels). we can close the PR and wait until will have a logger integration.

**Comment by avikivity** [comment]
Closing as suggested.

**Comment by avikivity** [comment]
I did see people export random info as labels.

**Pull request closed without merging**
