### PR TITLE
Migration to Scylla Repo Phase 1: Move existing docs to dev-docs directory

### PR DESCRIPTION
**Pull request by lauranovich**
This PR will create the structure needed to move the existing documentation into a new directory dev-docs creating room for the Scylla Docs which are currently in the scylla-docs repo.

### CODE REVIEW

**Comment by nyh** [comment]
I don't like this direction, and would ask that we hold some open discussion about this and hear from more maintainers and of course Avi before we start applying such patches.
It's already frustrating finding documents Scylla's source repository. What was once `docs/protocols.md` is now `docs/design-notes/protocols.md` and after your patch, `docs/dev-docs/design-notes/protocols.md`. All these subdirectories are unhelpful, unintuitive, and already today I can never remember if something is supposed to be a "design-notes" or "guides" or somewhere else.

If you want to "make room for scylla-docs", just create a subdirectory scylla-docs - or perhaps better - "website" (since this is stuff that will appear on the website, right?). You don't need to move everything else already in docs/. I don't understand why you want to move them.

**Comment by tzach** [comment]
Thanks @nyh 
Many month ago I sent an "RFC: moving Scylla Docs to in tree (in phases)", I will copy the relevant section below with some updates:

Open question (for Phase 2)
Where to place current "Scylla Dev site" docs once we move user-facing docs from docs.scylladb.com to scylla repo. Alternatives can be:
1. generate two sites (from the same repo). e.g. dev.docs.scylladb.com and scylla.docs.scylladb.com 
  - first with the content of scylla.docs.scylladb.com  
  - second with the relevant parts from docs.scylladb.com
  - pros:
     - No need to change anything in the current doc tree (maybe just the DNS name)
  - cons:
     - Make build more complex, as each site need to be build independently (maybe with one Sphinx project!)
     - Many updates apply to both
    
2. generate one site, and place dev doc under /docs/dev/ directory
  - pros:
    - simpler build
  - cons:
    - update design doc locations

This PR implement the second.

**Comment by tzach** [comment]
In addition, the current dev doc site [scylla.docs.scylladb.com](https://scylla.docs.scylladb.com/master/index.html) is still missing per release doc. I suggest to fix this before adding more complexity and choosing one of the options above

**Comment by nyh** [comment]
> Thanks @nyh
> Many month ago I sent an "RFC: moving Scylla Docs to in tree (in phases)"

Did anyone ever review this RFC and said they were happy with all these moves?

I am having a very hard time to understand why it was a good idea to move the file `docs/protocols.md` (just a random example) to `docs/dev-docs/design-notes/protocols.md`. I scratch my head every time I need to find a file in docs/ now.

> 
>     1. generate one site, and place dev doc under /docs/dev/ directory
> 
> 
>     * pros:
>       
>       * simpler build
> 
>     * cons:
>       
>       * update design doc locations
> 
> 
> This PR implement the second.

Maybe it does make some sense to have a split of docs/dev - for developers, and docs/user - for users. Or docs/guides (for user-facing guides) vs docs/design-notes (for people who care about internal design). Or some other split. But I let's consider the entire directory structure, and not move things randomly deeper and deeper into the hierarchy.

One possibility is to create the new "dev" directory as you suggested, but move everything in docs/ today into it, without a second division into "guides" vs "design notes" which I never understood. If you truely think that something is a "guide" that end-users will like to see, you can move it out of the dev/ subirectory into the user subdirectory.

I want the end-result to be convenient for developers - who we want to read those documents every day and also **write** them - not just for the script that runs Sphynx.

**Comment by lauranovich** [comment]
closing - taking it back to the drawing board

**Pull request closed without merging**
