### PR TITLE
IDL: support generating boilerplate code for RPC verbs

### PR DESCRIPTION
**Pull request by ManManson**
Introduce new syntax in IDL compiler to allow generating
registration/sending code for RPC verbs:

```
        verb [[attr1, attr2...] my_verb (args...) -> return_type;
```

`my_verb` RPC verb declaration corresponds to the
`netw::messaging_verb::MY_VERB` enumeration value to identify the
new RPC verb.

For a given `idl_module.idl.hh` file, a registrator class named
`idl_module_rpc_verbs` will be created if there are any RPC verbs
registered within the IDL module file.

These are the methods being created for each RPC verb:

```
        static void register_my_verb(netw::messaging_service* ms, std::function<return_type(args...)>&&);
        static future<> unregister_my_verb(netw::messaging_service* ms);
        static future<> send_my_verb(netw::messaging_service* ms, netw::msg_addr id, args...);
```

Each method accepts a pointer to an instance of `messaging_service`
object, which contains the underlying seastar RPC protocol
implementation, that is used to register verbs and pass messages.

There is also a method to unregister all verbs at once:

```
        static future<> unregister(netw::messaging_service* ms);
```

The following attributes are supported when declaring an RPC verb
in the IDL:
* `[[with_client_info]]` - the handler will contain a const reference to
  an `rpc::client_info` as the first argument.
* `[[with_timeout]]` - an additional `time_point` parameter is supplied
  to the handler function and `send*` method uses `send_message_*_timeout`
  variant of internal function to actually send the message.
* `[[one_way]]` - the handler function is annotated by
  `future<rpc::no_wait_type>` return type to designate that a client
  doesn't need to wait for an answer.

The `-> return_type` clause is optional for two-way messages. If omitted,
the return type is set to be `future<>`.
For one-way verbs, the use of return clause is prohibited and the
signature of `send*` function always returns `future<>`.

No existing code is affected.

Ref: #1456

### CODE REVIEW

**Comment by amnonh** [comment]
verb support is a long request @gleb-cloudius would be happy. 
Do you realy need it to be using pointers?

Can you give some example of the idl and the generated code?

**Comment by ManManson** [comment]
Pushed some fixes, changelog v2:
* Fix occasionally broken `RpcVerb` ctor missing `with_timeout` and `one_way` args (probably forgot to commit some code and lost updates)
* Support empty parameter lists for verbs.

**Comment by ManManson** [comment]
Changelog v3:
* Fixes for empty parameter lists (in `dist.impl.hh`)

**Comment by ManManson** [comment]
> verb support is a long request @gleb-cloudius would be happy.
> Do you realy need it to be using pointers?
Yes, you are right. Plain references can be used instead.

> 
> Can you give some example of the idl and the generated code?
Sure. I did not yet commit any testing code, maybe as a follow-up or in a later version.

Right now here's the ad-hoc example, demonstrating the generated code for various scenarios.

idl file:
```c++
// verb_test.idl.hh

// two-way message with timeout
verb [[with_timeout]] raft_send_snapshot (raft::group_id, raft::server_id, raft::server_id, raft::install_snapshot) -> raft::snapshot_reply;

// one-way message with timeout
verb [[with_timeout, one_way]] raft_append_entries (raft::group_id, raft::server_id, raft::server_id, raft::append_request);

// two-way message without arguments
verb schema_check () -> utils::UUID;
```
Generated `verb_test.dist.hh`:
```c++

/*
 * Copyright 2016-present ScyllaDB
 */

/*
 * This file is part of Scylla.
 *
 * Scylla is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Scylla is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Scylla.  If not, see <http://www.gnu.org/licenses/>.
 */


 /*
  * This is an auto-generated code, do not modify directly.
  */
#pragma once
 

 /*
  * The generate code should be included in a header file after
  * The object definition
  */
    
#include "serializer.hh"

namespace ser {

// RPC verbs defined in the 'verb_test' module

struct verb_test_rpc_verbs {
    static void register_raft_send_snapshot(netw::messaging_service* ms, std::function<future<raft::snapshot_reply> (const rpc::client_info&, rpc::opt_time_point, raft::group_id, raft::server_id, raft::server_id, raft::install_snapshot)>&&);
    static future<> unregister_raft_send_snapshot(netw::messaging_service* ms);
    static future<raft::snapshot_reply> send_raft_send_snapshot(netw::messaging_service* ms, netw::msg_addr id, netw::messaging_service::clock_type::time_point timeout, raft::group_id, raft::server_id, raft::server_id, raft::install_snapshot);

    static void register_raft_append_entries(netw::messaging_service* ms, std::function<future<rpc::no_wait_type> (const rpc::client_info&, rpc::opt_time_point, raft::group_id, raft::server_id, raft::server_id, raft::append_request)>&&);
    static future<> unregister_raft_append_entries(netw::messaging_service* ms);
    static future<> send_raft_append_entries(netw::messaging_service* ms, netw::msg_addr id, netw::messaging_service::clock_type::time_point timeout, raft::group_id, raft::server_id, raft::server_id, raft::append_request);

    static void register_schema_check(netw::messaging_service* ms, std::function<future<utils::UUID> (const rpc::client_info&)>&&);
    static future<> unregister_schema_check(netw::messaging_service* ms);
    static future<utils::UUID> send_schema_check(netw::messaging_service* ms, netw::msg_addr id);

    static future<> unregister(netw::messaging_service* ms);
};

} // ser
```

Generated `verb_test.dist.impl.hh`:
```c++

/*
 * Copyright 2016-present ScyllaDB
 */

/*
 * This file is part of Scylla.
 *
 * Scylla is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Scylla is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Scylla.  If not, see <http://www.gnu.org/licenses/>.
 */


 /*
  * This is an auto-generated code, do not modify directly.
  */
#pragma once
 
namespace ser {

// RPC verbs defined in the 'verb_test' module

void verb_test_rpc_verbs::register_raft_send_snapshot(netw::messaging_service* ms, std::function<future<raft::snapshot_reply> (const rpc::client_info&rpc::opt_time_point,, raft::group_id, raft::server_id, raft::server_id, raft::install_snapshot)>&& f) {
    register_handler(ms, netw::messaging_verb::RAFT_SEND_SNAPSHOT, std::move(f));
}

future<> verb_test_rpc_verbs::unregister_raft_send_snapshot(netw::messaging_service* ms) {
    return ms->unregister_handler(netw::messaging_verb::RAFT_SEND_SNAPSHOT);
}

future<raft::snapshot_reply> verb_test_rpc_verbs::send_raft_send_snapshot(netw::messaging_service* ms, netw::msg_addr id, netw::messaging_service::clock_type::time_point timeout, raft::group_id _1, raft::server_id _2, raft::server_id _3, raft::install_snapshot _4) {
    return send_message_timeout<future<raft::snapshot_reply>>(ms, netw::messaging_verb::RAFT_SEND_SNAPSHOT, id, timeout, std::move(_1), std::move(_2), std::move(_3), std::move(_4));
}

void verb_test_rpc_verbs::register_raft_append_entries(netw::messaging_service* ms, std::function<future<rpc::no_wait_type> (const rpc::client_info&rpc::opt_time_point,, raft::group_id, raft::server_id, raft::server_id, raft::append_request)>&& f) {
    register_handler(ms, netw::messaging_verb::RAFT_APPEND_ENTRIES, std::move(f));
}

future<> verb_test_rpc_verbs::unregister_raft_append_entries(netw::messaging_service* ms) {
    return ms->unregister_handler(netw::messaging_verb::RAFT_APPEND_ENTRIES);
}

future<> verb_test_rpc_verbs::send_raft_append_entries(netw::messaging_service* ms, netw::msg_addr id, netw::messaging_service::clock_type::time_point timeout, raft::group_id _1, raft::server_id _2, raft::server_id _3, raft::append_request _4) {
    return send_message_oneway_timeout<future<>>(ms, netw::messaging_verb::RAFT_APPEND_ENTRIES, id, timeout, std::move(_1), std::move(_2), std::move(_3), std::move(_4));
}

void verb_test_rpc_verbs::register_schema_check(netw::messaging_service* ms, std::function<future<utils::UUID> (const rpc::client_info&)>&& f) {
    register_handler(ms, netw::messaging_verb::SCHEMA_CHECK, std::move(f));
}

future<> verb_test_rpc_verbs::unregister_schema_check(netw::messaging_service* ms) {
    return ms->unregister_handler(netw::messaging_verb::SCHEMA_CHECK);
}

future<utils::UUID> verb_test_rpc_verbs::send_schema_check(netw::messaging_service* ms, netw::msg_addr id) {
    return send_message<future<utils::UUID>>(ms, netw::messaging_verb::SCHEMA_CHECK, id);
}

future<> verb_test_rpc_verbs::unregister(netw::messaging_service* ms) {
    return when_all_succeed(unregister_raft_send_snapshot(ms), unregister_raft_append_entries(ms), unregister_schema_check(ms)).discard_result();
}

} // ser
```

**Comment by ManManson** [comment]
One important thing that is missing right now is that it's not possible to provide names for parameters. For that reason it's also using auto-generated `_1`, `_2` etc. placeholder names in the implementation code. I'll fix that in the next version.

**Comment by avikivity** [comment]
Nice! I have ideas for improvements in registration/unregistration, but I think we should first merge something that is similar to existing practice, then improve it.

**Comment by avikivity** [comment]
@gleb-cloudius please review

**Comment by gleb-cloudius** [comment]
Looks great. Couple of generic comments. client_info is not mandatory (just like time_point), so we can make it an attribute as well. Second - arg list can be extensible. We need to mark fields that are added later and idl compiler should receive them as rpc::optional<>.

**Comment by avikivity** [comment]
Maybe [[optional]] arg.

**Comment by gleb-cloudius** [comment]
> Maybe [[optional]] arg.

In t current idl we have [[version x.y.x]] which have an advantage of documenting when the idl was changed.

**Comment by ManManson** [comment]
On Wed, Sep 22, 2021 at 2:46 PM Gleb Natapov ***@***.***>
wrote:

> Looks great. Couple of generic comments. client_info is not mandatory
> (just like time_point), so we can make it an attribute as well. Second -
> arg list can be extensible. We need to mark fields that are added later and
> idl compiler should receive them as rpc::optional<>.
>
Ok, sounds good. I will implement this in v2 along with some things I
mentioned before.

**Comment by ManManson** [comment]
Changelog v4:
* Arguments can have a name, it will be used instead of an auto-generated placeholder names like `_1`, `_2` etc.
* Arguments can be annotated with `[[version id]]` attribute, making it to appear as `rpc::optional<>` in the handler function signature.
* `[[with_client_info]]` rpc verb attribute, that adds a `rpc::client_info` argument to the handler function signature
* Refactoring, docstrings, IDL.md fixes
* Some more fixes regarding compilation of generated code

**Comment by gleb-cloudius** [comment]
Can you please provide an example of generated code for the latest version?

**Comment by ManManson** [comment]
> Can you please provide an example of generated code for the latest version?

@gleb-cloudius  Sure. Consider the following `verb_test.idl.hh` IDL file:

```
// verb_test.idl.hh

// message with client info, argument names and optional arguments
verb [[with_client_info]] test (std::string arg1, int, std::string arg3 [[version 1.0]]);

// empty message without client info
verb test_without_cinfo ();
```

Generated `verb_test.dist.hh`:
```c++

/*
 * Copyright 2016-present ScyllaDB
 */

/*
 * This file is part of Scylla.
 *
 * Scylla is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Scylla is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Scylla.  If not, see <http://www.gnu.org/licenses/>.
 */


 /*
  * This is an auto-generated code, do not modify directly.
  */
#pragma once
 

 /*
  * The generate code should be included in a header file after
  * The object definition
  */
    
#include "serializer.hh"

namespace ser {

// RPC verbs defined in the 'verb_test' module

struct verb_test_rpc_verbs {
    static void register_test(netw::messaging_service* ms,
        std::function<future<> (const rpc::client_info& info, std::string arg1, int, rpc::optional<std::string> arg3)>&&);
    static future<> unregister_test(netw::messaging_service* ms);
    static future<> send_test(netw::messaging_service* ms, netw::msg_addr id, std::string arg1, int, std::string arg3);

    static void register_test_without_cinfo(netw::messaging_service* ms,
        std::function<future<> ()>&&);
    static future<> unregister_test_without_cinfo(netw::messaging_service* ms);
    static future<> send_test_without_cinfo(netw::messaging_service* ms, netw::msg_addr id);

    static future<> unregister(netw::messaging_service* ms);
};

} // ser

```

Generated `verb_test.dist.impl.hh`:
```c++

/*
 * Copyright 2016-present ScyllaDB
 */

/*
 * This file is part of Scylla.
 *
 * Scylla is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Scylla is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Scylla.  If not, see <http://www.gnu.org/licenses/>.
 */


 /*
  * This is an auto-generated code, do not modify directly.
  */
#pragma once
 
namespace ser {

// RPC verbs defined in the 'verb_test' module

void verb_test_rpc_verbs::register_test(netw::messaging_service* ms,
        std::function<future<> (const rpc::client_info& info, std::string arg1, int, rpc::optional<std::string> arg3)>&& f) {
    register_handler(ms, netw::messaging_verb::TEST, std::move(f));
}

future<> verb_test_rpc_verbs::unregister_test(netw::messaging_service* ms) {
    return ms->unregister_handler(netw::messaging_verb::TEST);
}

future<> verb_test_rpc_verbs::send_test(netw::messaging_service* ms, netw::msg_addr id, std::string arg1, int _2, std::string arg3) {
    return send_message<future<>>(ms, netw::messaging_verb::TEST, id, std::move(arg1), std::move(_2), std::move(arg3));
}

void verb_test_rpc_verbs::register_test_without_cinfo(netw::messaging_service* ms,
        std::function<future<> ()>&& f) {
    register_handler(ms, netw::messaging_verb::TEST_WITHOUT_CINFO, std::move(f));
}

future<> verb_test_rpc_verbs::unregister_test_without_cinfo(netw::messaging_service* ms) {
    return ms->unregister_handler(netw::messaging_verb::TEST_WITHOUT_CINFO);
}

future<> verb_test_rpc_verbs::send_test_without_cinfo(netw::messaging_service* ms, netw::msg_addr id) {
    return send_message<future<>>(ms, netw::messaging_verb::TEST_WITHOUT_CINFO, id);
}

future<> verb_test_rpc_verbs::unregister(netw::messaging_service* ms) {
    return when_all_succeed(unregister_test(ms), unregister_test_without_cinfo(ms)).discard_result();
}

} // ser

```

**Review by gleb-cloudius — APPROVED** [review]

**Comment by ManManson** [comment]
@avikivity Please review.

**Comment by ManManson** [comment]
@avikivity @amnonh  Review ping

**Comment by ManManson** [comment]
Cc @tgrabiec

**Comment by avikivity** [comment]
> > Can you please provide an example of generated code for the latest version?
> 
> @gleb-cloudius Sure. Consider the following `verb_test.idl.hh` IDL file:
> 
> ```
> // verb_test.idl.hh
> 
> // message with client info, argument names and optional arguments
> verb [[with_client_info]] test (std::string arg1, int, std::string arg3 [[version 1.0]]);
> ```

We may want to require rpc::optional<> here, in addition to [[version 1.0]]. The reason is so we can support adding new parameters with defaults, without the overhead of rpc::optional.

e.g.

```
verb test1 (std::string arg1, int, std::string arg3 [[version 1.0]]);
verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]);
```

I'm not advocating for defaults now, just future-proof the language by not assuming rpc::optional.

**Comment by gleb-cloudius** [comment]
> > > Can you please provide an example of generated code for the latest version?
> > 
> > 
> > @gleb-cloudius Sure. Consider the following `verb_test.idl.hh` IDL file:
> > ```
> > // verb_test.idl.hh
> > 
> > // message with client info, argument names and optional arguments
> > verb [[with_client_info]] test (std::string arg1, int, std::string arg3 [[version 1.0]]);
> > ```
> 
> We may want to require rpc::optional<> here, in addition to [[version 1.0]]. The reason is so we can support adding new parameters with defaults, without the overhead of rpc::optional.
> 
> e.g.
> 
> ```
> verb test1 (std::string arg1, int, std::string arg3 [[version 1.0]]);
> verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]);
> ```
> 
> I'm not advocating for defaults now, just future-proof the language by not assuming rpc::optional.

This is not something RPC layer supports.

**Comment by avikivity** [comment]
> > > > Can you please provide an example of generated code for the latest version?
> > > 
> > > 
> > > @gleb-cloudius Sure. Consider the following `verb_test.idl.hh` IDL file:
> > > ```
> > > // verb_test.idl.hh
> > > 
> > > // message with client info, argument names and optional arguments
> > > verb [[with_client_info]] test (std::string arg1, int, std::string arg3 [[version 1.0]]);
> > > ```
> > 
> > 
> > We may want to require rpc::optional<> here, in addition to [[version 1.0]]. The reason is so we can support adding new parameters with defaults, without the overhead of rpc::optional.
> > e.g.
> > ```
> > verb test1 (std::string arg1, int, std::string arg3 [[version 1.0]]);
> > verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not advocating for defaults now, just future-proof the language by not assuming rpc::optional.
> 
> This is not something RPC layer supports.

It's not. I'm proposing to make room for it.

**Comment by ManManson** [comment]
> > > Can you please provide an example of generated code for the latest version?
> > 
> > 
> > @gleb-cloudius Sure. Consider the following `verb_test.idl.hh` IDL file:
> > ```
> > // verb_test.idl.hh
> > 
> > // message with client info, argument names and optional arguments
> > verb [[with_client_info]] test (std::string arg1, int, std::string arg3 [[version 1.0]]);
> > ```
> 
> We may want to require rpc::optional<> here, in addition to [[version 1.0]]. The reason is so we can support adding new parameters with defaults, without the overhead of rpc::optional.
> 
> e.g.
> 
> ```
> verb test1 (std::string arg1, int, std::string arg3 [[version 1.0]]);
> verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]);
> ```
> 
> I'm not advocating for defaults now, just future-proof the language by not assuming rpc::optional.
Do you mean to add an explicit `[[optional]]` in order to produce an `rpc::optional<>` argument?

Can you elaborate how it would work exactly? More specifically, what does it mean wrt. RPC message format (e.g. having an `optional<>` argument vs. non-optional with default value)? What RPC capabilities that you are talking about with Gleb are missing?

As far as I understand, you are talking about having the ability to not serialize an empty optional into an RPC message and let the client figure this out and substitute the default, if the argument is not there?

**Comment by avikivity** [comment]
Ugh, I mistyped my example. Should be explicit:

```
verb test1 (std::string arg1, int, rpc::optional<std::string> arg3 [[version 1.0]]); // supported today
verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]); // not supported by idl compiler, may add support in the future
```

The idl compiler should verify that optional arguments (with version tag) have rpc::optional wrapper and otherwise leave them alone.

**Comment by avikivity** [comment]
In terms of the future rpc support for default arguments, it should work similarly to current rpc::optional:

1. if the message is not truncated at the point where the argument is expected, deserialize it and proceed to the next argument
2. if the message is truncated, supply the default value (std::nullopt for rpc::optional, and the user-provided default for default aguments)

To be super clear, I'm not asking to implement default arguments. Just to require and enforce rpc::optional, so we have room to add default arguments.

**Comment by avikivity** [comment]
Closed by mistake reopening.

**Comment by gleb-cloudius** [comment]
> Ugh, I mistyped my example. Should be explicit:
> 
> ```
> verb test1 (std::string arg1, int, rpc::optional<std::string> arg3 [[version 1.0]]); // supported today
> verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]); // not supported by idl compiler, may add support in the future
> ```
> 
> The idl compiler should verify that optional arguments (with version tag) have rpc::optional wrapper and otherwise leave them alone.

Your first example was OK. You do no need explicit optional. Non optional can be figured by having `= something`.

**Comment by ManManson** [comment]
> > Ugh, I mistyped my example. Should be explicit:
> > 
> > ```
> > verb test1 (std::string arg1, int, rpc::optional<std::string> arg3 [[version 1.0]]); // supported today
> > verb test2 (std::string arg1, int, int arg3 = 0 [[version 2.0]]); // not supported by idl compiler, may add support in the future
> > ```
> > 
> > The idl compiler should verify that optional arguments (with version tag) have rpc::optional wrapper and otherwise leave them alone.
> 
> Your first example was OK. You do no need explicit optional. Non optional can be figured by having `= something`.

Exactly. Looking at `= value` part and `version` attribute, we already can conclude whether we need an `rpc::optional` or not. There shouldn't be any changes to existing IDL syntax if we are to add default rpc arguments.

**Comment by avikivity** [comment]
Ok. I prefer explicitness, but I agree that the [[version]] tag also conveys the same information.

**Comment by ManManson** [comment]
> Ok. I prefer explicitness, but I agree that the [[version]] tag also conveys the same information.

I think we can support both options by having idl compiler detect if the argument is already wrapped into optional or not.

In the former case, don't do anything, in the latter add an optional wrapper.

I can do it in a follow up.

**Comment by avikivity** [comment]
No need, everyone will pick the less-typing option.

**Pull request merged**
