### PR TITLE
test.py: add cluster and new approval tests

### PR DESCRIPTION
**Pull request by kostja**
test.py: add cluster and new approval tests

The purpose of this series is to introduce infrastructure
for managed scylla processes into test.py,
switch some existing suites to use test.py managed processes
and introduce cluster tests.

All of this is expected to make possible to test Raft topology
changes and schema changes using an easy to use and fast tool
such as test.py. In general this will allow testing Scylla clusters
from within the development test harness.

Branch URL: dev/test.py.v3

Changes in v3:
* type annotations
* more aggressive use of pathlib
* drop alternator suite
* switch approval tests to Python

Changes in v2:
* cluster tests
* short license headers
* dropped move of run.py
* dropped use of taskset, not useful in cluster/pooled
  environment, --overprovisioned is on anyway
* cleaned up scylla server options
* removed the switch for alternator tests
* style fixes
* use async http request and cql connect to check that the server is up
* use more pathlib

### CODE REVIEW

**Comment by tgrabiec** [comment]
@kostja PR description is missing.

**Comment by kostja** [comment]
* Tomasz Grabiec ***@***.***> [22/04/15 19:26]:
> @kostja PR description is missing. 

What is it? Where can I read about what it should contain?

there is a series on the mailing list with acover letter.

I made a PR to run dtests (I assume it will happen automatically?)

-- 
Konstantin Osipov, Moscow, Russia

**Comment by tgrabiec** [comment]
> What is it? Where can I read about what it should contain?

It's what's in the top-most comment. It will end up in the merge commit description when merged.

It should contain what a covering letter contains (what changed and why).

> 
> there is a series on the mailing list with acover letter.
> 
> I made a PR to run dtests (I assume it will happen automatically?)

If you intend the PR to be reviewed or merged, it should still contain the covering letter. If neither, this should be mentioned so that people are not puzzled. Do you intend this PR to be only for triggering CI?

**Comment by kostja** [comment]
* Tomasz Grabiec ***@***.***> [22/04/16 11:15]:
> If you intend the PR to be reviewed or merged, it should still
> contain the covering letter. If neither, this should be
> mentioned so that people are not puzzled. Do you intend this PR
> to be only for triggering CI?  

I don't have an opinion on how you should merge these patches.

I can add a cover letter if you wish to merge the PR, not the
series sent on the list. I prefer getting the review comments over
email, however.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by avikivity** [comment]
What is a Test.py.v3?

**Pull request closed without merging**
