### PR TITLE
Update seastar submodule

### LINKED ISSUE #10592: coredump when calling describe_ring and a node is being shut down
Test details
Scylla Version: 5.1.dev0
Manager Version: http://downloads.scylladb.com/manager/relocatable/unstable/branch-3.0/2022-05-14T21:57:57Z/scylla-manager_3.0-dev-0.20220514.8f367a97ae4.linux_x86_64.tar.gz
Build Id: #112
Jenkins job link: https://jenkins.scylladb.com/job/manager-3.0/job/manager-dtest/112/artifact/scylla-dtest/logs/1652569008375_manager_repair_tests.py%3A%3ATestScyllaMgmtRepair%3A%3Atest_intensity_and_parallel/

issue description:
There is coredump when repair is running and a node is being shut down.
This issue is produced during manager dtest test teardown (might happen during various maanger tests).
This particular example happens during manager_repair_tests.TestScyllaMgmtRepair.test_intensity_and_parallel, there is a coredump on node 2:
```
failed on teardown with "AssertionError: Critical errors found: [('node2', ['scylla: ./seastar/include/seastar/core/iostream.hh:387: seastar::output_stream<char>::~output_stream() [CharType = char]: Assertion `!_end && !_zc_bufs && "Was this stream properly closed?"\' failed.', 'Aborting on shard 0.'])]
Other errors: []"
```
The test creates a repair task on an empty data set and without waiting for it to finish terminates all scylla nodes at once:
```
{"L":"INFO","T":"2022-05-14T22:56:45.228Z","N":"repair","M":"Repair of the following keyspaces will be skipped because not all the tokens are present in the specified DCs","keyspaces":"system_auth","_trace_id":"euFr97BXShyoDG3n1CBy6Q"}
{"L":"INFO","T":"2022-05-14T22:56:45.228Z","N":"scheduler","M":"PutTask","task":"repair/5c221ec4-7595-4230-8c15-781135fb162e","schedule":{"cron":"","window":null,"timezone":"Etc/UTC","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":3,"retry_wait":"10m"},"properties":{"intensity":2,"keyspace":["keyspace1"],"parallel":1},"create":true,"_trace_id":"euFr97BXShyoDG3n1CBy6Q"}
{"L":"INFO","T":"2022-05-14T22:56:45.230Z","N":"scheduler.c758757a","M":"Schedule","task":"repair/5c221ec4-7595-4230-8c15-781135fb162e","in":"0s","begin":"2022-05-14T22:56:45.230Z","retry":0,"_trace_id":"euFr97BXShyoDG3n1CBy6Q"}
{"L":"INFO","T":"2022-05-14T22:56:45.230Z","N":"http","M":"POST /api/v1/cluster/c758757a-5d49-4c1e-99db-2ad7d9ee32d5/tasks","from":"127.0.0.1:48210","status":201,"bytes":0,"duration":"278ms","_trace_id":"euFr97BXShyoDG3n1CBy6Q"}
{"L":"INFO","T":"2022-05-14T22:56:45.231Z","N":"scheduler.c758757a","M":"Run started","task":"repair/5c221ec4-7595-4230-8c15-781135fb162e","retry":0,"_trace_id":"kXe696SjRPuf3H5YzCRntg"}
{"L":"INFO","T":"2022-05-14T22:56:45.347Z","N":"http","M":"GET /api/v1/cluster/c758757a-5d49-4c1e-99db-2ad7d9ee32d5/task/repair/5c221ec4-7595-4230-8c15-781135fb162e","from":"127.0.0.1:48240","status":200,"bytes":440,"duration":"6ms","_trace_id":"nKXSCFrfSrePL-OpUL_Cpw"}
{"L":"INFO","T":"2022-05-14T22:56:45.354Z","N":"http","M":"GET /api/v1/cluster/c758757a-5d49-4c1e-99db-2ad7d9ee32d5/task/repair/5c221ec4-7595-4230-8c15-781135fb162e/history?limit=10","from":"127.0.0.1:48240","status":200,"bytes":235,"duration":"6ms","_trace_id":"Y2UUvT3OQWKLRMudgv-r6w"}
{"L":"INFO","T":"2022-05-14T22:56:45.361Z","M":"Received signal","signal":"terminated","_trace_id":"JpAvW1mrQzaRG3ABBPD2aQ"}
{"L":"INFO","T":"2022-05-14T22:56:45.361Z","M":"Closing servers","timeout":"30s","_trace_id":"JpAvW1mrQzaRG3ABBPD2aQ"}
{"L":"INFO","T":"2022-05-14T22:56:45.363Z","M":"Closing server done","address":"127.0.59.1:5611","_trace_id":"JpAvW1mrQzaRG3ABBPD2aQ"}
{"L":"INFO","T":"2022-05-14T22:56:45.363Z","M":"Closing server done","address":"127.0.59.1:56091","_trace_id":"JpAvW1mrQzaRG3ABBPD2aQ"}
{"L":"INFO","T":"2022-05-14T22:56:45.363Z","M":"Closing server done","address":"127.0.59.1:5080","_trace_id":"JpAvW1mrQzaRG3ABBPD2aQ"}
```

This causes a coredump on one of the nodes:
```
INFO  2022-05-14 22:56:45,364 [shard 0] storage_service - Shutting down native transport server
scylla: ./seastar/include/seastar/core/iostream.hh:387: seastar::output_stream<char>::~output_stream() [CharType = char]: Assertion `!_end && !_zc_bufs && "Was this stream properly closed?"' failed.
Aborting on shard 0.
Backtrace:
  0x4d29408
  0x4d59e02
  0x7fa97488ca1f
  /jenkins/slave/workspace/manager-3.0/manager-dtest/scylla-dtest/tmp_dtest_run/.ccm/scylla-repository/unstable/master/2022-05-14T00_41_59Z/scylla/libreloc/libc.so.6+0x3d2a1
  /jenkins/slave/workspace/manager-3.0/manager-dtest/scylla-dtest/tmp_dtest_run/.ccm/scylla-repository/unstable/master/2022-05-14T00_41_59Z/scylla/libreloc/libc.so.6+0x268a3
  /jenkins/slave/workspace/manager-3.0/manager-dtest/scylla-dtest/tmp_dtest_run/.ccm/scylla-repository/unstable/master/2022-05-14T00_41_59Z/scylla/libreloc/libc.so.6+0x26788
  /jenkins/slave/workspace/manager-3.0/manager-dtest/scylla-dtest/tmp_dtest_run/.ccm/scylla-repository/unstable/master/2022-05-14T00_41_59Z/scylla/libreloc/libc.so.6+0x35a15
  0x3d2f31c
  0x4d3a374
  0x4d3b757
  0x4d3a9ac
  0x4ce1918
  0x4ce0df1
  0x105eeaf
  0x105c6da
  /jenkins/slave/workspace/manager-3.0/manager-dtest/scylla-dtest/tmp_dtest_run/.ccm/scylla-repository/unstable/master/2022-05-14T00_41_59Z/scylla/libreloc/libc.so.6+0x27b74
  0x105b66d
```

[1652569008375_manager_repair_tests.py__TestScyllaMgmtRepair__test_intensity_and_parallel.zip](https://github.com/scylladb/scylla/files/8707571/1652569008375_manager_repair_tests.py__TestScyllaMgmtRepair__test_intensity_and_parallel.zip)

### PR DESCRIPTION
**Pull request by nyh**
* seastar 96bb3a1b8...2be9677d6 (37):
  > Merge 'stream_range_as_array: always close output stream' from Benny Halevy

Fixes #10592

  > net/api: add "server_socket::is_listening()"
  > src/net/proxy: remove unused variable
  > coroutine: parallel_for_each: relax contraints
  > native-stack: do not use 0 as ip address if !_dhcp
  > coroutine: fix a typo in comment
  > std-coroutine: include for LLVM-14
  > tutorial: use non-variadic version of when_all_succeed()
  > scripts: Fix build.sh to use new --c++-standard config option
  > core/thread: initialize work::pr and work::th explicitly
  > util/log-impl: remove "const" qualifier in return type
  > map_reduce: remove redundant move() in return statement
  > util: mark unused parameter with [[maybe_unused]]
  > drop unused parameters
  > build: use "20" for the default CMAKE_CXX_STANDARD
  > build: make CMAKE_CXX_STANDARD a string
  > utils: log: don't crash on allocation failure while extending log buffer
  > tests: unix_domain_test: fix thread/future confusion in client_round()
  > compat: do not use std::source_location if it is broken
  > build: use CMAKE_CXX_STANDARD instead of Seastar_CXX_DIALECT
  > Merge 'Add hello-world demo from tutorial' from Pavel
  > rpc_tester: Put client/server sides into correct sched groups
  > reactor_backend: Use _r reference, not engine() method
  > future.hh: #include std-compat.hh for SEASTAR_COROUTINES_ENABLED
  > Merge "Add more CPU-hog facilities to RPC-tester" from Pavel E
  > Merge "io: Enlighten queued_request" from Pavel E
  > Correct swapped AIO detection/setup calls
  > sharded: De-duplicate map-reduce overloads
  > file: don't trample on xfs flags when setting xfs size hint
  > Merge "Per-class IO bandwidth limits" from Pavel E
  > Merge 'sstring: fix format and optimize the performance of sstring::find().' from Jianyong Chen
  > reactor_backend: Mark reactor_backend_aio::poll() private
  > scripts/build.sh: Mind if not running on a terminal
  > test, rpc: Don't work with large buffers
  > test, futures: Don't expect ready future to resolve immediately
  > source_location compatibility: Fix an unused private field error when treat warning as errors
  > file: Remove try-catch around noexcept calls

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]

**Comment by nyh** [comment]
Unfortunately, CI shows successful build - but a large number of failed tests after this Seastar update.

For example. the Alternator test crashed Scylla with
```
[2022-05-29T14:33:56.447Z] test_system_tables.py F
[2022-05-29T14:33:56.447Z] ! _pytest.outcomes.Exit: Scylla appears to have crashed in test test_system_tables.py::test_fetch_from_system_tables !
...
[2022-05-29T14:33:56.448Z] Scylla version 5.1.dev-0.20220529.3b6dc96fbe41 with build-id d1a7246325d59e30de12ae07b03e5b23f5d502ee starting ...
[2022-05-29T14:33:56.508Z] =================================================================
[2022-05-29T14:33:56.508Z] ==560==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f8b58fed337 at pc 0x000013ce7738 bp 0x7ffc0a701290 sp 0x7ffc0a701288
[2022-05-29T14:33:56.508Z] READ of size 1 at 0x7f8b58fed337 thread T0
[2022-05-29T14:33:56.508Z]     #0 0x13ce7737  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13ce7737)
[2022-05-29T14:33:56.508Z]     #1 0x13ceb020  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13ceb020)
[2022-05-29T14:33:56.508Z]     #2 0x13d26cf2  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13d26cf2)
[2022-05-29T14:33:56.508Z]     #3 0x13d5d76c  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13d5d76c)
[2022-05-29T14:33:56.508Z]     #4 0x16caf614  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x16caf614)
[2022-05-29T14:33:56.508Z]     #5 0x16d6504d  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x16d6504d)
[2022-05-29T14:33:56.508Z]     #6 0x16d64d78  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x16d64d78)
[2022-05-29T14:33:56.508Z]     #7 0x1ae7916e  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x1ae7916e)
[2022-05-29T14:33:56.508Z]     #8 0x1ae7f7e6  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x1ae7f7e6)
[2022-05-29T14:33:56.508Z]     #9 0x1ae84452  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x1ae84452)
[2022-05-29T14:33:56.508Z]     #10 0x1ae81fc1  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x1ae81fc1)
[2022-05-29T14:33:56.508Z]     #11 0x1ac40501  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x1ac40501)
[2022-05-29T14:33:56.508Z]     #12 0x1ac3e065  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x1ac3e065)
[2022-05-29T14:33:56.508Z]     #13 0x13c20a4c  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13c20a4c)
[2022-05-29T14:33:56.508Z]     #14 0x140f9c96  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x140f9c96)
[2022-05-29T14:33:56.508Z]     #15 0x140f9bcb  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x140f9bcb)
[2022-05-29T14:33:56.508Z]     #16 0x140f9a35  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x140f9a35)
[2022-05-29T14:33:56.508Z]     #17 0x13cdfd5d  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13cdfd5d)
[2022-05-29T14:33:56.508Z]     #18 0x13c1f261  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13c1f261)
[2022-05-29T14:33:56.509Z]     #19 0x7f8b5e75ab74  (/lib64/libc.so.6+0x27b74)
[2022-05-29T14:33:56.509Z]     #20 0x13b3e1ed  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13b3e1ed)
[2022-05-29T14:33:56.509Z] 
[2022-05-29T14:33:56.509Z] Address 0x7f8b58fed337 is located in stack of thread T0 at offset 55 in frame
[2022-05-29T14:33:56.509Z]     #0 0x16d6328f  (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x16d6328f)
[2022-05-29T14:33:56.509Z] 
[2022-05-29T14:33:56.509Z]   This frame has 1 object(s):
[2022-05-29T14:33:56.509Z]     [32, 56) 'ref.tmp' (line 302) <== Memory access at offset 55 is inside this variable
[2022-05-29T14:33:56.509Z] HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
[2022-05-29T14:33:56.509Z]       (longjmp and C++ exceptions *are* supported)
[2022-05-29T14:33:56.509Z] SUMMARY: AddressSanitizer: stack-use-after-return (/jenkins/workspace/releng/Scylla-CI/scylla/build/debug/scylla+0x13ce7737) 
[2022-05-29T14:33:56.509Z] Shadow bytes around the buggy address:
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a10: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a20: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a30: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a40: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a50: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z] =>0x0ff1eb1f5a60: f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a70: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5a90: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5aa0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z]   0x0ff1eb1f5ab0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
[2022-05-29T14:33:56.509Z] Shadow byte legend (one shadow byte represents 8 application bytes):
[2022-05-29T14:33:56.509Z]   Addressable:           00
[2022-05-29T14:33:56.509Z]   Partially addressable: 01 02 03 04 05 06 07 
[2022-05-29T14:33:56.509Z]   Heap left redzone:       fa
[2022-05-29T14:33:56.509Z]   Freed heap region:       fd
[2022-05-29T14:33:56.509Z]   Stack left redzone:      f1
[2022-05-29T14:33:56.509Z]   Stack mid redzone:       f2
[2022-05-29T14:33:56.509Z]   Stack right redzone:     f3
[2022-05-29T14:33:56.509Z]   Stack after return:      f5
[2022-05-29T14:33:56.509Z]   Stack use after scope:   f8
[2022-05-29T14:33:56.509Z]   Global redzone:          f9
[2022-05-29T14:33:56.509Z]   Global init order:       f6
[2022-05-29T14:33:56.509Z]   Poisoned by user:        f7
[2022-05-29T14:33:56.509Z]   Container overflow:      fc
[2022-05-29T14:33:56.509Z]   Array cookie:            ac
[2022-05-29T14:33:56.509Z]   Intra object redzone:    bb
[2022-05-29T14:33:56.509Z]   ASan internal:           fe
[2022-05-29T14:33:56.509Z]   Left alloca redzone:     ca
[2022-05-29T14:33:56.509Z]   Right alloca redzone:    cb
[2022-05-29T14:33:56.509Z]   Shadow gap:              cc
[2022-05-29T14:33:56.509Z] ==560==ABORTING
[2022-05-29T14:33:56.509Z] Aborting on shard 0.
[2022-05-29T14:33:56.509Z] Backtrace:
[2022-05-29T14:33:56.509Z]   0x13b8a110
[2022-05-29T14:33:56.509Z]   0x1aff618d
[2022-05-29T14:33:56.509Z]   0x1aff5d8c
[2022-05-29T14:33:56.509Z]   0x1ae5a474
[2022-05-29T14:33:56.509Z]   0x1ae85fce
[2022-05-29T14:33:56.509Z]   0x1af672bc
[2022-05-29T14:33:56.509Z]   0x1af6750d
[2022-05-29T14:33:56.509Z]   0x1af6733a
[2022-05-29T14:33:56.509Z]   0x7f8b5f318a1f
[2022-05-29T14:33:56.509Z]   /lib64/libc.so.6+0x3d2a1
[2022-05-29T14:33:56.509Z]   /lib64/libc.so.6+0x268a3
[2022-05-29T14:33:56.509Z]   0x13c0583e
[2022-05-29T14:33:56.509Z]   0x13c0376b
[2022-05-29T14:33:56.509Z]   0x13beadcf
[2022-05-29T14:33:56.509Z]   0x13bea855
[2022-05-29T14:33:56.509Z]   0x13beb36b
[2022-05-29T14:33:56.509Z]   0x13ce7737
[2022-05-29T14:33:56.509Z]   0x13ceb020
[2022-05-29T14:33:56.509Z]   0x13d26cf2
[2022-05-29T14:33:56.509Z]   0x13d5d76c
[2022-05-29T14:33:56.509Z]   0x16caf614
[2022-05-29T14:33:56.509Z]   0x16d6504d
[2022-05-29T14:33:56.509Z]   0x16d64d78
[2022-05-29T14:33:56.509Z]   0x1ae7916e
[2022-05-29T14:33:56.509Z]   0x1ae7f7e6
[2022-05-29T14:33:56.509Z]   0x1ae84452
[2022-05-29T14:33:56.509Z]   0x1ae81fc1
[2022-05-29T14:33:56.509Z]   0x1ac40501
[2022-05-29T14:33:56.509Z]   0x1ac3e065
[2022-05-29T14:33:56.509Z]   0x13c20a4c
[2022-05-29T14:33:56.509Z]   0x140f9c96
[2022-05-29T14:33:56.509Z]   0x140f9bcb
[2022-05-29T14:33:56.509Z]   0x140f9a35
[2022-05-29T14:33:56.509Z]   0x13cdfd5d
[2022-05-29T14:33:56.509Z]   0x13c1f261
[2022-05-29T14:33:56.509Z]   /lib64/libc.so.6+0x27b74
[2022-05-29T14:33:56.509Z]   0x13b3e1ed
```
As well as a large number of wasm tests, and a cql-pytest test test/cql-pytest/test_virtual_tables.py whose data is in files:
```
Test pytest --host=127.213.200.3 -o junit_family=xunit2 --junit-xml=/jenkins/workspace/releng/Scylla-CI/scylla/testlog/debug/xml/test_virtual_tables.2049.xunit.xml test/cql-pytest/test_virtual_tables.py failed, check the log at /jenkins/workspace/releng/Scylla-CI/scylla/testlog/debug/test_virtual_tables.2049.log
```
We need to decode these backtrace and to figure out which Seastar change broke Scylla :-(

**Comment by bhalevy** [comment]
> Unfortunately, CI shows successful build - but a large number of failed tests after this Seastar update.

Cc @benipeled

**Comment by nyh** [comment]
It's a real bug, not a CI issue. I'll look into it.

**Comment by benipeled** [comment]
> Unfortunately, CI shows successful build - but a large number of failed tests after this Seastar update.

@nyh ? did you see a wrong status report?
As far as I can see the build - ninja... - was indeed completed successfully. The failure was on the unit-tests stage - ./test.py - which was indeed reported by the CI.

**Comment by nyh** [comment]
That's what I said - the build passed, but tests failed. It's a Scylla/Seastar bug, not a CI problem. I'm on it.

**Comment by bhalevy** [comment]
Sorry, I misunderstood you.
I thought you meant there's false positive where CI failed but was showing as successful.

**Review by bhalevy — APPROVED** [review]

**Comment by avikivity** [comment]
rebased/merged as e85bd37c6e. Didn't want to create a merge commit for a seastar submodule update.

**Pull request closed without merging**
