### PR TITLE
commitlog: Add explicit track var for "wasted space" to avoid double …

### PR DESCRIPTION
**Pull request by elcallio**
…counting

Refs #9331

In segment::close() we add space to managers "wasted" counter. In destructor,
if we can cleanly delete/recycle the file we remove it. However, if we never
went through close (shutdown - ok, exception in batch_cycle - not ok), we can
end up subtracting numbers that were never added in the first place.
Just keep track of the bytes added in a var.

### CODE REVIEW

**Comment by avikivity** [comment]
Need issue reference. Is there any indication that exceptions were involved where we saw bad behavior?

**Comment by eliransin** [comment]
> Need issue reference. Is there any indication that exceptions were involved where we saw bad behavior?
@avikivity yes, #9331. I had an experiment with this. This is a timeout exception and it is all in this issue.

@elcallio - I have only one concern, if the segment is not clean() while destroyed we will have some waste bytes stuck
forever in the counter.
Can it even happen? If so I think we might want to subtract the `_waste` unconditionally.

**Comment by elcallio** [comment]
> 
> 
> Need issue reference. Is there any indication that exceptions were involved where we saw bad behavior?

Updated with ref.

**Comment by elcallio** [comment]
> 
> 
> > Need issue reference. Is there any indication that exceptions were involved where we saw bad behavior?
> 
> @avikivity yes, #9331. I had an experiment with this. This is a timeout exception and it is all in this issue.
> 
> @elcallio - I have only one concern, if the segment is not clean() while destroyed we will have some waste bytes stuck forever in the counter. Can it even happen? If so I think we might want to subtract the `_waste` unconditionally.

If a segment gets destroyed and it is not clean, it means we've exhausted all IO paths, and released the last reference to it. This would typically be in CL shutdown. If so, the only option that exists is leaving it on  disk for replay on next start. Which is what happens. 
In this case, we are at EOL for the CL so the counter left as it is is both correct and non-consequential.

**Comment by avikivity** [comment]
Ah, so a timeout in table::apply() goes through commilog and causes this problem? That sounds plausible. But please add it to the changelog.

**Comment by avikivity** [comment]
And, was this tested in #9331 scenario?

**Comment by elcallio** [comment]
> 
> 
> > Need issue reference. Is there any indication that exceptions were involved where we saw bad behavior?
> 
> @avikivity yes, #9331. I had an experiment with this. This is a timeout exception and it is all in this issue.
> 
> @elcallio - I have only one concern, if the segment is not clean() while destroyed we will have some waste bytes stuck forever in the counter. Can it even happen? If so I think we might want to subtract the `_waste` unconditionally.

If a segment gets destroyed and it is not clean, it means we've exhausted all IO paths, and released the last reference to it. This would typically be in CL shutdown. If so, the only option that exists is leaving it on  disk for replay on next start. Which is what happens. 
In this case, we are at EOL for the CL so the counter left as it is is both correct and non-consequential. 

> 
> 
> Ah, so a timeout in table::apply() goes through commilog and causes this problem? That sounds plausible. But please add it to the changelog.

Expanded log.

**Pull request closed without merging**
