### PR TITLE
tree-wide: comments on deprecated functions to access global variables

### PR DESCRIPTION
**Pull request by kbr-**

### CODE REVIEW

**Comment by kbr-** [comment]
I may have forgot about some services that are used globally, please remind in such case

**Review by tgrabiec — APPROVED** [review]

**Comment by kbr-** [comment]
forgot about one place, fixed

**Comment by xemul** [comment]
My list:
````
service::get_storage_proxy()
service::get_local_storage_proxy()
service::get_local_shared_storage_proxy()
service::get_storage_service()
service::get_local_storage_service()
tracing::tracing_instance()
tracing::get_local_tracing_instance()
gms::get_gossiper()
gms::get_local_gossiper()
locator::snitch_instance()
locator::get_local_snitch_ptr()
db::qctx // it's not a function, there's a whole bunch of them around it
service::get_local_priority_manager()
service::get_local_..._priority()
streaming::get_stream_manager()
streaming::get_local_stream_manager()
streaming::stream_session::... // there's a set of static pointers on other sharded service
db::get_batchlog_manager()
db::get_local_batchlog_manager()
::repair_tracker()
::repair_meta::repair_meta_map()
````

**Comment by avikivity** [comment]
@kbr- even better are patches to remove those functions and their users

**Pull request closed without merging**
