### PR TITLE
move cloud related code from scylla repository to scylla-machine-image

### PR DESCRIPTION
**Pull request by syuu1228**
Currently, cloud related code have cross-dependencies between
scylla and scylla-machine-image.
It is not good way to implement, and single change can break both
package.

To resolve the issue, we need to move all cloud related code to
scylla-machine-image, and remove them from scylla repository.

Change list:
 - move cloud part of scylla_util.py to scylla-machine-image
 - move cloud part of scylla_io_setup to scylla-machine-image
 - move scylla_ec2_check to scylla-machine-image
 - move cloud part of scylla_bootparam_setup to scylla-machine-image

---- 

This is scylla part of the PR, please merge scylla-machine-image part first.

### CODE REVIEW

**Comment by syuu1228** [comment]
scylla-machine-image part is at https://github.com/scylladb/scylla-machine-image/pull/289

**Comment by syuu1228** [comment]
Note that I keep --ami option on scylla_io_setup for compatibility, but it no longer needed.
And I also keep --ami option and also scylla_bootparam_setup itself, but the script no longer needed, since it only modify boot parameter on AMI (it does `if not args.ami: sys.exit(0)`).
On scylla_ec2_check, I just removed the script because it is only needed for login prompt of AMI.

**Comment by syuu1228** [comment]
@avikivity @yaronkaikov ping

**Comment by syuu1228** [comment]
@avikivity ping, we already merged scylla-machine-image part, we need merge this too.

**Comment by tarzanek** [comment]
@avikivity @syuu1228 
this effectively breaks custom installs of Scylla on plain OS in cloud
are we sure this is a good way to go?

**Comment by tarzanek** [comment]
OR should scylla machine image repo be applied on top of plain install of Scylla?
(this will complicate most of ansible installs)

**Comment by tarzanek** [comment]
at least let's get this documented well, if we really want to stop doing it for direct (without AMI) Scylla deployments

honestly, I think this will be a one more road block that will hinder perf tests of scylla on plain/custom cloud images and eventually loosing users/customers due to missing tuning

**Comment by vladzcloudius** [comment]
@avikivity How would a customer (Ansible Role included) know since which version and on which platform this needs to be installed? Why not to install it always by making `scylla` package depend on it?
And how the customer know how to run the scripts in that `machine-image` package?

As of today this code is triggered from `scylla_setup` meaning that there was a clear dependency between the version of `scylla_setup` which is part of a `scylla` package and the code that handles cloud specific pre-calculated values. If we decided to take this code out into a separate package then we need to create a clear `Depends` entry in the `scylla` package definition. Do we have it?

**Pull request closed without merging**
