### PR TITLE
cql3: do_execute_base_query: fix null deref when clustering key is unavailable

### LINKED ISSUE #5794: Segfault in indexed_table_select_statement during secondary_indexes_test.TestSecondaryIndexes.test_truncate_base
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/57/artifact/logs-debug.2/1581370901459_secondary_indexes_test.TestSecondaryIndexes.test_truncate_base/node2.log
Scylla version 43097854a5e043492cacd19cfced047f35a99a6b
```
INFO  2020-02-10 21:41:39,355 [shard 0] rpc - client 127.0.88.3:7000: fail to connect: Connection refused
AddressSanitizer:DEADLYSIGNAL
=================================================================
==10505==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000c16cc28 bp 0x7ffddc7244a0 sp 0x7ffddc724490 T0)
==10505==The signal is caused by a READ memory access.
==10505==Hint: address points to the zero page.
    #0 0xc16cc27 in blob_storage::ref_type::operator blob_storage*() const utils/managed_bytes.hh:40
    #1 0xc867dbb in managed_bytes::read_linearize() const utils/managed_bytes.hh:144
    #2 0xc869813 in managed_bytes::data() const utils/managed_bytes.hh:400
    #3 0xcc2c0bf in managed_bytes::operator std::basic_string_view<signed char, std::char_traits<signed char> >() const utils/managed_bytes.hh:341
    #4 0xd1956c3 in compound_wrapper<clustering_key_prefix, clustering_key_prefix_view>::begin(schema const&) const keys.hh:322
    #5 0xe11d4be in compound_wrapper<clustering_key_prefix, clustering_key_prefix_view>::get_component(schema const&, unsigned long) const keys.hh:354
    #6 0xef6aced in generate_base_key_from_index_pk<partition_key> cql3/statements/select_statement.cc:441
    #7 0xef23656 in operator() cql3/statements/select_statement.cc:504
    #8 0xef8a675 in apply<cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::<lambda(auto:174&&)> [with auto:174 = cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::base_query_state&]::<lambda()>&> seastar/include/seastar/core/future.hh:1655
    #9 0xef6ce59 in repeat<cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::<lambda(auto:174&&)> [with auto:174 = cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::base_query_state&]::<lambda()> > seastar/include/seastar/core/future-util.hh:279
    #10 0xef25f00 in operator()<cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::base_query_state&> cql3/statements/select_statement.cc:520
    #11 0xef262dc in do_with<cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::base_query_state, cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, dht::partition_range_vector&&, service::query_state&, const cql3::query_options&, gc_clock::time_point, seastar::shared_ptr<const service::pager::paging_state>) const::<lambda(auto:174&&)> > seastar/include/seastar/core/do_with.hh:94
    #12 0xef27e47 in cql3::statements::indexed_table_select_statement::do_execute_base_query(service::storage_proxy&, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, service::query_state&, cql3::query_options const&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >, seastar::shared_ptr<service::pager::paging_state const>) const cql3/statements/select_statement.cc:495
    #13 0xef412bb in operator() cql3/statements/select_statement.cc:970
    #14 0xef95dde in apply seastar/include/seastar/core/apply.hh:36
    #15 0xef95feb in apply<cql3::statements::indexed_table_select_statement::do_execute(service::storage_proxy&, service::query_state&, const cql3::query_options&) const::<lambda(cql3::selection::result_set_builder&, std::unique_ptr<cql3::query_options>&)>::<lambda()>::<lambda(dht::partition_range_vector, seastar::shared_ptr<const service::pager::paging_state>)>&, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<const service::pager::paging_state>&&> seastar/include/seastar/core/apply.hh:44
    #16 0xef9612d in apply<cql3::statements::indexed_table_select_statement::do_execute(service::storage_proxy&, service::query_state&, const cql3::query_options&) const::<lambda(cql3::selection::result_set_builder&, std::unique_ptr<cql3::query_options>&)>::<lambda()>::<lambda(dht::partition_range_vector, seastar::shared_ptr<const service::pager::paging_state>)>&, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<const service::pager::paging_state>&&> seastar/include/seastar/core/future.hh:1645
    #17 0xef7e997 in operator() seastar/include/seastar/core/future.hh:1163
    #18 0xefa8389 in call seastar/include/seastar/util/noncopyable_function.hh:130
    #19 0xf09b4c4 in seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>::operator()(std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&) const seastar/include/seastar/util/noncopyable_function.hh:184
    #20 0xf06d99b in seastar::apply_helper<seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>, std::tuple<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >&&, std::integer_sequence<unsigned long, 0ul, 1ul> >::apply(seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>&&, std::tuple<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >&&) seastar/include/seastar/core/apply.hh:36
    #21 0xf06dadc in auto seastar::apply<seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >(seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>&&, std::tuple<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >&&) seastar/include/seastar/core/apply.hh:44
    #22 0xf06dc1d in seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::apply<seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >(seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>&&, std::tuple<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >&&) seastar/include/seastar/core/future.hh:1645
    #23 0xf028f52 in seastar::future<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >::then_impl<seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>, seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >(seastar::noncopyable_function<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > (std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >&&, seastar::shared_ptr<service::pager::paging_state const>&&)>&&)::{lambda()#1}::operator()() const::{lambda(seastar::future_state<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >&&)#1}::operator()(seastar::future_state<std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >, seastar::shared_ptr<service::pager::paging_state const> >) seastar/include/seastar/core/future.hh:1191
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

### PR DESCRIPTION
**Pull request by bhalevy**
This series fixes null pointer dereference seen in #5794

efd7efe41e cql3: generate_base_key_from_index_pk; support optional index_ck
7af1f9e26a cql3: do_execute_base_query: generate open-ended slice when clustering key is unavailable
7fe1a9ec4a cql3: do_execute_base_query: fixup indentation

Fixes #5794

Branches: 3.3

### CODE REVIEW

**Comment by bhalevy** [comment]
Test: unit(dev) secondary_indexes_test:TestSecondaryIndexes.test_truncate_base(debug)

**Comment by psarna** [comment]
Great, thanks, I'll verify locally and queue.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint ping backport

**Comment by avikivity** [comment]
Backported to 3.3.

**Pull request merged**
