### PR TITLE
Fix DPDK mode in prepare script

### PR DESCRIPTION
**Pull request by c3mb0**

### CODE REVIEW

**Comment by avikivity** [comment]
@c3mb0 the patch looks good, but this project requires a CLA. Please see https://www.scylladb.com/open-source/ ("Contributor Agreement" section)

**Comment by glommer** [comment]
hello @c3mb0 . Did you see Avi's comments above?

**Comment by c3mb0** [comment]
Submitted earlier today.

**Comment by glommer** [comment]
Thanks a lot!!

@avikivity please consider merging

**Comment by avikivity** [comment]
Merged in 86b80365024db408e8f0556797c0df46040991ae

**Pull request closed without merging**
