### PR TITLE
fix(ebs_disks): Fix aws_instance.ebs_disks method

### PR DESCRIPTION
**Pull request by aleksbykov**
aws_instance.ebs_disks() method should return ebs disk
instead of ephemeral

### CODE REVIEW

**Comment by avikivity** [comment]
Please use your @scylladb.com address in the author/commit git metadata.

**Comment by aleksbykov** [comment]
> Please use your @scylladb.com address in the author/commit git metadata.

Fixed.

**Review by bentsi — APPROVED** [review]

**Comment by avikivity** [comment]
Please use the normal style for scylla changelogs, not the dtest/sct style.

**Comment by avikivity** [comment]
Oh, I already committed this, where did it go?

**Comment by aleksbykov** [comment]
> Oh, I already committed this, where did it go?

@avikivity i think 4.3. may be 4.2. Not sure about enterprise, does it have this code

**Comment by avikivity** [comment]
@albertjosearaujo I don't remember the entire code base by heart

**Pull request closed without merging**
