### PR TITLE
github: remove CODEOWNERS

### PR DESCRIPTION
**Pull request by avikivity**
I suspect that the reason maintainers mark pull requests as "approved"
and then let them rot is that others maintainers are automatically
marked as reviewers. This means that everyone assumes that someone
else is reponsible, and nothing happens.

Remove CODEOWNERS so this doesn't happen.

### CODE REVIEW

**Comment by nyh** [comment]
I don't understand neither the problem, nor your solution.

I am an example of someone who once in a while "approve" a PR and then don't commit it myself. Why don't I commit it right after approving? Sometimes I just forget (I don't have a good process for tracking PRs that need my attention). Sometimes I feel that although I could review this patch, I'm not the best person to review and not sure - and wait for someone else to also review. Sometimes I remember how @gleb-cloudius was angry with me for reviewing and immediately committing a patch (your patch) in "his" area of the code, so I hesitate to review-and-immediately-commit.

In any case, I don't see what removing CODEOWNERS would improve. I think what it will really do is that fewer patches will be brought to my attention because I hear about them now that I'm listed as a "code owner" in quite a bit of areas, and these notifications will stop of CODEOWNERS is removed (I'll probably get the mail about the new PR, but it will drown in a sea of similar mails).

I think another option is to continue improving CODEOWNERS - and list more people there - instead of removing it.

**Comment by denesb** [comment]
> I am an example of someone who once in a while "approve" a PR and then don't commit it myself. Why don't I commit it right after approving? Sometimes I just forget (I don't have a good process for tracking PRs that need my attention). Sometimes I feel that although I could review this patch, I'm not the best person to review and not sure - and wait for someone else to also review.

I feel that these are the two most common reasons for me as well. The list of codeowners requested to review is not the intimidating factor here: I know who owns what code without github listing it for me anyway.

For me CODEOWNERS has no negative or positive impacts: I skim trough all patches and PRs anyway -- and decide on what to review based on what code I'm most familiar with/interested in. Although when there are a lot of emails piled up (happens more and more often) it does help that relevant review requests land in the "me" folder which I always give higher priority to.

**Comment by psarna** [comment]
For me, the CODEOWNERS  effect is slightly positive. It would be better if patch authors would always manually ask me for review in my areas of expertise, but in practice it never happens - so it's better if I at least get an automatic ping from github. It's sometimes a false positive, but very often I actually review and merge patches just because I got notified as an owner that they exist

**Comment by avikivity** [comment]
Ok, I withdraw the patch and abort my attempt at pop psychology.

**Comment by avikivity** [comment]
Should we do [this](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-scheduled-reminders-for-your-team) instead?

**Comment by denesb** [comment]
For me the biggest problem is keeping track of patches/PRs that I reviewed but I'm waiting for either another review or a response (potentially to another reviewer). Just because I considered merging the patch/PR I'm not going to automatically be CCd on those responses and I might simply forget the whole thing. Usually I track my TODO by leaving emails unread. But if I leave such emails unread I will keep going back to them thinking I have to review them.

All this is to say that I can see that your suggestion might help in my use-case.

**Pull request closed without merging**
