### PR TITLE
repair: Fix rx_hashes_nr metrics

### PR DESCRIPTION
**Pull request by asias**
In get_full_row_hashes_with_rpc_stream and
repair_get_row_diff_with_rpc_stream_process_op which were introduced in
the "Repair switch to rpc stream" series, rx_hashes_nr metrics are not
updated correctly.

Tests: repair_additional_test.py:RepairAdditionalTest.repair_almost_synced_3nodes_test

In the test we have 3 nodes and run repair on node3, we makes sure the
following metrics are correct.
```
assertEqual(node1_metrics['scylla_repair_tx_hashes_nr'] + node2_metrics['scylla_repair_tx_hashes_nr'],
   	    node3_metrics['scylla_repair_rx_hashes_nr'])
assertEqual(node1_metrics['scylla_repair_rx_hashes_nr'] + node2_metrics['scylla_repair_rx_hashes_nr'],
   	    node3_metrics['scylla_repair_tx_hashes_nr'])
assertEqual(node1_metrics['scylla_repair_tx_row_nr'] + node2_metrics['scylla_repair_tx_row_nr'],
   	    node3_metrics['scylla_repair_rx_row_nr'])
assertEqual(node1_metrics['scylla_repair_rx_row_nr'] + node2_metrics['scylla_repair_rx_row_nr'],
   	    node3_metrics['scylla_repair_tx_row_nr'])
assertEqual(node1_metrics['scylla_repair_tx_row_bytes'] + node2_metrics['scylla_repair_tx_row_bytes'],
   	    node3_metrics['scylla_repair_rx_row_bytes'])
assertEqual(node1_metrics['scylla_repair_rx_row_bytes'] + node2_metrics['scylla_repair_rx_row_bytes'],
            node3_metrics['scylla_repair_tx_row_bytes'])
```
Note: Since the rpc stream enabled repair is not included in any release yet. So no need to backport.

### CODE REVIEW

**Comment by asias** [comment]
@nyh @avikivity Ping.

**Comment by asias** [comment]
@nyh @avikivity Ping. This is needed by 3.2. The fix is trivial. Please consider merging it. Thanks.

**Comment by avikivity** [comment]
@asias please add an issue #.

**Comment by asias** [comment]
Added the issue number and pushed.

**Comment by avikivity** [comment]
Merged into master by accident; removed for master and added to next.

**Pull request merged**
