### PR TITLE
docs: fix invalid path in README.mds

### PR DESCRIPTION
**Pull request by Rjerk**
Signed-off-by: Liu Lan <liulan_yewu@cmss.chinamobile.com>

### CODE REVIEW

**Comment by tzach** [comment]
LGTM

**Comment by avikivity** [comment]
@nyh did you check that @Rjerk signed the CLA?

**Comment by avikivity** [comment]
I removed this commit since the CLA was not signed.

**Comment by Rjerk** [comment]
That's new. Maybe the CLA can be prompted and checked by scylladb-promoter. : )

**Comment by avikivity** [comment]
Queued again now that @Rjerk has signed the CLA.

**Pull request closed without merging**
