### PR TITLE
gracefully close scylladb on SIGINT and SIGTERM

### PR DESCRIPTION
**Pull request by bsphere**

### CODE REVIEW

**Comment by bsphere** [comment]
are you planning to merge this?

**Comment by tzach** [comment]
Hi @bsphere sorry for the late response.
We are not working with Pull Requests so this was ignored (for too long)
Please read https://github.com/scylladb/scylla/blob/master/CONTRIBUTING.md#contributing-code-to-scylla on how to contribute to the project.

**Comment by bsphere** [comment]
@tzach 404 on that license agreement link.
too much hassle for such a simple and basic fix. I'd be glad to see it being fixed..

**Comment by dorlaor** [comment]
Ouch. Thanks for reporting. We just did a major website change last night
and seems like the page didn't survive it.

**Comment by penberg** [comment]
@bsphere The CLA is up on the home page page. I'm closing this pull request but please do submit your changes to the development mailing list!

**Pull request closed without merging**
