### PR TITLE
cql: Remove support for null inside lists of IN values

### LINKED ISSUE #10579: cql: Remove support for null inside lists of IN values
Currently we support queries like:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4);
```
Nothing can be equal to null so this is equivalent to:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, 4);
```

Cassandra doesn't support it at all.
```cql
> SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")

> SELECT * FROM ks.tab WHERE p IN (1, 2, ?, 4) # ? is NULL
Error: DbError(Invalid, "Invalid null value in condition for column p")

> SELECT * FROM ks.tab WHERE p IN ? # ? is (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")
```
It makes little sense to send a null inside list of IN values and supporting it is a bit cumbersome.

Supporting it causes trouble because internally the values are represented as a list, not a tuple, and lists can't contain nulls.
Because of that code requires exceptions because in this single case there can be a null inside of a collection.

Changing this wouldn't require much work.
We would only need to remove `evaluate_IN_list` and modify [some tests](https://github.com/scylladb/scylla/blob/a2b9a17927d851b368d3ef8e869a295c8bd2e86b/test/boost/restrictions_test.cc#L660).

### PR DESCRIPTION
**Pull request by cvybhu**
Currently we support queries like:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4);
```
Nothing can be equal to null so this is equivalent to:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, 4);
```

Cassandra doesn't support it at all.
```cql
> SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")

> SELECT * FROM ks.tab WHERE p IN (1, 2, ?, 4) # ? is NULL
Error: DbError(Invalid, "Invalid null value in condition for column p")

> SELECT * FROM ks.tab WHERE p IN ? # ? is (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")
```
It makes little sense to send a null inside list of IN values and supporting it is a bit cumbersome.

Supporting it causes trouble because internally the values are represented as a list, not a tuple, and lists can't contain nulls.
Because of that code requires exceptions because in this single case there can be a null inside of a collection.

This PR starts treating a llist of IN values the same as any other list and as result nulls are forbidden inside them.

In case of a null the message is the same as any other collection:
```
null is not supported inside collections
```
I'm not entirely happy about it - someone could be confused if they received this message after a query that didn't involve any collections.
The problem with making a prettier error message is that once again we would have to give `evaluate` additional information that it's now evaluating a list of IN values. And we would end up back with `evaluate_IN_list`

I think we could consider adding some kind of generic context to evaluate. The context would contain the whole expression and a mark on the part that we are currently evaluating. Then in case of error we could use this context and use it to create more helpful error messages, e.g. point to the part of the expression where a problem occured. But that's outside of the scope of this PR.

Fixes #10579

### CODE REVIEW

**Comment by avikivity** [comment]
Agree about quality of error messages. We can improve it later, indeed by passing a context-type thing during prepare.

**Comment by avikivity** [comment]
@benipeled CI reports some tests pending, but last force-push was two days ago. What's going on?

**Comment by avikivity** [comment]
@cvybhu please fix your names in the commits, it shows up like this:

```
commit 326c89c1758617c650e055635dfa9b43451094bf (origin/pull/10620/head)
Author: cvybhu <jan.ciolek@scylladb.com>
Date:   Fri May 20 01:06:41 2022 +0200

```

**Comment by benipeled** [comment]
> @benipeled CI reports some tests pending, but last force-push was two days ago. What's going on?

The CI failed with spot termination and for some reason didn't re-trigger a new job. I see the pattern we're looking for `Cannot contact i` doesn't exist on the log, I'll check it.

I'm not going to manually submit a new CI since a change is required for this PR - once submitted, a new CI job will trigger

**Comment by cvybhu** [comment]
v2:
- Fixed name in commit description

**Comment by cvybhu** [comment]
v3:
- Fixed name in `Signed-off` part of commit description

**Pull request merged**
