### PR TITLE
database: apply_in_memory: run_when_memory_available under table::run_async

### LINKED ISSUE #8790: test view_builder_test is failing shutdown in debug mode  (closed gate)
At least for the last 5 builds, we have been seeing `view_builder_test` failing in debug mode. One of them is https://jenkins.scylladb.com/job/scylla-master/job/next/3588/consoleText, and the test fails like this:
```
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,245 [shard 0] view - Stopping view builder
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,246 [shard 1] view - Stopping view builder
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,250 [shard 0] gossip - My status = NORMAL
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,250 [shard 0] gossip - Announcing shutdown
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,256 [shard 0] gossip - Disable and wait for gossip loop started
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,257 [shard 0] gossip - Disable and wait for gossip loop finished
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,622 [shard 0] gossip - Gossip is now stopped
[2021-06-02T23:01:16.518Z] INFO  2021-06-03 01:44:41,630 [shard 0] compaction_manager - Asked to stop
[2021-06-02T23:01:16.519Z] INFO  2021-06-03 01:44:41,630 [shard 0] compaction_manager - Stopping 0 ongoing compactions
[2021-06-02T23:01:16.519Z] INFO  2021-06-03 01:44:41,631 [shard 1] compaction_manager - Asked to stop
[2021-06-02T23:01:16.519Z] INFO  2021-06-03 01:44:41,631 [shard 0] compaction_manager - Stopped
[2021-06-02T23:01:16.519Z] INFO  2021-06-03 01:44:41,631 [shard 1] compaction_manager - Stopping 0 ongoing compactions
[2021-06-02T23:01:16.519Z] INFO  2021-06-03 01:44:41,632 [shard 1] compaction_manager - Stopped
[2021-06-02T23:01:16.519Z] INFO  2021-06-03 01:44:42,486 [shard 1] view_update_generator - leaving 0 unstaged sstables unprocessed
[2021-06-02T23:01:16.519Z] ERROR 2021-06-03 01:44:42,512 [shard 0] table - Table async_gate is closed, at: 0x116446d0 0x17ed390c 0x17ed358d 0x17ed5ebf 0x17ed6e02 0x17142b8b 0x11bab578 0x11af261e 0x118c3345 0x118c3273 0x118c2ef7 0x1184cf93 0x1184cbae 0x1184eb7d 0x118240cf 0x11a0879a 0x11a0857d 0x11a084b3 0x11a0832f 0x119586d7 0x11a9b3a8 0x11a9ae38 0x119586d7 0x11958167 0x11957edd 0x11957e27 0x11957d43 0x11957333 0x119564b3 0x170276d8 0x17027511 0x17027261 0x1718bac0 0x171928c6 0x171974fb 0x1807dc6a 0x1807bd7c 0x18054186 0x180539d7 0x18053867 0x18053277 0x11d26c88 0x1750a2e7 /lib64/libpthread.so.0+0x93f8 /lib64/libc.so.6+0x101902
[2021-06-02T23:01:16.519Z]    --------
[2021-06-02T23:01:16.519Z]    seastar::lambda_task<seastar::execution_stage::flush()::$_5>
```

I suspect we have some sort of race closing a gate and using it, and because debug mode messes with the continuation order, maybe this race can end up the wrong way.
I guess this is a recent regression, because in the past this test wasn't failing.

CC @bhalevy

### PR DESCRIPTION
**Pull request by bhalevy**
Make sure to apply the mutation under the table's _async_gate.

Fixes #8790

Test: unit(dev), view_build_test(debug)
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by bhalevy** [comment]
Marked as draft until the unit tests pass

**Comment by bhalevy** [comment]
This patch should be applied before "table: do_apply: verify that _async_gate is open"

**Review by nyh — COMMENTED** [review]
I'm not familiar with cf.run_async() (is it new?) to understand **why** this patch needs to do what it does. What's the purpose of cf.run_async() and why is it needed here specifically?

**Comment by nyh** [comment]
> This patch should be applied before "table: do_apply: verify that _async_gate is open"

That patch is already applied... Shall I dequeue it?

**Comment by nyh** [comment]
> Marked as draft until the unit tests pass

Are you running the unit tests yourself?

**Comment by nyh** [comment]
> > This patch should be applied before "table: do_apply: verify that _async_gate is open"
> 
> That patch is already applied... Shall I dequeue it?

Or I can just reorder them manually. Please tell me when to commit this patch, and I'll do the reordering manually.

**Comment by bhalevy** [comment]
> > Marked as draft until the unit tests pass
> 
> Are you running the unit tests yourself?

@nyh, yes. I want to make sure they pass before committing the patch.
the debug test takes forever...

**Comment by bhalevy** [comment]
@nyh tests passed, feel free to queue in next (and reorder before the patch adding the async_gate assert)

**Comment by nyh** [comment]
Done. Pushed this patch, and rebased next so that this patch comes before the one that added the assertion. Let us pray that this git monkey-business worked ;-)

**Pull request closed without merging**
