### PR TITLE
tools: toolchain: support podman as a replacement to docker

### LINKED ISSUE #5332: dbuild hangs on Fedora 31 hosts
Running dbuild on Fedora 31 hosts hangs when the container exits. This looks like a manifestation of https://github.com/moby/moby/issues/36718.

### PR DESCRIPTION
**Pull request by avikivity**
Docker on Fedora 31 is flakey, and is not supported at all on RHEL 8. Podman is a drop-in replacement for docker; this series adds support for using podman in dbuild.

Apart from actually working on Fedora 31 hosts, podman is nicer in being more secure and not requiring a daemon.

Fixes #5332.

### CODE REVIEW

**Comment by espindola** [comment]
Tested on fedora 30.
LGTM

**Comment by espindola** [comment]
BTW, I still get some test failures, but given that I could not run configure.py before this is an improvement and the LGTM stands.

The test failure:

% ./tools/toolchain/dbuild ./build/dev/tests/memory_footprint -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0
...
ERROR 2019-11-22 09:35:56,684 [shard 0] seastar - Exiting on unhandled exception: std::filesystem::__cxx11::filesystem_error (error generic:13, filesystem error: cannot create directories: Permission denied [/tmp/scylla-34ec1d65-4bab-41ca-8b27-d5e3092acf91])

**Comment by avikivity** [comment]
@espindola I can't reproduce your error.
 - please try upgrading podman and associated packages to the latest versions
 - try disabling selinux (`setenforce 0`)

**Comment by espindola** [comment]
Testing again at ff7e78330c062253acee85c1005b49f1c29b3b53
$ ./tools/toolchain/dbuild  ./configure.py
$ ./tools/toolchain/dbuild  ninja build/dev/tests/memory_footprint
$ ./build/dev/tests/memory_footprint -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0

ERROR 2019-11-25 09:46:58,934 [shard 0] seastar - Exiting on unhandled exception: std::filesystem::__cxx11::filesystem_error (error generic:13, filesystem error: cannot create directories: Permission denied [/tmp/scylla-43f0efca-1600-4fb6-bdf3-687fcf7dfb98]

The podman docker is

Version     : 1.6.2
Release     : 2.fc30

Disabling selinux "fixes" the problem. Since this is fedora 30 I am not too worried, as there is always plain docker and everything works for you in fedora 31 ( I will test this now on my laptop and report, but a build on a laptop will take some time).

**Comment by avikivity** [comment]
You're probably the last person on Earth (other than Dan Walsh) to run with selinux enable.

Please see if you can minimize this (e.g. `podman run -v /tmp:/tmp --rm fedora:31 touch /tmp/xx`) and report to the containers/libpod repository.

**Comment by espindola** [comment]
I got the same error on fedora 31. I will try to reduce and report upstream.

**Comment by espindola** [comment]
btw, do we need the "real" /tmp? I am trying

-       -v /tmp:/tmp$z \
+       --tmpfs /tmp \

The above test passes with selinux enabled.

It also works with plain docker.

**Comment by avikivity** [comment]
This is due to a kernel bug, see b349e11aba33d0ddb52d34ddfb9319cfec87519b. The bug has likely been fixed since then, but we may need to update some jenkins workers.

**Comment by avikivity** [comment]
See also https://lore.kernel.org/linux-fsdevel/26f0d78e-99ca-2f1b-78b9-433088053a61@scylladb.com/T/#t for another kernel bug in this area.

**Comment by avikivity** [comment]
Mount /tmp can also help reduce the space requirement from the container, since the compilers spew large amounts of gunk into /tmp. Of course, it increases the space requirement on /tmp, but that's easier to guarantee.

**Comment by avikivity** [comment]
(and --tmpfs /tmp is risky due to that space requirement, since tmpfs is backed by limited RAM/swap)

**Comment by avikivity** [comment]
@scylladb/scylla-maint please consider for merging. While there are failures with selinux enabled, there is a workaround, and the fix is likely to be outside dbuild (and in podman/selinux/whatever).

**Comment by psarna** [comment]
Is the expected usage to first set `docker` as an alias for `podman` in your console?

**Comment by avikivity** [comment]
Fedora comes with a podman-docker package that makes /usr/bin/docker call podman.

For testing, I placed a tiny shell script in ~/bin/docker that similarly calls podman.

**Comment by psarna** [comment]
Ok, thanks. I went with manually editing `/usr/bin/docker` with a hack, but `podman-docker` is a better long term solution. Everything works fine on my machine (along with the memory footprint test), so I'm going to merge it.

**Comment by psarna** [comment]
Queued as d90dbd6ab0b760eefd2249954657f2c9b0416a42

**Comment by espindola** [comment]
I reported https://bugzilla.redhat.com/show_bug.cgi?id=1777018 to track the issue binding /tmp.

BTW, is --tmpfs with swap much worse than a bind mount of a real fs?

**Comment by avikivity** [comment]
> I reported https://bugzilla.redhat.com/show_bug.cgi?id=1777018 to track the issue binding /tmp.


Better to report it upstream. 

> 
> BTW, is --tmpfs with swap much worse than a bind mount of a real fs?

Yes

**Pull request merged**
