### PR TITLE
Simplify and explain from_varint_to_integer

### PR DESCRIPTION
**Pull request by espindola**
This is the second version of the patch series. The previous one was just the second patch, this one adds more tests an another patch to make it easier to test that the new code has the same behavior as  the old one.

### CODE REVIEW

**Comment by espindola** [comment]
ping.  @kostja Could you review this one?

**Comment by espindola** [comment]
ping 2. @tgrabiec maybe?

**Comment by espindola** [comment]
merge ping

**Comment by kostja** [comment]
@espindola pinging me on github is OK only as long as you're OK with a very late response.
Generally I prefer reviewing patches over email, just in case you would wish to solicit my review another time and make it easy for me to provide

**Comment by avikivity** [comment]
Queed as 9e990725d90502feac24075779ccbc426667fa5f

**Pull request merged**
