### PR TITLE
Commit Log: effectively disable strict threshold maintenance behavior

### PR DESCRIPTION
**Pull request by eliransin**
This commit effectively disables the commitlog behavior that is related
to strict threshold maintenance.
The first change is to stop accounting the wasted bytes (or file slack bytes)
as there is at least one bug in that area that puts the whole system out
of balance. The second, makes the segment flash behave as it behaved
before and try to flush all segments up to the active one instead of
evicting exactly the segments that will make the commit log go below the
disk usage threshold.
The changes makes the commitlog behave closer to the way it used to
behave before strict disk usage was introduced. This is meant to be
temporary and allow for gradual re-enabling of the code once the bugs or
the source of unpredictable behavior is found.

Refs scylladb/scylla#9331

### CODE REVIEW

**Comment by avikivity** [comment]
How was this tested?

**Comment by eliransin** [comment]
> How was this tested?

I used the reproducer from #9331 and a comparative test.
The accounting stuff I just found by sprinkling some asserts that we always subtract the amount we added and saw it is
not true. The other change helped to get good results on that scenario (closer to the behavior that was before it).
The graphs are there, 
starting at https://github.com/scylladb/scylla/issues/9331#issuecomment-958095100 and goes on for 3 or 4 comments below it.

**Comment by avikivity** [comment]
I don't know what to say. "There is suspicion" is not a inspiring confidence. Maybe you ran a test and got better results, but do we know that it won't regress other tests?

**Comment by eliransin** [comment]
We can't know this for sure, however, the change I made will make commitlog behave as it did before the recent changes were introduced (at least according to my understanding of the code which I rather new to).
If I am not making some novice mistake here, the worst thing that can happen is that we have undone an improvement. However, reading the code reviews I couldn't find any evidence that it is an improvement in the first place.
How about I will go the other way around? We found a regression and we have a reproduce.
The change to wasted bytes definitely is definitely one of the root causes to that regression. The second is only suspected to participate, I will do a run of the reproducer with only the first part of the "revert" and if there won't be an apparent regression I will remove it from this commit.

/cc @elcallio

**Comment by elcallio** [comment]
I would suggest #9598 instead.

**Comment by eliransin** [comment]
I will drop this in favor of @elcallio approach which is better IMO. (#9598)

**Pull request closed without merging**
