### PR TITLE
config: Do not enable repair based node operations by default

### PR DESCRIPTION
**Pull request by asias**
Give it some more time to mature. Use the old stream plan based node
operations by default.

Fixes: #6305
Backports: 4.0

### CODE REVIEW

**Comment by bhalevy** [comment]
LGTM, can you please run a byo test to make sure it doesn't break the gating dtests?
(You'll need to push it to a branch of yours in scylla-dev or seastar-dev)

**Comment by asias** [comment]
I can push a branch to scylla-dev.git asias/disable_repair_based_ops_by_default.
I need howto doc to run the byo test.

**Comment by bhalevy** [comment]
Started https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/967/

**Comment by slivne** [comment]
based on the BYO it looks good

there is a resharding test failure - but it seems unrelated to me - all the other gating passed.

@avikivity / @penberg / @tgrabiec please merge this.

We need this backported to 4.0 tomorrow (wednesday 29 April) as well so we can keep the timeline of 4.0 release.

**Pull request merged**
