### PR TITLE
cql3: Drop all uses_function methods

### PR DESCRIPTION
**Pull request by dekimir**
No one seems to call them except for other uses_function methods.

Tests: unit (dev)

Signed-off-by: Dejan Mircevski <dejan@scylladb.com>

### CODE REVIEW

**Comment by dekimir** [comment]
> Shouldn't drop_function statement check that a function is in use before dropping it? Maybe it's missing a check.

I can't tell where that check would go.  Let's ask @espindola. :)

**Comment by espindola** [comment]
Dejan Mircevski <notifications@github.com> writes:

>> Shouldn't drop_function statement check that a function is in use before dropping it? Maybe it's missing a check.
>
> I can't tell where that check would go.  Let's ask @espindola. :)

The code was added in c01515d291 back in 2015. As far as I know the only
thing that would use a function is a UDA, but I didn't even use this
method when implementing UDA.

Patch LGTM.

Cheers,
Rafael

**Comment by tgrabiec** [comment]
@espindola What about the check which prevents dropping a function used by another function?

C* has this check and I think we're missing it.

**Comment by dekimir** [comment]
Also: if there's a check Cassandra has and we're missing, shouldn't there be an issue for that?  And if there is an issue for that, wouldn't we close it by saying what @espindola mentioned above: 

> the only thing that would use a function is a UDA

which, presumably, has a suitable check.

**Comment by psarna** [comment]
If there's a missing check, let's create an issue indeed, and it can be fixed later along with the rewrite. Rewriting the whole CQL layer is already a pain, so if this patch makes it a little easier, looks good to me - I'll speculatively enqueue this pull request in the hope that nobody opposes it :)

**Comment by psarna** [comment]
df3ea2443bd398be714bb51114af184278582933

**Review by psarna — APPROVED** [review]

**Comment by tgrabiec** [comment]
@dekimir UDA doesn't have the check, because we don't have UDA support yet. When we add it, we will have to reintroduce uses_function(). 

The current code comes directly from Cassandra, where it was used, so it has a high chance of being still correct. There is knowledge being embedded in it, so trying to preserve it is less risk than writing it from scratch later. That's intuition-based, not a hard proof.

**Comment by dekimir** [comment]
> @dekimir UDA doesn't have the check, because we don't have UDA support yet.

In that case, doesn't it follow that nothing can use a function ATM?

> The current code comes directly from Cassandra, where it was used, so it has a high chance of being still correct.

I disagree.  Even if that code came from today's Cassandra (and not Cassandra from five years ago), the chance of untested code being still correct is never high.  Consider the number of bugs recently found in the _tested_ parts of restrictions code.

> There is knowledge being embedded in it, so trying to preserve it is less risk than writing it from scratch later.

My experience with restrictions rewriting has been the exact opposite.  And Git history preserves the code anyway.

**Comment by espindola** [comment]
Tomasz Grabiec <notifications@github.com> writes:

> @espindola What about the check which prevents dropping a function used by another function?

Not having that feature. A UDF is only ever used from a UDA and we don't
have UDAs yet.

Cheers,
Rafael

**Comment by avikivity** [comment]
Merged in df3ea2443bd398be714bb51114af184278582933.

**Pull request closed without merging**
