### PR TITLE
doc: create a new CQL reference section to aggregate CQL information - V2

### PR DESCRIPTION
**Pull request by annastuchlik**
This PR is V2 of https://github.com/scylladb/scylla/pull/11065.

The scope of updates:
- Created a _/cql/_ folder.
- Moved all the CQL-related pages from _/getting-started/_ to _/cql/_ .
- Moved the _cql-extensions.md_ file from _/dev/_ to  _/cql/_ .
- Removed the outdated files and references.
- Updated the links to the CQL-related pages.

### CODE REVIEW

**Review by tzach — APPROVED** [review]
LGTM
We can improve the index page (see below), but it can be a followup PR, as this pr focus on reorganization.

The index page looks random, not logical order of the pages.
I would place DDL first, DML after etc.
image

**Comment by annastuchlik** [comment]
@tzach The order was supposed to be alphabetical, although there is one mistake, which I'll fix later. If you lean to a different order, we can discuss it outside of this PR.

**Comment by annastuchlik** [comment]
@nyh Could you merge it?

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
@annastuchlik I see Avi already merged it. It should eventually move to master after whatever random code that also came around that time get tested.

**Comment by annastuchlik** [comment]
@nyh This PR was merged, but there are conflicts in the redirects file - David removed some redirections and his PR was merged: https://github.com/scylladb/scylla/pull/11093.
Should I resolve the conflicts in this PR (it's easy to do)?

**Comment by nyh** [comment]
Maybe @avikivity  already fixed these conflicts while merging? Because I see he did merge it. This PR is no longer important after being merged, so you don't need to fix it.

**Comment by annastuchlik** [comment]
@nyh I get it, thank you!

**Comment by nyh** [comment]
@annastuchlik actually your were right, there is a problem:
It appears that @tzach accidentally (?) committed @dgarcia360 's patch directly to master, apparently after Avi already merged your patch to next, and now next cannot be merged with master.
I wrote a mail about deciding what to do here. We can remove @dgarcia360 's patch from master to have your patch go in, or leave it in master and rebase next (and fix your patch).

**Pull request merged**
