### PR TITLE
 view: differentiate identical error messages and change them to warn…

### LINKED ISSUE #4600: view_builder bookkeeping errors are actually warnings and aren't unique.
Seen in [dtest-release/158/artifact/logs-release.2/1561433162725_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/node2.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/158/artifact/logs-release.2/1561433162725_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/node2.log):
```
INFO  2019-06-25 03:23:42,099 [shard 0] init - stopping view builder
INFO  2019-06-25 03:23:42,099 [shard 0] view - Stopping view builder
INFO  2019-06-25 03:23:42,099 [shard 1] view - Stopping view builder
ERROR 2019-06-25 03:23:42,099 [shard 0] view - Failed to update materialized view bookkeeping (seastar::no_sharded_instance_exception (sharded instance does not exists)), continuing anyway.
```

I'm not sure if this came from `view_builder::execute` or `view_builder::calculate_shard_build_step`.

a. I think we better uniquify these two messages so we can distinguish between them.
b. Since we're continuing anyway, we better demote the log severity level from error to warn, this will also not fail the dtest.

### PR DESCRIPTION
**Pull request by wmitros**
…ings

Modified log message in view_builder::calculate_shard_build_step to make it distinct from the one in view_builder::execute, changed their logging level to warning, since we're continuing even if we handle an exception.

Fixes #4600

### CODE REVIEW

**Comment by wmitros** [comment]
I can't add reviewers right now so I'm tagging @psarna here.

**Comment by psarna** [comment]
Looks good! I'll queue once in front of the computer, so probably tomorrow.

**Comment by nyh** [comment]
Committed to next: 76038b8d8e5589d91a1cb8b4f469fe252ea36f3b

**Comment by psarna** [comment]
It was deliberate and I think that I was even the author, but after discussing it with Benny I think that downgrading to "warn" is the right choice - because these errors are all recoverable and they just confuse the tests.

**Pull request closed without merging**
