### PR TITLE
doc: Remove unused redirects

### PR DESCRIPTION
**Pull request by dgarcia360**
In https://github.com/scylladb/scylla-docs/pull/4138, we have moved the redirects from scylla.docs.scylladb.com to the [scylladb/scylla-docs](https://github.com/scylladb/scylla-docs) repository. For this reason, we can delete the following redirects.

### CODE REVIEW

**Comment by tzach** [comment]
@dgarcia360 for the record, how did you find all these broken links?

**Comment by dgarcia360** [comment]
@tzach This PR does not fix broken links, but removes unused redirections.

If you refer to https://github.com/scylladb/scylla-docs/pull/4139, I tested manually the redirections I generated during our call with more time.

If you refer to https://github.com/scylladb/scylla/pull/11092, I searched for all links that matched this regex with VSCode:

image

Which translates to "Find all links created without the "doc" directive (ending with an underscore) that does not contain htttp (internal links)).

**Comment by tzach** [comment]
> @tzach This PR does not fix broken links, but removes unused redirections.

Yes, I mixed up the PR sorry.
Thanks

**Comment by nyh** [comment]
@dgarcia360, @tzach accidentally merged this patch into master instead of next, causing in ability to promote next and also conflicts with other patches which were already in next.
@avikivity fixed this by removing your patch from master.
So the purple button saying "merged" on this pull request is now wrong.
Please create a new pull request for your branch. You'll probably need to rebase your branch on the newest master and probably solve some conflicts with Anna's patch that got in.

**Pull request merged**
