### PR TITLE
db: range_tombstone_list: Deoverlap empty range tombstones

### LINKED ISSUE #9661: row_cache_test.test_concurrent_reads_and_eviction: Mutation read doesn't match any expected version
This happened in the same test case as https://github.com/scylladb/scylla/issues/5349, but involved no bad_alloc exception so I'm opening a new issue for this.

Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4180/artifact/testlog/x86_64_debug/row_cache_test.test_concurrent_reads_and_eviction.3778.log
log file copied here: 
[row_cache_test.test_concurrent_reads_and_eviction.3778.log.gz](https://github.com/scylladb/scylla/files/7568551/row_cache_test.test_concurrent_reads_and_eviction.3778.log.gz)

```
test/boost/row_cache_test.cc(0): Entering test case "test_concurrent_reads_and_eviction"
==24120==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
WARNING: debug mode. Not for benchmarking or production
random-seed=1444721086
random_mutation_generator seed: 2319870
test/boost/row_cache_test.cc(3264): fatal error: in "test_concurrent_reads_and_eviction": Mutation read doesn't match any expected version, slice: ...
```

### PR DESCRIPTION
**Pull request by tgrabiec**
Appending an empty range adjacent to an existing range tombstone would
not deoverlap (by dropping the empty range tombstone) resulting in
different (non canoncial) result depending on the order of appending.

Suppose that range tombstone [a, b] covers range tombstone [x, x), and [a, x) and [x, b) are range tombstones which correspond to [a, b] split around position x.

Appending [a, x) then [x, b) then [x, x) would give [a, b)
Appending [a, x) then [x, x) then [x, b) would give [a, x), [x, x), [x, b)

The fix is to drop empty range tombstones in range_tombstone_list so that the result is canonical.

Fixes #9661

### CODE REVIEW

**Comment by tgrabiec** [comment]
Tests: 
  - unit [dev]

**Comment by xemul** [comment]
LGTM, but I think that it's better to tune the `test_random_list_is_not_overlapped` to allow for [x, x) tombstones and check that the output doesn't generate such.

**Comment by tgrabiec** [comment]
In V2:
  - extended test_random_list_is_not_overlapped to generate empty ranges

**Comment by bhalevy** [comment]
@xemul please re-review

**Comment by bhalevy** [comment]
Cc @cmm @mikolajsieluzycki

**Pull request merged**
