### PR TITLE
repair: Always use run_replace_ops

### LINKED ISSUE #8013: Cassandra stress fails to achieve consistency during replace node operation
*Installation details*
Scylla version (or git commit hash): 4.5.dev-0.20210127.a1f93e429 with build-id f53c1cdd5bf7a862ed05cdf0396dd5725eeaddce
Cluster size:6
OS (RHEL/CentOS/Ubuntu/AWS AMI):ami-0395803c0387e0e06 (eu-north-1)
Scenario: longevity-50GB-3days-authorization-and-tls-ssl

At `2021-01-29 11:32:34.192` a RestartThenRepairNode nemesis has started. The nemesis restarts the target node's (node 5 13.53.48.68 | 10.0.2.150) instance and then repairs it. Before the nemesis has started, all of the nodes were in UN status:
```
< t:2021-01-29 11:31:51,911 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > ====================
< t:2021-01-29 11:31:51,911 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Status=Up/Down
< t:2021-01-29 11:31:51,912 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2021-01-29 11:31:51,913 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > --  Address     Load       Tokens       Owns    Host ID                               Rack
< t:2021-01-29 11:31:51,940 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > UN  10.0.1.130  26.44 GB   256          ?       fe11c152-d394-4576-8c17-7ccfa6051959  1a
< t:2021-01-29 11:31:51,967 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > UN  10.0.2.180  27.97 GB   256          ?       3eb51651-337c-438b-9df4-c42361adc89f  1a
< t:2021-01-29 11:31:52,008 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > UN  10.0.2.150  29.48 GB   256          ?       2be3ee2c-60f4-4fde-9e30-d606f28d3568  1a
< t:2021-01-29 11:31:52,024 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > UN  10.0.0.166  28.92 GB   256          ?       c332aa51-44d2-471a-af20-ecdbc62ac613  1a
< t:2021-01-29 11:31:52,074 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > UN  10.0.1.89   24.85 GB   256          ?       39e8c89e-d451-47f4-86bc-364c78a5bd64  1a
< t:2021-01-29 11:31:52,120 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > UN  10.0.0.237  36.98 GB   256          ?       9d259a57-b1c6-4d05-9cf4-4154f44cdc6b  1a
```

However, after the target node was restarted, the C-S cannot achieve consistency and failed as a result:
```
java.io.IOException: Operation x10 on key(s) [343139364f4c31394c30]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:00.955: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3309 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-3 [13.51.48.87 | 10.0.2.106] (seed: False)
java.io.IOException: Operation x10 on key(s) [3631504c374b4b313430]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:00.965: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3290 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-2 [13.48.190.163 | 10.0.0.244] (seed: False)
java.io.IOException: Operation x10 on key(s) [4b37304c333137343131]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:00.973: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3330 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-3 [13.51.48.87 | 10.0.2.106] (seed: False)
java.io.IOException: Operation x10 on key(s) [36344b3331354d4b4b30]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:00.990: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3340 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-1 [13.49.73.146 | 10.0.3.204] (seed: False)
java.io.IOException: Operation x10 on key(s) [314d4d504c394e383231]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:00.990: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3340 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-1 [13.49.73.146 | 10.0.3.204] (seed: False)
java.io.IOException: Operation x10 on key(s) [314d4d504c394e383231]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:01.058: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3375 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-3 [13.51.48.87 | 10.0.2.106] (seed: False)
java.io.IOException: Operation x10 on key(s) [39393534385037333030]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:01.063: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3360 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-3 [13.51.48.87 | 10.0.2.106] (seed: False)
java.io.IOException: Operation x10 on key(s) [353437304b3233393531]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:01.072: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3334 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-2 [13.48.190.163 | 10.0.0.244] (seed: False)
java.io.IOException: Operation x10 on key(s) [38504c30375031373730]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2021-01-29 11:37:01.074: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=3346 node=Node longevity-tls-50gb-4d-master-loader-node-b38320d5-2 [13.48.190.163 | 10.0.0.244] (seed: False)
```
```
11:37:00.283 [cluster1-nio-worker-13] DEBUG c.d.driver.core.RequestHandler - [1587362874-0] Doing retry 1 for query com.datastax.driver.core.BoundStatement@21ffde94 at consistency null
11:37:00.283 [cluster1-nio-worker-13] DEBUG c.d.driver.core.RequestHandler - [1587362874-0] Error querying 10.0.2.180/10.0.2.180:9042 : com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
11:37:00.285 [cluster1-nio-worker-2] DEBUG c.d.driver.core.RequestHandler - [1215679576-0] Doing retry 1 for query com.datastax.driver.core.BoundStatement@50cb255 at consistency null
11:37:00.285 [cluster1-nio-worker-2] DEBUG c.d.driver.core.RequestHandler - [1215679576-0] Error querying 10.0.0.237/10.0.0.237:9042 : com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
11:37:00.289 [cluster1-nio-worker-13] DEBUG c.d.driver.core.RequestHandler - [366028438-0] Doing retry 1 for query com.datastax.driver.core.BoundStatement@3435a41 at consistency null
11:37:00.289 [cluster1-nio-worker-13] DEBUG c.d.driver.core.RequestHandler - [366028438-0] Error querying 10.0.2.180/10.0.2.180:9042 : com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
java.io.IOException: Operation x10 on key(s) [4b4e4e4f4d364d343430]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
FAILURE
```
(The node we used as the point of contact for the stress is node 1 (13.49.80.103 | 10.0.0.166), so the restart of node 5 (13.53.48.68 | 10.0.2.150) does not explain the C-S failure)
All of the stresses that were alive and running (across all three loaders) during the issue failed. All of them were write stresses, as follows:
```
cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compression=LZ4Compressor     compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=lz4    -rate threads=20  -pop seq=1..100000000 -log interval=5
cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compression=ZstdCompressor    compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none   -rate threads=20  -pop seq=1..100000000 -log interval=5
cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compression=SnappyCompressor  compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=snappy -rate threads=20  -pop seq=1..100000000 -log interval=5
cassandra-stress write cl=QUORUM n=100000000 -schema 'replication(factor=3) compression=DeflateCompressor compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none   -rate threads=20  -pop seq=1..100000000 -log interval=5
```


During the target node's restart, node 1 (13.49.80.103 | 10.0.0.166) experienced the following error:
```
2021-01-29T11:35:41+00:00  longevity-tls-50gb-4d-master-db-node-b38320d5-1 !WARNING | scylla: [shard 0] gossip - Fail to send EchoMessage to 10.0.2.150: std::runtime_error (Not ready to respond gossip echo message)
2021-01-29T11:35:43+00:00  longevity-tls-50gb-4d-master-db-node-b38320d5-1 !WARNING | scylla: [shard 0] gossip - Fail to send EchoMessage to 10.0.2.150: std::runtime_error (Not ready to respond gossip echo message)
2021-01-29T11:35:43+00:00  longevity-tls-50gb-4d-master-db-node-b38320d5-1 !WARNING | scylla: [shard 0] gossip - Fail to send EchoMessage to 10.0.2.150: std::runtime_error (Not ready to respond gossip echo message)
```
Even so, that error does not seem to imply that node 1 was down. I could not any evidence that any of the nodes crashed in that time span.
As such, and since only the single target node is suppose to be downed by the nemesis, it isn't clear why would the stress wouldn't be able to achieve consistency.

CPU utilization during the run:
![Screenshot from 2021-02-02 14-55-50](https://user-images.githubusercontent.com/40186893/106603364-db955a80-6566-11eb-8479-aa196415ebc3.png)
Monitor link: http://13.49.222.185:3000/d/KLdsxvYGk/longevity-50gb-3days-scylla-per-server-metrics-nemesis-master?orgId=1&from=1611915053719&to=1611923161763


Logs:
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                        Log links for testrun with test id b38320d5-9aa7-4f4a-ba70-e80b40874d31                                                                                                         |
+-----------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                                                   |
+-----------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20190101_010101 | prometheus  | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/prometheus_snapshot_20210129_115539.tar.gz                                                                                                                         |
| 20210129_114725 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_114725/grafana-screenshot-longevity-50gb-3days-scylla-per-server-metrics-nemesis-20210129_115115-longevity-tls-50gb-4d-master-monitor-node-b38320d5-1.png |
| 20210129_114725 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_114725/grafana-screenshot-overview-20210129_114725-longevity-tls-50gb-4d-master-monitor-node-b38320d5-1.png                                               |
| 20210129_115602 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_115602/grafana-screenshot-longevity-50gb-3days-scylla-per-server-metrics-nemesis-20210129_115917-longevity-tls-50gb-4d-master-monitor-node-b38320d5-1.png |
| 20210129_115602 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_115602/grafana-screenshot-overview-20210129_115602-longevity-tls-50gb-4d-master-monitor-node-b38320d5-1.png                                               |
| 20210129_120359 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_120359/db-cluster-b38320d5.zip                                                                                                                            |
| 20210129_120359 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_120359/loader-set-b38320d5.zip                                                                                                                            |
| 20210129_120359 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_120359/monitor-set-b38320d5.zip                                                                                                                           |
| 20210129_120359 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/b38320d5-9aa7-4f4a-ba70-e80b40874d31/20210129_120359/sct-runner-b38320d5.zip                                                                                                                            |
+-----------------+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by asias**
Currently, the new NODE_OPS_CMD for replace operation is used only when
repair based node operation is enabled. However, We can use the
NODE_OPS_CMD to run replace operation and use streaming instead of
repair to sync data as well.

After this patch, we will use streaming inside run_replace_ops if repair
based node ops is not enabled. So that we can take the benefits that
NODE_OPS_CMD brings in commit 323f72e48a7d89d9edc40257a1f45c202accc146
(repair: Switch to use NODE_OPS_CMD for replace operation).

Fixes #8013

### CODE REVIEW

**Comment by asias** [comment]
@slivne @bhalevy FYI, this patch closes the gap of #8013 completely.

**Comment by tgrabiec** [comment]
The patch looks ok, but it switches replace to use the new node_ops algorithm unconditionally. It's up to @avikivity to decide if it's ok.

**Comment by asias** [comment]
> The patch looks ok, but it switches replace to use the new node_ops algorithm unconditionally. It's up to @avikivity to decide if it's ok.

We already use the node cmd ops unconditionally for decommission and removenode operations. Being able to revert the operation in case of error is huge win in the field, in my view, it is better to switch to it sooner than later.

**Comment by avikivity** [comment]
> > The patch looks ok, but it switches replace to use the new node_ops algorithm unconditionally. It's up to @avikivity to decide if it's ok.
> 
> We already use the node cmd ops unconditionally for decommission and removenode operations. Being able to revert the operation in case of error is huge win in the field, in my view, it is better to switch to it sooner than later.

Isn't it conditional on enable_repair_based_node_ops?

**Comment by asias** [comment]
> > > The patch looks ok, but it switches replace to use the new node_ops algorithm unconditionally. It's up to @avikivity to decide if it's ok.
> > 
> > 
> > We already use the node cmd ops unconditionally for decommission and removenode operations. Being able to revert the operation in case of error is huge win in the field, in my view, it is better to switch to it sooner than later.
> 
> Isn't it conditional on enable_repair_based_node_ops?

replace and boostrap operation are currently only use node cmd ops if enable_repair_based_node_ops is enabled. We always use node cmd ops for decommission and removenode, when enable_repair_based_node_ops is on we use repair, when enable_repair_based_node_ops is off we use stream to sync data.

**Comment by asias** [comment]
@avikivity ping for merge.

**Comment by asias** [comment]
@avikivity ping for merge ^2.

**Comment by avikivity** [comment]
> is enabled. We always use node cmd o

Ok. This is confusing, both an IDL change and a mechanism change, and any combination works.

**Comment by asias** [comment]
Merged as 2ec1f719de29d98e1be7fc7c171b06986b81af14 in master.

**Pull request closed without merging**
