### PR TITLE
[branch 4.5] mutation_writer: feed_writer(): handle exceptions from consume_end_of_stream()

### PR DESCRIPTION
**Pull request by denesb**
Currently the exception handling code of feed_writer() assumes consume_end_of_stream() doesn't throw. This is false and an exception from said method can currently lead to an unclean destroy of the writer and reader. Fix by also handling exceptions from     consume_end_of_stream() too.
Only affects <4.5, 4.6 and later rewrote `feed_writer()` with coroutines.

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]
LGTM

I see that in 4.6 and later this is done in de55ab571b9041cdcbd8a85153ba74fc649b5176

**Comment by avikivity** [comment]
Closing per comment.

**Comment by avikivity** [comment]
Was there a relevant issue?

**Comment by denesb** [comment]
The relevant issue is https://github.com/scylladb/scylla-enterprise/issues/2026.

**Comment by bhalevy** [comment]
I interpreted @avikivity's question if the was a relevant issue for the respective change de55ab571b9041cdcbd8a85153ba74fc649b5176 but it seems like you fixed a bug there along the conversion to a coroutine with no github issue backing it.

**Pull request closed without merging**
