### PR TITLE
replica: create a replica module

### PR DESCRIPTION
**Pull request by avikivity**
Move the ::database, ::keyspace, and ::table classes to a new replica
namespace and replica/ directory. This designates objects that only
have meaning on a replica and should not be used on a coordinator
(but note that not all replica-only classes should be in this module,
for example compaction and sstables are lower-level objects that
deserve their own modules).

The module is imperfect - some additional classes like distributed_loader
should also be moved, but there is only one way to untie Gordian knots.

### CODE REVIEW

**Comment by denesb** [comment]
> Move the ::database, ::keyspace, and ::table classes to a new replica namespace and replica/ directory. This designates objects that only have meaning on a replica and should not be used on a coordinator (but note that not all replica-only classes should be in this module, for example compaction and sstables are lower-level objects that deserve their own modules).

Big +1.

> The module is imperfect - some additional classes like distributed_loader should also be moved, but there is only one way to untie Gordian knots.

There is actually a second way (used by Alexander the Great) but that only works if you don't care about the rope surviving. :)

**Review by denesb — APPROVED** [review]
LGTM
There is not much to review on the code itself as its a mechanical refactor.
I fully support the idea of breaking up the huge mud-ball that is our root directory (even if your motives were different).

**Review by psarna — APPROVED** [review]

**Comment by denesb** [comment]
Has conflicts, please rebase.

**Comment by avikivity** [comment]
v2: rebased

**Comment by avikivity** [comment]
v3: adjusted scylla-gdb.py

**Pull request closed without merging**
