### PR TITLE
treewide: change metric calls from make_derive to make_counter

### PR DESCRIPTION
**Pull request by avikivity**
make_derive was recently deprecated in favor of make_counter, so
make the change throughput the codebase.

### CODE REVIEW

**Review by psarna — APPROVED** [review]

**Comment by psarna** [comment]
oh wait, I queued this one, but then noticed the failure, so dequeueing. Looks rather random, but I'll wait for CI to agree

**Comment by psarna** [comment]
Ok - same test failed again, so perhaps it's a genuine bug indeed

**Comment by xemul** [comment]
I guess seastar update crept into the commit (@avikivity )

**Comment by avikivity** [comment]
Argh, thanks for catching. I almost never use `git add -u`, but when I do, it's bad.

Luckily the breakage alerted us.

**Comment by avikivity** [comment]
v2: without the unintended seastar update

**Pull request closed without merging**
