### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by psarna**
```
* seastar ff46af9a...2dee550b (2):
  > Merge 'Add initial support for websocket protocol' from Andrzej Stalke
  > Merge 'abort_source: request_abort: allow passing exception to subscribers' from Benny Halevy
```

### CODE REVIEW

**Comment by psarna** [comment]
(for CI purposes)

**Comment by psarna** [comment]
@bhalevy there seems to be a failure related to your https://github.com/scylladb/seastar/commit/f3749938ad9f77cce04359805742ba96aa635602 patch:   https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1030/consoleText

```
[2022-06-24T07:54:37.705Z] main.cc:118:35: error: no matching member function for call to 'invoke_on_all'
[2022-06-24T07:54:37.705Z]             return _abort_sources.invoke_on_all(&abort_source::request_abort);
[2022-06-24T07:54:37.705Z]                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
[2022-06-24T07:54:37.705Z] /jenkins/workspace/releng/Scylla-CI/scylla/seastar/include/seastar/core/sharded.hh:214:14: note: candidate function not viable: no overload of 'request_abort' matching 'std::function<future<> (abort_source &)>' for 1st argument
[2022-06-24T07:54:37.705Z]     future<> invoke_on_all(std::function<future<> (Service&)> func) noexcept {
[2022-06-24T07:54:37.705Z]              ^
[2022-06-24T07:54:37.705Z] /jenkins/workspace/releng/Scylla-CI/scylla/seastar/include/seastar/core/sharded.hh:247:14: note: candidate template ignored: couldn't infer template argument 'Func'
[2022-06-24T07:54:37.705Z]     future<> invoke_on_all(Func func, Args... args) noexcept {
[2022-06-24T07:54:37.705Z]              ^
[2022-06-24T07:54:37.705Z] /jenkins/workspace/releng/Scylla-CI/scylla/seastar/include/seastar/core/sharded.hh:207:14: note: candidate function not viable: requires 2 arguments, but 1 was provided
[2022-06-24T07:54:37.705Z]     future<> invoke_on_all(smp_submit_to_options options, std::function<future<> (Service&)> func) noexcept;
[2022-06-24T07:54:37.705Z]              ^
[2022-06-24T07:54:37.705Z] /jenkins/workspace/releng/Scylla-CI/scylla/seastar/include/seastar/core/sharded.hh:238:14: note: candidate function template not viable: requires at least 2 arguments, but 1 was provided
[2022-06-24T07:54:37.705Z]     future<> invoke_on_all(smp_submit_to_options options, Func func, Args... args) noexcept;
[2022-06-24T07:54:37.705Z]              ^
[2022-06-24T07:54:37.705Z] In file included from main.cc:9:
[2022-06-24T07:54:37.705Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:49:
[2022-06-24T07:54:37.705Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_function.h:60:
[2022-06-24T07:54:37.705Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/move.h:57:
[2022-06-24T07:54:37.705Z] /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/type_traits:3009:5: error: no type named 'type' in 'std::invoke_result<(lambda at main.cc:117:84)>'
(...)
```


Does it need a custom Scylla patch for compatibility to be pushed along with the update? If so, I'd be obliged if you provide one (:

**Comment by psarna** [comment]
Maybe the Seastar-side fix is easy, so I'll optimistically wait with the revert, let me know if you figure something out.

**Comment by bhalevy** [comment]
> Maybe the Seastar-side fix is easy, so I'll optimistically wait with the revert, let me know if you figure something out.

okay, great.  I think thay restoring the request_abort methid that accepts no args will do, rather than defaulting the optional exception_ptr to nullopt.

**Comment by psarna** [comment]
Updated the update so that it contains https://github.com/scylladb/seastar/commit/6ee2a1ff3e5ed7d51e259ff4abeab6a4789ecf13, let's see what CI thinks about it

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla/pull/10898 updated seastar at a later change.
@psarna I think this PR can be closed.

**Pull request closed without merging**
