### PR TITLE
docs: moved latest_version to conf.py

### PR DESCRIPTION
**Pull request by dgarcia360**
**Related issues:** https://github.com/scylladb/sphinx-scylladb-theme/issues/87

All the variables related to the multiversion extension are now defined in ``conf.py`` instead of using the GitHub Actions file.

##  How to test this PR

Run ``make multiversionpreview`` on ``docs`` folder. When you open https://0.0.0.0:5500,  the browser should render the documentation site.

### CODE REVIEW

**Comment by dgarcia360** [comment]
@tzach Could you please review? Thanks!

**Comment by tzach** [comment]
`make multiversionpreview` works, but only present master
I try to update config.py
```
 # Whitelist pattern for branches (set to None to ignore all branches)
-BRANCHES = ['master']
+BRANCHES = ['master', 'branch-4.3', 'branch-4.4', 'branch-4.5']
```
but I only see "Master" on the preview. What am I'm doing wrong?

**Comment by lauranovich** [comment]
I tried to run the PR
I was able to get it to build with no errors, but I got the following when doing multiversion. 
Error response
Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.

**Comment by dgarcia360** [comment]
> but I only see "Master" on the preview. What am I'm doing wrong?

By default, the command builds the documentation that is available on GitHub (origin remote repository).

If I open [your fork](https://github.com/tzach/scylla) on GitHub (origin remote repository), I can see you don't have the branches "'branch-4.3", "branch-4.4" & "branch-4.5" created.

image

To make it work, please follow [one of these options](https://github.com/scylladb/scylla-monitoring/issues/1437#issuecomment-869472286). I recommend you to follow A) [Build multiversion for the upstream repo](https://sphinx-theme.scylladb.com/stable/configuration/troubleshooting.html#i-want-to-preview-the-documentation-published-in-production).

To make this easier, we could add a parameter to the multiversion command to choose from which source do you want to preview multiversion docs (e.g. ``make multiversionpreview (--local, --upstream, --origin)``). Nevertheless, if you choose local or origin you will still need to make sure that your fork has the branches you are trying to build docs for.

**Comment by dgarcia360** [comment]
Please try:

```
gh repo clone scylladb/scylla
cd scylla/docs
gh pr checkout 7957
make multiversionpreview
```

**Comment by lauranovich** [comment]
All good to go!
@avikivity or @nyh  please review - this PR runs with no issues

**Review by lauranovich — APPROVED** [review]

**Pull request closed without merging**
