### PR TITLE
remove date type

### PR DESCRIPTION
**Pull request by espindola**
This is split in two patches so that it is easy to drop the last one if it turns out we need to keep date_type.

### CODE REVIEW

**Comment by denesb** [comment]
We should either commit both patches or none. If a type can theoretically can be created (even if not through CQL) it should be used by `random_schema`.
BTW have you checked that it is not possible to create the type though thrift either?

**Comment by espindola** [comment]
I will move the tests removal to the second patch.

I never looked at thrift. What is a good point to take a look?

**Comment by denesb** [comment]
I'm not too familiar with thrift, look in the `thrift` folder. I vaguely recall that in thrift you could specify the name of the type class you wanted to use, e.g. `org.apache.cassandra.db.marshal.DataType`, so you might be able to instantiate types not accessible from CQL.

**Comment by espindola** [comment]
Abandoned in favour of https://github.com/scylladb/scylla/pull/4931

**Pull request closed without merging**
