### PR TITLE
fixing --experimental flag option from "on" to "1"

### PR DESCRIPTION
**Pull request by guy9**
When trying to run with "--experimental=on" I get:
File "/usr/lib64/python3.6/argparse.py", line 2318, in _check_value
   raise ArgumentError(action, msg % args)
argparse.ArgumentError: argument --experimental: invalid choice: 'on' (choose from '0', '1')

### CODE REVIEW

**Comment by tzach** [comment]
https://docs.scylladb.com/operating-scylla/scylla-yaml/#enable-all-experimental-features

**Comment by nyh** [comment]
We have in both dist/docker/redhat/scyllasetup.py and alternator-test/run the "--experimental=on", and it works! What changed?
By the way, LWT is no longer experimental,so when we commit that change (if I haven't done it, I'll do it now) we can completely drop this line instead of fixing it.

**Comment by nyh** [comment]
I just realized in the issue description above you quoted a Python error message... But why Python? Scylla is a C++ program... What exactly did you try to run?

**Comment by nyh** [comment]
Ok, I know what the problem is... You didn't run Scylla, you ran the docker image and it ran the script docs/alternator/alternator.md. This script has:

        if self._experimental == "1":
            args += ["--experimental=on"]

I don't know why this script has a different convention for experimental... @penberg ?
In any case, since LWT is no longer experimental, I think we should close this PR and drop any mention of experimental in the Alternator documentation. I'm opening an issue for this right now.

**Comment by nyh** [comment]
Opened https://github.com/scylladb/scylla/issues/6118.
Closing this PR because it's invalid. Scylla indeed uses "--experimental=on" and alternator.md, and it shouldn't be fixed. The docker image indeed uses "--experimental=1" but that's correctly explained in getting-started.md.

**Pull request closed without merging**
