### PR TITLE
Move Cassandra specific code to separate module

### PR DESCRIPTION
**Pull request by penberg**
The scylla.git repository started out as a re-implementation of Apache
Cassandra and, therefore, followed the directory structure of
cassandra.git in many cases. However, scylla.git has since then gained
support for DynamoDB and Redis APIs, both of which have their own
top-level modules, "alternator" and "redis".

Let's move the Cassandra-specific code to an top-level "cassandra"
module to make the code more discoverable and modular.

### CODE REVIEW

**Review by kostja — CHANGES_REQUESTED** [review]
I think the code is already quite discoverable since cql3 and thrift are two fairly independent frontends, so there is little value in putting them together. Besides, not all cassandra legacy is encapsulated in cassandra with this transition, for good or bad, e.g. storage format, jmx support, so it can be somewhat confusing. 
This is just my 2c. I thought there was a discussion on the mailing list already , and some plan must have settled out of it. I suggest we finalize the decision on the mailing list and then implement it here. If there was a decision to put cql3 and thrift together into cassandra/ I must have missed it.

**Comment by nyh** [comment]
> Let's move the Cassandra-specific code to an top-level "cassandra"
> module to make the code more discoverable and modular.

The patch itself is very long, so please explain in the commit message exactly what is this "Cassandra-specific code" which you are moving - e.g., cql3/* and transport/*? Anything else? As @kostja noted, it's not clear what is the full extent of "Cassandra specific" code, or that you actually moved all of it. It's fine not to move all of it in this patch, but we should be clear about it.

By the way, I'm pretty sure even after such a patch there will be blurry boundaries, like cassandra/ header files included in Alternator, or Cassandra-specific things outside the cassandra/ directory. But those things can be fixed later.

@avikivity are you fine with a subdirectory called "cassandra"? I remember in the past you didn't want a "dynamodb" subdirectory and chose the name "alternator" instead, although you were fine with "redis", so I don't know where the line stands.

**Comment by avikivity** [comment]
I don't mind a directory called "cassandra", but the cost/benefit ratio is pretty bad. One the cost side we break everyone's muscle memory and backports, and make all paths longer. On the benefit side we have that "thrift" and transport" are clearly associated with Cassandra, but I wasn't aware that it was a large problem to begin with.

I don't mind renaming when there's a clear benefit, but here is seems marginal.

**Comment by penberg** [comment]
@nyh Imagine you want to build a version of Scylla that only supports DynamoDB or Redis, for example. The point of encapsulating "Cassandra-specific" code is to _start the effort_ of modularizing things. I have no idea how deep the rabbit hole is, but as you already stated elsewhere, Alternator already includes stuff from "cql3", which is likely a layering violation. Having a "cassandra" layer makes it easier to start this effort.

@avikivity The `transport` module is in _no way_ associated with Cassandra, except for those of us who already know that to be the case. Many seem to agree we can rename it to `cql-protocol`, for example, for clarity, but I am suggesting `cassandra/transport` to be symmetric with the DynamoDB and Redis front-ends.

@kostja I do not agree that the modules are now discoverable. I also don't think we should transition everything in one go, because -- as you can see here -- it's already impossible to make forward progress with simple renames like this.

**Comment by kostja** [comment]
> @kostja I do not agree that the modules are now discoverable. I also don't think we should transition everything in one go, because -- as you can see here -- it's already impossible to make forward progress with simple renames like this.

I agree we can split the transition into steps, as long as these steps are not like adoption of [Swedish Calendar](https://en.wikipedia.org/wiki/Swedish_calendar).

**Comment by penberg** [comment]
Closing as stale.

**Pull request closed without merging**
