### PR TITLE
table: Make make_reader_v2_excluding_sstables() account for a possible clone of excluded files

### PR DESCRIPTION
**Pull request by raphaelsc**
There's an undergoing change which clones sstables from staging dir to
the base dir, allowing sstables in base dir to be compacted
indepedently. The problem is that view builder will not exclude those cloned
files when using make_reader_v2_excluding_sstables(), just the ones in
staging dir.

As a cloned file is just another link to a staging sstable, we can solve this
problem by filtering out all sstables that share the run identifier with
any of those files being explicitly excluded.

Refs #9559.

Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>

### CODE REVIEW

**Comment by raphaelsc** [comment]
Now that I think about it, I am not sure using run_identifier() is the correct thing to do as we may end up filtering out other fragments in the same run which should be actually included. I am withdrawing this pull request in favor of a better one.

**Comment by bhalevy** [comment]
> Now that I think about it, I am not sure using run_identifier() is the correct thing to do as we may end up filtering out other fragments in the same run which should be actually included. I am withdrawing this pull request in favor of a better one.

True.

Note that I unfortunately had to revert the relevant parts of the compact-staging-sstables series in 81fa1ce9a15d23709399b887835d3b84bab5ed28 due to this exclusion problem.

another issue with your proposed change is that the clone may already be compacted (that was the whole point of cloning it) and then we have no way to exclude only the data that is in the staging sstable.

We need to get back to the drawing board to figure out a solution for #9559.

**Comment by bhalevy** [comment]
let's continue the discussion in #9559

**Comment by raphaelsc** [comment]
> > > > Now that I think about it, I am not sure using run_identifier() is the correct thing to do as we may end up filtering out other fragments in the same run which should be actually included. I am withdrawing this pull request in favor of a better one.
> > > 
> > > 
> > > True.
> > > Note that I unfortunately had to revert the relevant parts of the compact-staging-sstables series in [81fa1ce](https://github.com/scylladb/scylla/commit/81fa1ce9a15d23709399b887835d3b84bab5ed28) due to this exclusion problem.
> > > another issue with your proposed change is that the clone may already be compacted (that was the whole point of cloning it) and then we have no way to exclude only the data that is in the staging sstable.
> > 
> > 
> > assuming there would be a 1:1 relationship between an id and fs inode, then it would work because the idea is to exclude all sstables that share the same fs inode.
> 
> But the reason to exclude them, for view update building purposes, is not the sstable id per-se, but rather the data in it. The view update builder compares the contents in the staging sstables against the contents in the table, excluding the staging sstables. With the clones in the table's main sstable set, the view builder sees no diff so it produces no view updates. Even if we were able to exclude the cloned sstables based on inode identity, what I'm saying is that if they get compacted - their contents will be copied to new sstables that we can't exclude and this will again cause the view builder to see no diff and generate no view updates.

You're correct. thanks for the explanation.

**Pull request closed without merging**
