### PR TITLE
doc: create migration redirections

### PR DESCRIPTION
**Pull request by dgarcia360**
## Motivation

According to the [migration plan](https://docs.google.com/document/d/15yBf39j15hgUVvjeuGR4MCbYeArqZrO1ir-z_1Urc6A/edit?usp=sharing), the domain docs.scylladb.com will point to this repository. 

The original repository (scylladb/scylla-docs) did not have multi-version enabled, while this repository does:

- Before:  docs.scylladb.com/getting-started.
- Now: docs.scylladb.com/**stable**/getting-started/

For this reason, we should create redirects for all the links that do not have the version name.

This PR edits the `redirects.yml` file as follows:

- Creates redirections for all the files that we have migrated in https://github.com/scylladb/scylla/pull/10976, adding the "stable" prefix.
- Moves the contents from the original `redirections.yml` file to the new `redirects.yml` file taking into account multiversion.

## How to test this PR

1. Enter the docs folder.
2. Run `make redirects`.
3. Open `docs/_build/dirhtml/kb/index.html` in your browser. It should redirect you to `stable/kb`

Before we change the domain name, we will do additional tests on the live site once this PR gets merged.

### CODE REVIEW

**Comment by dgarcia360** [comment]
cc @annastuchlik @tzach

**Comment by tzach** [comment]
> Run make redirects.

isnt this part of the doc build?

**Comment by dgarcia360** [comment]
@tzach No, `make redirects` it's called after the build: https://github.com/scylladb/scylla/blob/master/.github/workflows/docs-pages.yaml#L31

In https://github.com/scylladb/sphinx-scylladb-theme/pull/515 we decoupled creating redirections from the build process so that we can have more control in projects with multiversion enabled.

**Comment by annastuchlik** [comment]
LGTM. Works as expected.

**Comment by tzach** [comment]
LGTM

**Comment by tzach** [comment]
@nyh ping

**Pull request closed without merging**
