### PR TITLE
cdc: set ttl column in log rows which update only collections

### PR DESCRIPTION
**Pull request by kbr-**
Fixes https://github.com/scylladb/scylla/issues/6505.

### CODE REVIEW

**Comment by psarna** [comment]
Looks good, I'll enqueue once somebody fluent in CDC approves.

**Comment by haaawk** [comment]
@psarna ready to go

**Comment by psarna** [comment]
I was sure I queued this one yesterday, but it looks like I did not, so here it is: 398f2957915fabef0eff17574654e2343aef774b

**Comment by slivne** [comment]
@haaawk whats the status of this one - do we need it - was it merged ?

**Comment by haaawk** [comment]
Seems like @psarna has merged it -> https://github.com/scylladb/scylla/commit/398f2957915fabef0eff17574654e2343aef774b. Closing...

**Pull request closed without merging**
