### PR TITLE
db,view: improve verbosity of errors coming from view updates

### LINKED ISSUE #8177: Improve the verbosity of errors coming from the view builder/updater
*Installation details*
HEAD: 0e0282cdf1b57c23354a3e356016bf33b6a8788a

*Description*
We need to improve the verbosity of errors like these:

```
[shard 17] view - Error applying view update to 10.10.5.59: std::invalid_argument (Mutation of 68781501 bytes is too large for the maximum size of 16777216)
```

It would really help to know which view is being updated and if possible some more info about the base partition(s) and the destination view partition(s) involved.

### PR DESCRIPTION
**Pull request by psarna**
The error now contains information about the view table that failed.
Example:
view - Error applying view update (ks.testme_v_idx_index) to 127.0.0.1: std::runtime_error (manually injected error)

Fixes #8177

### CODE REVIEW

**Comment by avikivity** [comment]
Dequeueing, fell afoul of error pattern in dtest  interrupt_build_process_with_resharding_half_to_max_test (materialized_views_test.TestMaterializedViews).

**Comment by psarna** [comment]
Ugh, I'll just rephrase the message to still match the regex in dtests - it will still bear the same information, just in a slightly different place in the string.

**Comment by psarna** [comment]
v2:
 - rephrased the message to still match dtest regex
 - added base and view token info as per @vladzcloudius's wish, to make it easier to pinpoint which partition is causing trouble

**Review by nyh — APPROVED** [review]
Looks good. I see Avi already committed this, so nothing left for me to do.

**Pull request closed without merging**
