### PR TITLE
test/cql-ptest: add tests for collection indexing

### PR DESCRIPTION
**Pull request by nyh**
This patch adds an extensive array of tests for the Cassandra feature
that Scylla hasn't implemented yet (issues #2962, #8745, #10707) of
indexing the keys, values or entries of a collection column.

The goal of these tests is to explicitly exercise every corner case
I could think of by looking at the documentation of this feature and
considering its possible implementation - and as usual, making sure
that the tests actually pass on Cassandra.

These tests overlap some of the existing unit tests that we translated
from Cassandra, as well as some randomized tests that do not necessarily
cover the same edge cases as these tests cover.

All tests added in this patch pass on Cassandra, but currently fail
on Scylla due to the above issues.

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

### CODE REVIEW

**Comment by nyh** [comment]
This is another set of tests with which to test the functionality of @enedil 's  collection-indexing patches in https://github.com/scylladb/scylla/pull/10123.

It tried to cover every corner case I could think of, and the result is 400 lines of test code covering both the basic functionality and various bizarre corner cases like quoted column names (which we know that the pull request doesn't cover yet). There's quite a bit of overlap between these tests and other tests we already had (both translated from Cassandra and randomized tests that @enedil wrote), but I do believe that there's value in trying to sit down and write tests that cover every single aspect of the functionality that we can think of in an explicit (not random) way, and compare it to Cassandra to be sure that we're implementing the right thing.

**Review by psarna — APPROVED** [review]

**Comment by psarna** [comment]
CI died, retriggering

**Comment by nyh** [comment]
One unrelated (supposedly...) test failed - test_materialized_view.py::test_mv_quoted_column_names_build. I'll investigate whether this some sort of flaky test (?) or some interaction between the tests.

**Comment by nyh** [comment]
Sadly, it appears that the CI failed yet again with a random, unrelated failure, this time in the C++ unit test: boost.view_complex_test.debug.test_update_column_not_in_view_with_flush

The test report is useless: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/780/testReport/junit/boost.view_complex_test/debug/test_update_column_not_in_view_with_flush/

I'll restart the CI again, but Houston, I think we have a problem :-(

**Pull request closed without merging**
