### PR TITLE
scylla-python3: move scylla-python3 to separated repository

### LINKED ISSUE #6751: dist: scylla-python3 should be separated repository
Except scylla-python3, each scylla package has its own git repository, same package script filename, same build directory structure.
To put python3 thing on scylla repo, we created 'python3' directory on multiple locations, made '-python3' suffixed files, dig deeper build directory not to conflict scylla-server package build.
We should move all scylla-python3 related files to new repository, scylla-python3.
Since we recently added scylla-jmx and scylla-tools as git submodule, we can move scylla-python3 to another submodule, too.

Here's RFC version of scylla-python3 repo, with latest next code:
https://github.com/syuu1228/scylla-python3

After moved it to new repo, we can drop these scripts:
```
[syuu@monster scylla.3]$ git status
On branch next
Your branch is up to date with 'origin/next'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    dist/debian/python3/build_deb.sh
	deleted:    dist/debian/python3/changelog.template
	deleted:    dist/debian/python3/control.template
	deleted:    dist/debian/python3/debian/compat
	deleted:    dist/debian/python3/debian/copyright
	deleted:    dist/debian/python3/debian/rules
	deleted:    dist/debian/python3/debian_files_gen.py
	deleted:    dist/redhat/python3/build_rpm.sh
	deleted:    dist/redhat/python3/python.spec
	deleted:    python3/install.sh
	deleted:    reloc/python3/build_deb.sh
	deleted:    reloc/python3/build_reloc.sh
	deleted:    reloc/python3/build_rpm.sh
	deleted:    scripts/create-relocatable-package-python3.py
```

### PR DESCRIPTION
**Pull request by syuu1228**
This is v2 of #6805, added wrapper scripts on reloc/python3 to keep compatibility with existing jenkins scripts.
This also requires to merge https://github.com/scylladb/scylla-python3/pull/2 to make it work.

----

Except scylla-python3, each scylla package has its own git repository, same package script filename, same build directory structure.
To put python3 thing on scylla repo, we created 'python3' directory on multiple locations, made '-python3' suffixed files, dig deeper build directory not to conflict scylla-server package build.
We should move all scylla-python3 related files to new repository, scylla-python3.

Add wrapper scripts on reloc/python3 for keep compatibility of Jenkins build job, for now.

Fixes #6751

### CODE REVIEW

**Comment by avikivity** [comment]
./reloc/python3/build_reloc builds in the wrong place - the output is in tools/python3/build/scylla-python3-package.tar.gz.

**Comment by avikivity** [comment]
Please make sure the rpm and deb also land in the existing places, including when called via ninja.

**Comment by syuu1228** [comment]
> ./reloc/python3/build_reloc builds in the wrong place - the output is in tools/python3/build/scylla-python3-package.tar.gz.

We can do that, but changing the result binary path may also causes next promotion failure since the path is hardcoded on jenkins script, no?
https://github.com/scylladb/scylla-pkg/blob/master/scripts/jenkins-pipelines/groovy_modules/artifact.groovy#L125

**Comment by yaronkaikov** [comment]
@syuu1228 We can change it, Let me know when so we can merge it together

**Comment by avikivity** [comment]
> > ./reloc/python3/build_reloc builds in the wrong place - the output is in tools/python3/build/scylla-python3-package.tar.gz.
> 
> We can do that, but changing the result binary path may also causes next promotion failure since the path is hardcoded on jenkins script, no?
> https://github.com/scylladb/scylla-pkg/blob/master/scripts/jenkins-pipelines/groovy_modules/artifact.groovy#L125

It's better to keep the result in build/python3 so that all build results are under scylla.git/build rather than the submodules.

**Comment by syuu1228** [comment]
> > > ./reloc/python3/build_reloc builds in the wrong place - the output is in tools/python3/build/scylla-python3-package.tar.gz.
> > 
> > 
> > We can do that, but changing the result binary path may also causes next promotion failure since the path is hardcoded on jenkins script, no?
> > https://github.com/scylladb/scylla-pkg/blob/master/scripts/jenkins-pipelines/groovy_modules/artifact.groovy#L125
> 
> It's better to keep the result in build/python3 so that all build results are under scylla.git/build rather than the submodules.

It currently saved at scylla/build/release/scylla-python3-package.tar.gz not build/python3.
I think we can merge this first to keep compatibility with current jenkins script, then switch to new location (tools/python3/build/scylla-python3-package.tar.gz) by updating the jenkins script.

**Comment by syuu1228** [comment]
> > > > ./reloc/python3/build_reloc builds in the wrong place - the output is in tools/python3/build/scylla-python3-package.tar.gz.
> > > 
> > > 
> > > We can do that, but changing the result binary path may also causes next promotion failure since the path is hardcoded on jenkins script, no?
> > > https://github.com/scylladb/scylla-pkg/blob/master/scripts/jenkins-pipelines/groovy_modules/artifact.groovy#L125
> > 
> > 
> > It's better to keep the result in build/python3 so that all build results are under scylla.git/build rather than the submodules.
> 
> It currently saved at scylla/build/release/scylla-python3-package.tar.gz not build/python3.
> I think we can merge this first to keep compatibility with current jenkins script, then switch to new location (tools/python3/build/scylla-python3-package.tar.gz) by updating the jenkins script.

After merging new jenkins script we can drop reloc/python3.

**Comment by avikivity** [comment]
> It currently saved at scylla/build/release/scylla-python3-package.tar.gz not build/python3.

I don't see it. The rule is

```
 build tools/python3/build/scylla-python3-package.tar.gz: build-submodule-reloc
```



> I think we can merge this first to keep compatibility with current jenkins script, then switch to new location (tools/python3/build/scylla-python3-package.tar.gz) by updating the jenkins script.


I want to consolidate all build products under scylla.git/build, not scatter them around the tree.

**Comment by syuu1228** [comment]
@avikivity Seems like jenkins job for next branch is now using dist target of ninja-build instead of calling ./reloc/build_*.sh, I updated the PR to generate packages under build/ directory (implemented at compat-python3-* on configure.py, once jenkins job updated these targets can delete).

**Comment by avikivity** [comment]
@syuu1228 we should instead modify scylla-python3 to be able to build into a directory supplied by scylla.git ninja. I'd like all the build products to be at scylla.git/build/ so users don't have to hunt for them.

**Comment by avikivity** [comment]
(I'll test and apply this patch)

**Comment by avikivity** [comment]
Queued as 352a136ae2.

**Pull request closed without merging**
