### PR TITLE
db/virtual tables: Add infrastructure + system.status example table

### LINKED ISSUE #8343: Add infrastructure for virtual tables
Cut out the relevant parts from https://github.com/scylladb/scylla-dev/tree/call, add tests and upstream it.
Possibly also apply the fixes listed here: https://www.scylladb.com/2020/12/29/scylladb-developer-hackathon-managing-scylla-using-cql/

### PR DESCRIPTION
**Pull request by StarostaGit**
This is the 1st PR in series with the goal to finish the hackathon project authored by @tgrabiec, @kostja, @amnonh and @mmatczuk (improved virtual tables + function call syntax in CQL). Virtual tables created within this framework are "materialized" in memtables, so current solution is for small tables only. As an example system.status was added. It was checked that DISTINCT and reverse ORDER BY do work.

This PR was created by @jul-stas and @StarostaGit
Fixes #8343

This is the same as #8364, but with a compilation fix (newly added `close()` method was not implemented by the reader)

### CODE REVIEW

**Comment by StarostaGit** [comment]
Fixed the `alternator/run` test problem
@tgrabiec

**Comment by StarostaGit** [comment]
@tgrabiec ping

**Comment by tgrabiec** [comment]
@StarostaGit What changed since the last version?

**Comment by StarostaGit** [comment]
@tgrabiec I overlooked that `mutation_sink` was captured by reference because of the `&`. This caused crashes as expected, so I changed that to be captured by value instead.
`
    future<> execute(std::function<void(mutation)> mutation_sink, db::timeout_clock::time_point timeout) override {
        auto& ss = service::get_local_storage_service();
        return ss.get_ownership().then([&, mutation_sink] (std::map<gms::inet_address, float> ownership) {
`

**Pull request closed without merging**
