### PR TITLE
repair: create repair_info before waiting for hints

### LINKED ISSUE #8612: repair_while_table_is_dropped_test dtest fails
Regression started in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/805/testReport/repair_additional_test/RepairAdditionalTest/repair_while_table_is_dropped_test/
Scylla version df65d09e089c218bb8b1f53bb18bab38753fb471
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2909, in repair_while_table_is_dropped_test
    thread1.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2898, in <lambda>
    thread1 = executor.submit(lambda: node1.repair())
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1317, in repair
    return self.nodetool(cmd, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 678, in nodetool
    return super().nodetool(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 777, in nodetool
    raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/df65d09e089c218bb8b1f53bb18bab38753fb471/scylla-tools-java/bin/nodetool -h 127.0.90.1 -p 7190 repair' failed; exit status: 2; stdout: [2021-05-05 00:58:38,065] Starting repair command #1, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true)
[2021-05-05 00:58:40,164] Repair session 1 
[2021-05-05 00:58:40,164] Repair session 1 finished
[2021-05-05 00:58:40,172] Starting repair command #2, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2021-05-05 00:58:41,275] Repair session 2 failed
[2021-05-05 00:58:41,275] Repair session 2 finished
; stderr: error: Repair job has failed with the error message: [2021-05-05 00:58:41,275] Repair session 2 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2021-05-05 00:58:41,275] Repair session 2 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/805/artifact/logs-all.release.2/1620176327164_repair_additional_test.RepairAdditionalTest.repair_while_table_is_dropped_test/node1.log
```
INFO  2021-05-05 00:58:40,170 [shard 0] repair - starting user-requested repair for keyspace ks, repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b], options {{ trace -> false}, { jobThreads -> 1}, { incremental -> false}, { parallelism -> parallel}, { primaryRange -> false}}
INFO  2021-05-05 00:58:40,170 [shard 0] repair - repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b]: started replaying hints before repair, source nodes: {127.0.90.2, 127.0.90.1}, target nodes: {127.0.90.2, 127.0.90.1}
...
INFO  2021-05-05 00:58:41,171 [shard 0] repair - repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b]: finished replaying hints (took 1s), continuing with repair
WARN  2021-05-05 00:58:41,171 [shard 0] repair - repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b] failed: std::out_of_range ()
WARN  2021-05-05 00:58:41,171 [shard 0] repair - repair_tracker run for repair id [id=2, uuid=3fcc5ca1-d19e-4b50-ba12-11c54c0db91b] failed: std::out_of_range ()
```

### PR DESCRIPTION
**Pull request by piodul**
User-requested repair should fail if a table that does not exist is
requested to be repaired. However, if the table which is being repaired
is dropped while repair is in progress, repair should handle that
gracefully and not fail.

Up to the point when `repair_info` objects are created, repair can fail
due to a nonexistent table. This point is usually reached very quickly.
However, in #8452 a feature was merged which waits for hints to be
replayed towards repaired nodes, and this wait delays the point at which
`repair_info`s are created. For example, if replaying hints lasts 60
seconds but the table is deleted 30 seconds after `nodetool repair` was
started, then the repair operation will fail.

In order to prevent such situations and handle the deleted table
gracefully, the code which can fail due to a nonexistent table is moved
before waiting for hints to be replayed.

Fixes #8612

Tests:
- unit(dev, debug)
- dtest(repair_additional_test.py:RepairAdditionalTest.repair_while_table_is_dropped_test)

### CODE REVIEW

**Comment by avikivity** [comment]
Looks reasonable. @asias please review.

**Comment by asias** [comment]
Before try_wait_for_hints_to_be_replayed returns, we haven't really started to repair anything. The promise if a table is dropped during repair, the repair should return success is kept even without this patch, we can modify the test to make it pass by checking the log where repair really starts.

This is an example the confusion would bring if we unconditionally couple two unrelated operation together.  I would image even more confusing from users, e.g., why repair a tiny table would take so long. 



To fix the issue, I think it is best to separate hint replay to a separate api as we discussed here: https://github.com/scylladb/scylla/pull/8452#issuecomment-839458521


BTW, we need to improve the exception message for:

```
 971 const utils::UUID& database::find_uuid(std::string_view ks, std::string_view cf) const {
 972     try {
 973         return _ks_cf_to_uuid.at(std::make_pair(ks, cf));
 974     } catch (...) {
 975         throw std::out_of_range("");
 976     }
 977 }
```

The out of range error message is very confusing.

**Review by kbr- — APPROVED** [review]
LGTM, altough I'd probably separate the repair_info collection to a separate function.
@asias I agree that separating hint replay would be nice, but I think we can do it as a follow-up. This patch is nice nevertheless and won't hurt even after the separation.

**Comment by asias** [comment]
> LGTM, altough I'd probably separate the repair_info collection to a separate function.
> @asias I agree that separating hint replay would be nice, but I think we can do it as a follow-up. This patch is nice nevertheless and won't hurt even after the separation.

This patch is making the code more complicated than it was, playing with the foreign_ptr tricks. I do not think it is nicer.

**Comment by bhalevy** [comment]
@piodul, @asias, how about the following change that moves the call to list_column_families till after hint playing, and also allows skipping tables given via options if they are not found at this point.

```diff
diff --git a/repair/repair.cc b/repair/repair.cc
index 04eb58648..522dbe6f2 100644
--- a/repair/repair.cc
+++ b/repair/repair.cc
@@ -1228,16 +1228,9 @@ int repair_service::do_repair_start(sstring keyspace, std::unordered_map<sstring
         ranges = std::move(intersections);
     }
 
-    std::vector<sstring> cfs =
-        options.column_families.size() ? options.column_families : list_column_families(db.local(), keyspace);
-    if (cfs.empty()) {
-        rlogger.info("repair id {} completed successfully: no tables to repair", id);
-        return id.id;
-    }
-
     // Do it in the background.
     (void)repair_tracker().run(id, [this, &db, id, keyspace = std::move(keyspace),
-            cfs = std::move(cfs), ranges = std::move(ranges), options = std::move(options), ignore_nodes = std::move(ignore_nodes)] () mutable {
+            ranges = std::move(ranges), options = std::move(options), ignore_nodes = std::move(ignore_nodes)] () mutable {
         auto participants = get_hosts_participating_in_repair(db.local(), keyspace, ranges, options.data_centers, options.hosts, ignore_nodes).get();
 
         if (db.local().get_config().wait_for_hint_replay_before_repair()) {
@@ -1248,9 +1241,33 @@ int repair_service::do_repair_start(sstring keyspace, std::unordered_map<sstring
             try_wait_for_hints_to_be_replayed(id, std::move(waiting_nodes), participants).get();
         }
 
+        std::vector<sstring> cfs =
+            options.column_families.size() ? options.column_families : list_column_families(db.local(), keyspace);
+        std::vector<utils::UUID> table_ids;
+        table_ids.reserve(cfs.size());
+
+        // Filter out non-existing, optional tables.
+        auto& ldb = db.local();
+        for (const auto& cf : cfs) {
+            thread::maybe_yield();
+            try {
+                table_ids.push_back(ldb.find_uuid(keyspace, cf));
+            } catch (const std::out_of_range&) {
+                if (!options.column_families.empty()) {
+                    rlogger.info("Table \"{}\" not found. Skipping", cf);
+                    continue;
+                }
+                throw;
+            }
+        }
+
+        if (table_ids.empty()) {
+            rlogger.info("repair id {} completed successfully: no tables to repair", id);
+            return;
+        }
+
         std::vector<future<>> repair_results;
         repair_results.reserve(smp::count);
-        auto table_ids = get_table_ids(db.local(), keyspace, cfs);
         abort_source as;
         auto uuid = id.uuid;
         auto off_strategy_updater = seastar::async([this, uuid, &table_ids, &participants, &as] {
```

**Comment by piodul** [comment]
The "wait for hints" feature was converted into an HTTP API and is now separate from repair (https://github.com/scylladb/scylla/pull/8982). The logic which causes this bug was reverted, so this PR is not needed anymore. I'm closing this.

**Pull request closed without merging**
