### PR TITLE
dht: boot_strapper: fix `no_such_keyspace` exception when dropping keyspace while bootstrapping

### PR DESCRIPTION
**Pull request by kbr-**
The new cluster test harness was rapidly creating and dropping keyspaces while bootstrapping nodes. This would sometimes trigger a bug in `dht::boot_strapper::bootstrap` which would try to access a non-existing keyspace. This PR fixes the bug.

### CODE REVIEW

**Review by avikivity — APPROVED** [review]

**Comment by avikivity** [comment]
Looks simple and correct, @asias please look too.

**Comment by avikivity** [comment]
Why broken? It won't be streamed, but if it was just added, nothing needs to be streamed. We should check that the new node receives writes though.

**Comment by kbr-** [comment]
> I meant that it won't be streamed, whereas it should (cause it may contain writes). But fixing that probably amounts to implementing the safe topology changes spec.

If it is added after streaming starts, then all writes achieve quorum in the new replica set - because we've incremented required CL for writes by this point.

**Comment by tgrabiec** [comment]
I'm thinking about the same kind of race which happens here with keyspace removal, so the keyspace is added and receives writes before streaming starts, but we're using stale keyspace list here.

**Comment by gleb-cloudius** [comment]
On Thu, Jun 23, 2022 at 05:56:42AM -0700, Tomasz Grabiec wrote:
> I'm thinking about the same kind of race which happens here with keyspace removal, so the keyspace is added and receives writes before streaming starts, but we're using stale keyspace list here.
> 
I think we create this bootstraping object only when all nodes knows
new topology. Of course it breaks if they do not, but this is true for
the streaming in general.

--
			Gleb.

**Comment by kbr-** [comment]
Well, my explanation doesn't make sense.
The node pools for topology tests and regular tests are separate - we don't run regular tests on the nodes from topology tests.
So the create/drop keyspace dance shouldn't affect the chance of regular tests failing.

But maybe it's simply because we now start more nodes concurrently - so we introduce more overhead on the machine running the tests - and the nodes don't keep up.

**Comment by kbr-** [comment]
I removed the commit which re-enables the topology suite. There are other problems with it besides this bug. But nevertheless, the bug exists and is one of the necessary (but not sufficient) conditions to re-enable the suite. I'll work on the other problems independently.

**Comment by asias** [comment]
> Looks simple and correct, @asias please look too.

Looks good to me.

**Comment by kbr-** [comment]
After all the CI failure doesn't seem to be related to this PR, it was some problem on master.
I rebased and re-enabled the test. Let's see what happens...

**Comment by kbr-** [comment]
Apparently `memtable_test` has timed out:
first timestamp in its logs:
```
WARN  2022-06-24 12:16:58,098 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
```
12:16:58

last timestamp:
```
INFO  2022-06-24 12:31:17,670 [shard 0] compaction - [Compact ks.cf_0 8b81ed50-f3b9-11ec-af03-e8c4abb4c7c1] Compacting [/jenkins/workspace/releng/Scylla-CI/scylla/testlog/debug/scylla-3be7f260-e984-4a61-aa84-11c088a40fd2/ks/cf_0-881fd690f3b911ecaf03e8c4abb4c7c1/me-146-big-Data.db:level=0:origin=compaction,/jenkins/workspace/releng/Scylla-CI/scylla/testlog/debug/scylla-3be7f260-e984-4a61-aa84-11c088a40fd2/ks/cf_0-881fd690f3b911ecaf03e8c4abb4c7c1/me-148-big-Data.db:level=0:origin=memtable]
=== TEST.PY SUMMARY START ===
Test was cancelled
=== TEST.PY SUMMARY END ===
```
12:31:17

It may be due to overloading the Jenkins machine. The topology suite does introduce another pool of nodes that exists concurrently with the existing pool...

**Comment by kbr-** [comment]
Nevermind, the test was probably cancelled because a concurrently running test has failed
```
[2022-06-24T12:30:05.082Z] [2328/2336] cql-pytest  debug  [ PASS ] test_secondary_index.2043 58.59s
[2022-06-24T12:30:08.696Z] [2329/2336]   unit    debug  [ PASS ] bptree_stress_test.2329 32.57s
[2022-06-24T12:30:22.960Z] [2330/2336] cql-pytest  debug  [ PASS ] test_tools.2050 64.34s
[2022-06-24T12:30:22.960Z] [2331/2336] rest_api  debug  [ PASS ] test_storage_service.2325 30.96s
[2022-06-24T12:30:49.572Z] [2332/2336]   cql     debug  [ PASS ] lwt_test.2083 53.57s
[2022-06-24T12:30:55.454Z] [2333/2336]  boost    debug  [ PASS ] index_with_paging_test.test_index_with_paging.138 770.29s
[2022-06-24T12:31:01.343Z] [2334/2336]  boost    debug  [ PASS ] schema_changes_test.196 753.54s
[2022-06-24T12:31:18.028Z] errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.153.173.9:9042
[2022-06-24T12:31:18.029Z] Traceback (most recent call last):
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1208, in workaround_python26789
[2022-06-24T12:31:18.029Z]     code = await main()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1175, in main
[2022-06-24T12:31:18.029Z]     await run_all_tests(signaled, options)
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1047, in run_all_tests
[2022-06-24T12:31:18.029Z]     await reap(done, pending, signaled)
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 1029, in reap
[2022-06-24T12:31:18.029Z]     result = coro.result()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 181, in run
[2022-06-24T12:31:18.029Z]     await test.run(options)
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 707, in run
[2022-06-24T12:31:18.029Z]     async with self.suite.clusters.instance() as cluster:
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/pool.py", line 52, in __aenter__
[2022-06-24T12:31:18.029Z]     self.obj = await self.pool.get()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/pool.py", line 36, in get
[2022-06-24T12:31:18.029Z]     await self.pool.put(await self.build())
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/./test.py", line 358, in create_cluster
[2022-06-24T12:31:18.029Z]     await cluster.install_and_start()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 376, in install_and_start
[2022-06-24T12:31:18.029Z]     await server.install_and_start()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 130, in install_and_start
[2022-06-24T12:31:18.029Z]     await self.start()
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 290, in start
[2022-06-24T12:31:18.029Z]     if await self.cql_is_up():
[2022-06-24T12:31:18.029Z]   File "/jenkins/workspace/releng/Scylla-CI/scylla/test/pylib/scylla_server.py", line 230, in cql_is_up
[2022-06-24T12:31:18.029Z]     session.execute("CREATE KEYSPACE k WITH REPLICATION = {" +
[2022-06-24T12:31:18.029Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 2668, in execute
[2022-06-24T12:31:18.029Z]     return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state, host, execute_as).result()
[2022-06-24T12:31:18.029Z]   File "/usr/local/lib64/python3.9/site-packages/cassandra/cluster.py", line 4953, in result
[2022-06-24T12:31:18.029Z]     raise self._final_exception
[2022-06-24T12:31:18.029Z] cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.153.173.9:9042
[2022-06-24T12:31:21.584Z] [Pipeline] echo
```

**Comment by kbr-** [comment]
Some weird failure:
```
strip: unable to copy file 'debian/scylla-server/opt/scylladb/libexec/scylla'; reason: No space left on device
dh_strip: error: strip --remove-section=.comment --remove-section=.note debian/scylla-server/opt/scylladb/libexec/scylla returned exit code 1
make[1]: *** [debian/rules:41: override_dh_strip] Error 25
make[1]: Leaving directory '/jenkins/workspace/releng/Scylla-CI/scylla/build/dist/debug/debian/scylla-package'
make: *** [debian/rules:55: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -rfakeroot -us -uc -ui failed
[2579/2883] unified/build_unified.sh --mode release --unified-pkg build/release/dist/tar/scylla-unified-x86_64-package-5.1.dev.0.20220627.ffed4bb639d5.tar.gz
FAILED: build/release/dist/tar/scylla-unified-x86_64-package-5.1.dev.0.20220627.ffed4bb639d5.tar.gz 
unified/build_unified.sh --mode release --unified-pkg build/release/dist/tar/scylla-unified-x86_64-package-5.1.dev.0.20220627.ffed4bb639d5.tar.gz
tar: scylla/libexec/scylla: Wrote only 3584 of 10240 bytes
tar: Exiting with failure status due to previous errors
[2580/2883] reloc/build_deb.sh --reloc-pkg build/release/dist/tar/scylla-x86_64-package.tar.gz --builddir build/dist/release/debian
FAILED: build/dist/release/debian 
reloc/build_deb.sh --reloc-pkg build/release/dist/tar/scylla-x86_64-package.tar.gz --builddir build/dist/release/debian
tar: scylla/libexec/scylla: Wrote only 3584 of 10240 bytes
tar: Exiting with failure status due to previous errors
[2581/2883] reloc/build_rpm.sh --reloc-pkg build/release/dist/tar/scylla-x86_64-package.tar.gz --builddir build/dist/release/redhat
FAILED: build/dist/release/redhat 
reloc/build_rpm.sh --reloc-pkg build/release/dist/tar/scylla-x86_64-package.tar.gz --builddir build/dist/release/redhat
'/jenkins/workspace/releng/Scylla-CI/scylla/build/dist/release/redhat/SOURCES/scylla-x86_64-package.tar.gz' => '/jenkins/workspace/releng/Scylla-CI/scylla/build/release/dist/tar/scylla-x86_64-package.tar.gz'
'/jenkins/workspace/releng/Scylla-CI/scylla/build/dist/release/redhat/SPECS/scylla.spec' => 'dist/redhat/scylla.spec'
warning: line 202: It's not recommended to have unversioned Obsoletes: Obsoletes:	tuned
setting SOURCE_DATE_EPOCH=1437436800
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.dvvGnk
+ umask 022
+ cd /jenkins/workspace/releng/Scylla-CI/scylla/build/dist/release/redhat/BUILD
+ cd /jenkins/workspace/releng/Scylla-CI/scylla/build/dist/release/redhat/BUILD
+ rm -rf scylla
+ /usr/bin/gzip -dc /jenkins/workspace/releng/Scylla-CI/scylla/build/dist/release/redhat/SOURCES/scylla-x86_64-package.tar.gz
+ /usr/bin/tar -xof -
/usr/bin/tar: scylla/libexec/scylla: Wrote only 1536 of 10240 bytes
/usr/bin/tar: Exiting with failure status due to previous errors
error: Bad exit status from /var/tmp/rpm-tmp.dvvGnk (%prep)


RPM build errors:
    line 202: It's not recommended to have unversioned Obsoletes: Obsoletes:	tuned
    Bad exit status from /var/tmp/rpm-tmp.dvvGnk (%prep)
ninja: build stopped: subcommand failed.
```
cc @benipeled

**Comment by benipeled** [comment]
`reason: No space left on device` - leftovers on spider3, cleared

**Comment by kbr-** [comment]
@tgrabiec could you merge please?

**Pull request closed without merging**
