### PR TITLE
Add metrics for tracking latency of successful operations

### PR DESCRIPTION
**Pull request by psarna**
This series is inspired by the following AWS blog on latency and load shedding: https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/.

In order to be able to track the latency of successful requests (e.g. without counting in timeouts and other errors), a mirrored set of histograms is added. The new set of histograms tracks only the latency of requests which result in sending a non-error reply to the user.

Attached, an example screenshot from a modified Grafana dashboard - orange lines indicate the latencies of successful writes only, while green lines represent the original histograms. The metrics were recorded in a modified environment, where every 5th request was delayed for 123ms, and every 10th request is delayed to the point when it's already too late and a TIMEOUT error is returned to the client - which was usually 2 seconds. It's easy to correlate the difference between orange and green lines and the rise of timeouts metrics.
latencies_successful

### CODE REVIEW

**Comment by avikivity** [comment]
Maybe we should only count successful requests? Is the original histogram useful?

**Comment by psarna** [comment]
Perhaps, but the original histogram may already be used in all kinds of user-side tools, so I'm hesitant to just change its meaning. The original histogram might be useful for firing red flares when the latency reaches a certain point, which is a clear symptom that queries start to time out. It's better to rely on the metrics which actually tells you that timeouts happened, but I have no guarantee that nobody relies on current behaviour. And finally, it looks cool when both are shown in a single chart.

Still, changing this series from "introduce new histograms" to "replace old histograms with new semantics" would be rather trivial, so just let me know if that's the decision.

**Comment by psarna** [comment]
(rebased to current master just in case)

**Comment by psarna** [comment]
Well, and current histograms also help you guess what the current timeout is - not sure if it's in any way useful, but that's one bit of information that we lose when switching to only measuring "good" latency.

**Comment by psarna** [comment]
Now the timeout is likely either hardcoded or configured, but I'm pretty sure that we're going to eventually allow per-connection or per-session timeouts in order to help Scylla decide which queries should be rejected and which still have a chance of finishing in time.

**Comment by avikivity** [comment]
The histogram that includes the timeouts can be synthesized, no? it's the non-failing histogram plus an (nr_fail, timeout) entry.

The reason I'm reluctant to have both is that those histograms consume a large amount of bandwith just to send around, so I'm trying to limit redundant metrics.

**Comment by avikivity** [comment]
Adding @amnonh as it's metrics related.

**Comment by psarna** [comment]
In that case I'd prefer having good latency only over the current metrics. Let's wait for Amnon's take, and I can rewrite this pull request tomorrow if need be.

**Comment by psarna** [comment]
Ok, let me try add labels in v3. I hope I understand what you mean here - creating a `seastar::metrics::label` instance and marking the new histograms with this label?

**Comment by amnonh** [comment]
Yes, but keep in mind that when you sum over all the values you should count things only once.
For example, think about a metric called `total_requests` and we add a label for `status=failed`

If we had 100 requests, 80 successful and 20 failed.
`sum(total_requests{status='failed'}) = 20`
Make sure that
`sum(total_requests) = 100`
and not 120

**Comment by psarna** [comment]
Ok, I don't follow after all. Do I understand correctly that the suggestion is to still use two histograms, but instead of calling them `estimated_read` and `estimated_successful_read`, they should be gathered under a single name, but with different labels? I can imagine it working for counters, but how would I do that for latencies? Gathering two histograms for reads with `status==successful` and `status==failed` seems like the same amount of work as having `estimated_read` and `estimated_successful_read`, but it would also involve more computations, because latency of failed requests is not interesting by itself at all. I'd state that we're only interested in latency of successful requests, but if we insist on keeping the current metrics intact, why are labels better than simply providing new histograms, which directly measure successful requests?

**Comment by amnonh** [comment]
Users only interested in successful latencies would look at `estimated_read{status==successful}`
users interested in all latencies (it would better match what they see from the client-side) would look at `estimated_read`

Histograms are summable, summing the bucket on the Prometheus side would get the total result.

**Comment by psarna** [comment]
Splitting current histograms into two (e.g. one for failed reads and one for successful ones) is not trivial, because the existing histograms (e.g. `estimated_read`) are also already exposed via API (`api/column_family.cc`).
I'm not going to dig deeper into how to make it work with labels, because actually running the load shedding tests has higher priority than picking a proper way of representing some metrics in code. I'll just leave this pull request as is for now and use my private branch for testing, and if somebody wants to pick it up later, it's free to take.

**Comment by nyh** [comment]
I see there's a lot of arguments here, so although I do support this patch I can't really commit this without some agreement, so I can only add my two cents.

I agree with Piotr (and the Amazon post) that the performance of successful requests is what matters, and for unsuccessful requests all we care is to minimize their number (for which we have a separate counter). So I'm comfortable with these histograms measuring only successful requests, and I don't think we need two histograms.

I would like the **description** of these metrics to change, however, to make it clearer to Grafana users that what these histograms are showing, and that it does NOT measure timeouts. .

Also, I want to make clear what kind of "failures" we stopped measuring. Ideally, it should just exclude timeouts. For example, read of non existant data, LWT writes which failed the condition, etc. - such "failures" aren't timeouts, their latency is important, and should be measured.

**Comment by psarna** [comment]
@nyh it's a very good point that we should exclude only timeouts, but that one would be tricky to implement... In order to check the type of the exception, the code would have to throw and catch the error from `std::exception_ptr`, which we should avoid on hot paths for performance reasons.

On the other hand, errors like "lwt failed condition" are not propagated as exceptional futures, but rather as regular messages returned to the client, so they would still influence the latency histograms. I'm not sure how "reading non-existent data" is propagated though. Still, I'm comfortable with using this pull request for tests as a private branch only, so I'm not pushing towards merging the series. While the histograms for good latency are not perfect, because they ignore more errors than just timeouts, they're still very useful in load shedding tests, where the vast majority of errors are timeouts anyway.

**Comment by psarna** [comment]
Bonus: an interesting histogram showing a local test results. The test first wrote to a cluster with a too-high concurrency, and then read all the data, also with too many threads. Green lines are from current histograms and yellow ones count only successful operations.

The writing part shows very high average latency because some write timeouts occurred, while the successful average latency remains low. The reading part shows an opposite discrepancy - most of the requests ended up with an error (`storage_proxy - Exception when communicating with 127.0.0.1, to read from keyspace1.standard1: std::runtime_error (_read_concurrency_sem: restricted mutation reader queue overload)`), and the small percentage of successful ones had very high latency - that's why the average latency is quite low, while the successful average latency is orders of magnitude higher.
latency_vs_good_latency

**Comment by avikivity** [comment]
> On the other hand, errors like "lwt failed condition" are not propagated as exceptional futures, but rather as regular messages returned to the client, so they would still influence the latency histograms. I'm not sure how "reading non-existent data" is propagated though. Still, I'm comfortable with using this pull request for tests as a private branch only, so I'm not pushing towards merging the series. While the histograms for good latency are not perfect, because they ignore more errors than just timeouts, they're still very useful in load shedding tests, where the vast majority of errors are timeouts anyway.


If you have an exception, you're already not on a hot path.

I think we should move towards propagating expected errors (like timeouts) as variants (after careful consideration).

**Comment by psarna** [comment]
Ok, hot path is not a good wording, but I think it's still not a cold path. Lukewarm path maybe? What I mean is that there can be thousands of errors on that path - just like `storage_proxy - Exception when communicating with 127.0.0.1, to read from keyspace1.standard1: std::runtime_error (_read_concurrency_sem: restricted mutation reader queue overload)`, which usually comes in big bursts - and there can still be successful requests trying to get through, so it probably makes sense to minimize the effect of these failed requests on the system. I'm optimizing prematurely though, since I don't have any measurements to back up my claims.

**Comment by psarna** [comment]
By the way, the expected-error-as-variant approach is already applied in alternator (`executor.hh:: using request_return_type = std::variant<json::json_return_type, api_error>;`, mainly in order to avoid throwing on cas operations, but also to optimize some top-level validation errors.

**Comment by avikivity** [comment]
I'm uncomfortable with it because std::variant is terrible (but we can always happily write our own) and because future<T> is already a variant<T, std::exception_ptr>, so we're adding even more branches. But I expect it can't be helped.

**Comment by psarna** [comment]
I rebased and repushed the previous version, which adds good latency histograms in addition to the old ones. That's done only to make it easier to use this branch in local tests, so it's still not a merge candidate.

**Comment by psarna** [comment]
not going to be merged, closing

**Pull request closed without merging**
