### PR TITLE
docs/docker-hub.md: add quickstart section with --smp 1

### PR DESCRIPTION
**Pull request by sitano**
Also provide formula to calculate proper value for aio-max-nr.

### CODE REVIEW

**Comment by sitano** [comment]
However, the formula is not correct because it does not work even for 8 cores that must require 128*8*8 = 8192 free aio-nr items.

**Comment by bentsi** [comment]
@avikivity Scylla [page](https://hub.docker.com/r/scylladb/scylla) on Docker hub doesn't reflect the changes in this PR.
How is the page updated? Manually or we have some automatic process to update it?

CC: @lauranovich 
image

**Comment by avikivity** [comment]
It's not updated at all.

**Comment by bentsi** [comment]
@guy9 FYI: Docker examples in the Scylla University won't run out of the box, need somehow to notify users that the `aio-max-nr` should be increased to the recommended value.

**Comment by guy9** [comment]
@bentsi can you elaborate on this? Is this on Fedora? A specific version?

**Pull request closed without merging**
