### PR TITLE
scylla_setup: fix --nic option on non-interactive mode

### LINKED ISSUE #5725: Scylla_setup: still ask for nic in non-interactive mode
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

fixes are missing for https://github.com/scylladb/scylla/issues/3908 in some "if" branches

### PR DESCRIPTION
**Pull request by syuu1228**
scylla_setup should not shows up NIC selection prompt on non-interactive mode.

Fixes #5725

Signed-off-by: Takuya ASADA <syuu@scylladb.com>

### CODE REVIEW

**Comment by syuu1228** [comment]
This should be backport to branch-3.1, branch-3.2, branch-3.3

**Comment by tarzanek** [comment]
lgtm, thank you Takuya! :-)

**Comment by penberg** [comment]
Merged as 8e901636fc332302cf82f97a153f2a7e7a2b947e.

**Comment by dyasny** [comment]
Please backport to 3.2 and 3.3, we have customers who are running into this issue (when the host has more than one NIC)

**Pull request closed without merging**
