### PR TITLE
Update HACKING.md

### PR DESCRIPTION
**Pull request by 0xflotus**
fixed typo in --overprovisioned flag

### CODE REVIEW

**Comment by bhalevy** [comment]
LGTM, just need to change target branch to `next` (we don't merge directly to master)

**Comment by 0xflotus** [comment]
> LGTM, just need to change target branch to `next` (we don't merge directly to master)

I opened a new PR #5618 :)

**Comment by nyh** [comment]
@bhalevy it doesn't matter what the target branch is - the committer will take care of it. In fact, it's better to set the target branch to "master"-  that ensures that the pull request is only closed when the patch actually reaches master - and not as soon as it reaches "next".

**Comment by glommer** [comment]
@nyh is this really true? I see a lot of people including @penberg and @avikivity repeatedly asking people to base on top of next

**Comment by avikivity** [comment]
I only ask to base on next under exceptional circumstances. The correct base is master.

**Comment by bhalevy** [comment]
The base should be master and the target branch is next.
This is particularly true is one merges using the github web GUI.
This also helps detect merge conflicts in next before merging.

**Pull request closed without merging**
