### PR TITLE
storage_service: Use sleep_abortable instead of sleep

### PR DESCRIPTION
**Pull request by asias**
Make the sleep abortable so that it is able to break the loop during
shutdown.

### CODE REVIEW

**Comment by avikivity** [comment]
I have almost the same patch (prepared as part of https://github.com/scylladb/scylla/pull/4684) but I pass the abort_source instead of relying on a global termination signal.

**Comment by asias** [comment]
Nice timing ;-)  But I saw you did not modify the code where calls sleep(). Is this patch still needed?

**Comment by avikivity** [comment]
I have an extra patch that I did not yet push that adds more sleep_abortable()s, but decided to fix the critical stuff first.

**Comment by asias** [comment]
Ok. I will handle off the patch to you if you need any of the changes in this patch.

**Comment by avikivity** [comment]
Actually it is better that you do it because you know better which sleeps can be aborted and which do not. But it should be done after #4684 and use the abort_source from there.

**Comment by asias** [comment]
OK.

**Comment by asias** [comment]
Updated:
- Use _abort_source inside storage_service:

**Pull request merged**
