### PR TITLE
Use inline variables to reduce code duplication and complexity

### PR DESCRIPTION
**Pull request by haaawk**
C++17 introduced inline variables and now we don't have to declare a global extern in a header and then define it in .cc file. It is better to use inline variables because it reduces code duplication and complexity. Defining a variable in a single place is simpler and more maintainable.

This PR switches multiple places to use inline variables.

Tests: unit (dev)

### CODE REVIEW

**Comment by avikivity** [comment]
@espindola don't such changes increase object sizes and work for the linker?

Work for the linker isn't so important now since lld is plenty fast.

**Comment by haaawk** [comment]
> @espindola don't such changes increase object sizes and work for the linker?
> 
> Work for the linker isn't so important now since lld is plenty fast.

Isn't there still just one instance of the object in the final binary? Do we care about *.o files size that much?

**Comment by avikivity** [comment]
> > @espindola don't such changes increase object sizes and work for the linker?
> > Work for the linker isn't so important now since lld is plenty fast.
> 
> Isn't there still just one instance of the object in the final binary? Do we care about *.o files size that much?

We don't care much about the .o size, but I think it can increase compilation time. Every time someone uses an inline variable the compiler has to generate constructors and destructors for it and add them to the .o, which the linker then eliminates. Similar to inline functions, you don't make all your functions inline just because the linker eliminates the duplicates in the end.

**Comment by haaawk** [comment]
> > > @espindola don't such changes increase object sizes and work for the linker?
> > > Work for the linker isn't so important now since lld is plenty fast.
> > 
> > 
> > Isn't there still just one instance of the object in the final binary? Do we care about *.o files size that much?
> 
> We don't care much about the .o size, but I think it can increase compilation time. Every time someone uses an inline variable the compiler has to generate constructors and destructors for it and add them to the .o, which the linker then eliminates. Similar to inline functions, you don't make all your functions inline just because the linker eliminates the duplicates in the end.

Would you like me to measure compile time with and without this PR @avikivity ?

**Comment by avikivity** [comment]
It can't hurt, but I also want to hear from @espindola

**Comment by haaawk** [comment]
> It can't hurt, but I also want to hear from @espindola

Sure. I wasn't suggesting otherwise :).

**Comment by haaawk** [comment]
I run the clean compilation before and after the PR in dev and release

dev:

before
real    14m12.106s
user    197m3.745s
sys     11m20.727s

after
real    13m53.203s
user    199m25.441s
sys     11m23.304s

release:

before
real    27m28.252s
user    382m17.279s
sys     16m4.258s

after
real    28m46.035s
user    387m6.294s
sys     16m15.970s

The user time is ~1% more after this PR, in both cases.

**Comment by haaawk** [comment]
@espindola ping

**Comment by espindola** [comment]
Avi Kivity <notifications@github.com> writes:

> @espindola don't such changes increase object sizes and work for the linker?

Yes. They also mean that the initialization is seen by every translation
unit. I would prefer using inline variables only for simplifications
(templates for instance) and avoid it when a plain extern in .hh + definition
in .cc will do.

I know it is tempting, but I think the real replacement for extern in
.hh + definition in .cc is modules, and we just have to wait for it.

Cheers,
Rafael

**Comment by haaawk** [comment]
So what should we do with this PR @avikivity? Should I close it or is there a chance for it to be merged considering a little impact it has on compilation time?

**Comment by haaawk** [comment]
ping

**Comment by avikivity** [comment]
Seems like a net loss.  Is it worth 18 more seconds of build time? not IMO.

**Pull request closed without merging**
