### PR TITLE
Repair based node operation

### PR DESCRIPTION
**Pull request by asias**
Here is a simple introduction to the node operations scylla supports and
some of the issues.

- Replace operation

   It is used to replace a dead node. The token ring does not change. It
   pulls data from only one of the replicas which might not be the
   latest copy.

- Rebuild operation

   It is used to get all the data this node owns form other nodes. It
   pulls data from only one of the replicas which might not be the
   latest copy.

- Bootstrap operation

   It is used to add a new node into the cluster. The token ring
   changes. Do no suffer from the "not the latest replica” issue. New
   node pulls data from existing nodes that are losing the token range.

   Suffer from failed streaming. We split the ranges in 10 groups and we
   stream one group at a time. Restream the group if failed, causing
   unnecessary data transmission on wire.

   Bootstrap is not resumable. Failure after 99.99% of data is streamed.
   If we restart the node again, we need to stream all the data again
   even if the node already has 99.99% of the data.

- Decommission operation

   It is used to remove a live node form the cluster. Token ring
   changes.  Do not suffer “not the latest replica” issue. The leaving
   node pushes data to existing nodes.

   It suffers from resumable issue like bootstrap operation.

- Removenode operation

   It is used to remove a dead node out of the cluster. Existing nodes
   pulls data from other existing nodes for the new ranges it own. It
   pulls from one of the replicas which might not be the latest copy.

To solve all the issues above. We could use repair based node operation.
The idea behind repair based node operations is simple: use repair to
sync data between replicas instead of streaming.

The benefits:

   - Latest copy is guaranteed

   - Resumable in nature

   - No extra data is streamed on wire
     E.g., rebuild twice, will not stream the same data twice

   - Unified code path for all the node operations

   - Free repair operation during bootstrap, replace operation and so on.

Fixes: #3003
Fixes: #4208
Tests: update_cluster_layout_tests.py + replace_address_test.py + manual test

### CODE REVIEW

**Comment by asias** [comment]
@avikivity I see nodetool cleanup patchset is in. The previous PR is closed and I can not reopen. Creating a new one.

**Comment by avikivity** [comment]
Dequeued, it doesn't build after a merge. Please rebase (and check commits for bisectability, since this isn't a simple textual conflict).

**Comment by asias** [comment]
@avikivity @slivne @roydahan I created https://github.com/scylladb/scylla-dtest/pull/1329. We need it to pass the update_cluster_layout_tests.py. It looks like update_cluster_layout_tests is not part of the scylla next to mater promoting gate. Anyway, we need the change to make new code works with dtest.

**Comment by asias** [comment]
> Dequeued, it doesn't build after a merge. Please rebase (and check commits for bisectability, since this isn't a simple textual conflict).

The build failure is due to 897bbeabea0901673788db3dd35f12e2627a22f6.  

Changes in aaa1f3ce7bfe986712aacae80ef270a4f33f4794:
- Rebased to master
- Fixed missing of finish_bootstrapping build failure
- Verified each and every commit compiles in this series

**Comment by asias** [comment]
@avikivity I ran the update_cluster_layout_tests.py (https://github.com/scylladb/scylla-dtest/pull/132911) today. All 41 tests passed. I think we are ready to go if update_cluster_layout_tests.py is not part of the gating.

**Comment by avikivity** [comment]
Trying again :crossed_fingers:

**Pull request merged**
