### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by avikivity**
* seastar 443e6a9b77...c437920c23 (10):
  > Merge "Replace RPC outgoing queue with continuation chain" from Pavel E
  > test_runner: use std::endl to ensure messages are flushed
  > memory: realloc: defer to malloc if ptr is null
  > cmake: require boost 1.73 for building with C++20
  > reactor: backend: io_uring: disable on old kernels if RAID devices exist
  > Move function in invoke_on_all
  > core/loop: drop unused parameters
  > net/api: add connected_socket::operator bool()
  > fix cpuset count is zero after shift
  > docker: add pandoc package

### CODE REVIEW

**Comment by avikivity** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/980/
> 
> @xemul could these failures due to abandoned exceptional futures be related to your series: "Merge "Replace RPC outgoing queue with continuation chain" from Pavel E"?

Good catch, I just assumed flakiness (which is bad, when we see flakiness we should address it rather than smash the retry button)

**Comment by xemul** [comment]
> @xemul could these failures due to abandoned exceptional futures be related to your series: "Merge "Replace RPC outgoing queue with continuation chain" from Pavel E"?

I guess it's because `connection::send()` now may resolve into exception if connection fails/aborts, but prior to this it never did so.

**Comment by xemul** [comment]
`[PATCH] rpc: Take care of client::send() future in send_helper`

**Comment by bhalevy** [comment]
> > > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/980/
> > 
> > 
> > @xemul could these failures due to abandoned exceptional futures be related to your series: "Merge "Replace RPC outgoing queue with continuation chain" from Pavel E"?
> 
> Good catch, I just assumed flakiness (which is bad, when we see flakiness we should address it rather than smash the retry button)

credit goes to @raphaelsc who raised the suspicion

**Pull request closed without merging**
