### PR TITLE
Fix outdated setup message

### PR DESCRIPTION
**Pull request by ebenzecri**
'scylla_bootparam_setup' just set a clock source at boot time instead of setting 'huge pages' as the message said.

Just in case, please double check.

Thanks!

### CODE REVIEW

**Review by nyh — APPROVED** [review]
Looks good, but @syuu1228 please review.

A small nitpick: I wonder if a typical user will understand what this question about "add ... as a bootloader option" is asking him or her. What the script really does to to add whatever it adds as a **kernel** option, it's just that it does this via grub (it can't be any other "bootloader"). The word "kernel" isn't mentioned at all in our message or in the script.

**Comment by ebenzecri** [comment]
@nyh I absolutely agree with you

**Review by syuu1228 — APPROVED** [review]
LGTM

**Comment by avikivity** [comment]
"Outdated setup message (probably)" is maybe a description of a bug, but not a description of a fix.

**Comment by nyh** [comment]
> "Outdated setup message (probably)" is maybe a description of a bug, but not a description of a fix.

I'll commit after adding the word "Fix" and removing the word "probably" :-)

**Comment by nyh** [comment]
Oh, I can't commit, this PR now has two commits, one of them is a weird merge. @ebenzecri please rebase the patch over master. Thanks.

**Comment by nyh** [comment]
I'll fix commits in this PR manually and commit.

**Comment by nyh** [comment]
Thanks @ebenzecri committed manually. It's now in commit f196a4131a23c76841d8fe1549768ad2f57fbc11 in the "next" branch, eventually will reach the "master" branch after testing (at that point it may have a different commit id, though).
This PR will automatically close when that commit reaches master.

**Pull request closed without merging**
