### PR TITLE
alternator: fix combination of filter and projection

### PR DESCRIPTION
**Pull request by nyh**
The main goal of this this series is to fix issue #6951 - a Query (or Scan) with a combination of filtering and projection parameters produced wrong results if the filter needs some attributes which weren't projected.

This series also adds new tests for various corner cases of this issue. These new tests also pass after this fix, or still fail because some other missing feature (namely, nested attributes). These additional tests will be important if we ever want to refactor or optimize this code, because they exercise some rare corner code paths at the intersection of filtering and projection.

This series also fixes some additional problems related to this issue, like combining old and new filtering/projection syntaxes (should be forbidden), and even one fix to a wrong comment.

### CODE REVIEW

**Comment by nyh** [comment]
@psarna can you please review, and if ok, commit? Thanks.

**Comment by psarna** [comment]
Sure, I'll review it today

**Comment by nyh** [comment]
@psarna @avikivity any idea what happened to this? It seems to @psarna committed it to next (see above) but then it just disappeared from next, and never reached master. Was there any problem with these patches and it had to be dequeued - or is this just some git accident and this PR needs to be committed yet again?

**Comment by avikivity** [comment]
It might have been me. A few days ago I tried to dequeue something, then later found it wasn't dequeued and then dequeued it again. So it's likely the first time I dequeued this patch by mistake. I wanted to send an email about it, but forgot.

Apologogies.

**Comment by nyh** [comment]
@psarna @avikivity so please one of you re-merge this PR. Thanks.

**Comment by avikivity** [comment]
I'll let @psarna do it as I'm unfamiliar with the code. Apologies again.

**Comment by psarna** [comment]
requeued

**Pull request closed without merging**
