### PR TITLE
doc: Fix broken links

### PR DESCRIPTION
**Pull request by dgarcia360**
This PR fixes some links that stopped working when changing the domain from https://docs.scylladb.com/ to `https://docs.scylladb.com/<version_name>`

## How to test this PR

1. Run ``make preview``. The build should complete without errors.

2. Open the preview and click on some of the links replaced.

### CODE REVIEW

**Review by tzach — APPROVED** [review]
LGTM
I sample the links and the fix works.
Note this problem is tricky, since it no manifest with a local `build preview`  with mostly used.
It does manifest in multi verion production

**Comment by dgarcia360** [comment]
Fixed merge conflict

**Comment by denesb** [comment]
Conflicts, please rebase, you can do this by running `git rebase master` (after pulling master).

**Comment by dgarcia360** [comment]
Merge conflict fixed

**Comment by denesb** [comment]
Queued.

In the future, please prefix your commit titles (first line of commit message) with `docs: `, so we know they are related to docs by glance.

**Comment by tzach** [comment]
@denesb can you please take a look

**Comment by denesb** [comment]
> @denesb can you please take a look

Too slow, I already did :D

**Pull request closed without merging**
