### PR TITLE
[RFC] gossiper: Consolidate limiters for pending ACK and ACK2

### PR DESCRIPTION
**Pull request by michoecho**
This is my attempt at #5304. But honestly, I think that this piece of code will be better off without such refactoring. One small piece of duplication is cleaner than a template in this case. Especially since there are some small differences (log messages) that need to be specialized for both types of messages, which muddles the code. Perhaps #5304 should simply be closed without changes? Or maybe you could point me to a solution more elegant than just stuffing both pieces of similar code into a template?

### CODE REVIEW

**Comment by avikivity** [comment]
@michoecho first, your patch has to explain what problem it is solving, and how it is solving it in the changelog. Look at `git log` output from this repository.

When I review I first review the changelog to see if it something that should be done, and then I look at the patch itself to see how it is done.

**Comment by avikivity** [comment]
I agree that adding a template to eliminate just this duplication is overkill, since it's just two messages you're consolidating. Perhaps a non-template de-duplicating with smaller scope would be better.

**Comment by tgrabiec** [comment]
I agree that templating the whole thing is not the right direction.

The main problem here is not the duplication but intertwining high-lever and low-level logic in one method. It would help to extract the low level logic into a synchronizer like `serialized_action`.

**Comment by michoecho** [comment]
Closing due to inactivity and doubtful value of the refactoring.

**Pull request closed without merging**
