### PR TITLE
cql3: represent lists as chunked_vector instead of std::vector

### PR DESCRIPTION
**Pull request by michoecho**
The cql3 layer manipulates lists as `std::vector`s (of `managed_bytes_opt`). Since lists can be arbitrarily large, let's use chunked vectors there to prevent potentially large contiguous allocations.

### CODE REVIEW

**Comment by denesb** [comment]
`cql3::lists::copy_elements()` still remains as a vector, no?

**Comment by avikivity** [comment]
> `cql3::lists::copy_elements()` still remains as a vector, no?

I think it's just a boundary point where the series chose to stop the conversion, otherwise it would propagate to a lot more stuff in cql3.

It's a good boundary point, as lists::value values are rarely large (they can be, but usually lists/collection are accumulated slowly in writes and then the huge lists surface in core dumps when read).

**Comment by avikivity** [comment]
I think the real importance is that partially_deserialize_listlike now returns a chunked_vector, so that really large lists (>10k elements) can now fit in multiple 128k fragments.

**Comment by michoecho** [comment]
@denesb @avikivity Ping. I have answered the question. If there are no more questions, please approve or reject this PR.

**Review by denesb — APPROVED** [review]

**Pull request closed without merging**
