### PR TITLE
scylla_current_repo: support different $PRODUCT

### PR DESCRIPTION
**Pull request by fruch**
Support point to the correct download url for
diffrent scylla products

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@fruch Please change the base branch to `next` instead of master

**Comment by penberg** [comment]
Did the old AMI image call this script? I would prefer we fix this in scylla-machine-image.git and just eliminate this script from scylla.git altogether.

**Comment by fruch** [comment]
> Did the old AMI image call this script? I would prefer we fix this in scylla-machine-image.git and just eliminate this script from scylla.git altogether.

Yes it was called:
https://github.com/scylladb/scylla/blob/master/dist/ami/build_ami.sh#L70

**Comment by penberg** [comment]
@fruch Ok, thanks! I queued this as e5da79c211586ba49621858f3b1ac966153b6071, but please open a ticket on scylla-machine-image.git to eliminate this dependency in the future.

**Comment by fruch** [comment]
What do you think about just moving this in to scylla-machine-image ? or maybe scylla-pkg, sine that is the repo owns the downloads directory structure ?

**Pull request closed without merging**
