### PR TITLE
Fix deciding whether a query uses indexing

### LINKED ISSUE #4539: A partition key index may cause a regular query to fail with "No such index"
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): master (9213d56a069a223c0009ab2c2677aa408cf6b5cb)

The following, perfectly legal sequence of queries:
~~~
CREATE TABLE test_a(a BIGINT, b BIGINT, c BIGINT, PRIMARY KEY ((a, b)));
CREATE INDEX ON test_a(a);
INSERT INTO test_a (a, b, c) VALUES (1, 2, 3);
SELECT * FROM test_a WHERE a=1 AND b=2 AND c = 3 ALLOW FILTERING;
~~~
will cause a `No index found.` error, because there's a bug in the code that tries to figure out if a query is an indexed query or a regular one. I'm leaving the issue here as a placeholder, as I already pinpointed the problem, but I need some time to provide it with proper tests. Feel free to assign this issue to me.

### PR DESCRIPTION
**Pull request by psarna**
The code that decides whether a query should used indexing was buggy - a partition key index might have influenced the decision even if the whole partition key was passed in the query (which effectively means that indexing it is not necessary).

Fixes #4539

### CODE REVIEW

**Comment by slivne** [comment]
@nyh - we need this reviewed for a customer

**Comment by avikivity** [comment]
Looks good.

**Comment by avikivity** [comment]
@nyh is there a reason you did not merge this?

**Comment by nyh** [comment]
No. I was afraid to use the "merge pull request" button, and thought someone else would merge it manually before me. But I can definitely merge this manually. I'll do it myself.

**Comment by nyh** [comment]
@avikivity @psarna  I merged this patch manually to next, with hand-edited merge commit message. Please review my commit and let me know where or if I still need to improve my committer skills.

As you can see, I added a reference to this pull request in the commit message, which was noticed above, but the pull request was not automatically closed. I don't know if it will be closed when the commit gets promoted to master. If it doesn't, we'll need to find a way to have the pull requests close automatically - or if we can't, just close it manually....

**Comment by nyh** [comment]
Hmm, on second thought, it now seems that github figured out that this pull request was "merged". So it works. No need to manually close it. (however, if something breaks in promotion, we can end up with a lost pull request because it was already closed).

**Comment by psarna** [comment]
@nyh looks like github figured it out for pull requests indeed, but I have one more hint for issues in general. If you put `Ref #xxxx`, `Refs #xxxx`, or pretty much anything with `#xxxx` in the commit message, it will be shown in the issue, but merging the patch won't close it automatically. For closing, one has to use `Fixes #xxxx`, `Closes #xxxx` and other similar combinations. Source: https://help.github.com/en/articles/closing-issues-using-keywords

**Pull request merged**
