### PR TITLE
Add emergency compaction to harden fast flush vs slow compaction scenario.

### PR DESCRIPTION
**Pull request by mikolajsieluzycki**
If we reach a situation where flush rate exceeds compaction rate, we may
end up with arbitrarily large number of sstables on disk. If a read is
executed in such case, the amount of memory required is proportional to
the number of sstables for the given shard, which in extreme cases can
lead to OOM.

In the wild, this was observed in 2 scenarios:
- A node with >10 shards creates a keyspace with thousands of tables,
  drops the keyspace and shuts down before compaction finishes. Dropping
  keyspace drops tables, and each dropped table is smp::count writes to
  system.local table with flush after write, which creates tens of
  thousands of sstables. Bootstrap read from system.local will run OOM.
- A failure to agree on table schema (due to a code bug) between nodes
  during repair resulted in excessive flushing of small sstables which
  compaction couldn't keep up with.

The solution is to execute an emergency compaction post flush which will
- happen only if there are enough sstables that aren't currently being compacted
- pick smallest sstables, so that the compaction will be as quick as possible
- won't serialize with other compactions, so won't block flushes unnecessarily

In the unit test introduced in this patch series it can be proved that
even hard setting maximum shares for compaction and minimum shares for
flushing doesn't tilt the balance towards compaction enough to prevent
the problem. Since it's a fast producer, slow consumer problem, the
remaining solution is to block producer until the consumer catches up.
Flushing is on the latency sensitive path, so the emergency compaction
takes necessary precautions to be executed only in emergency situations
and to take as little time as possible.

### CODE REVIEW

**Comment by avikivity** [comment]
Ok, so you do close the loop. But then why the emergency compaction? That table should already be compacting like crazy.

**Comment by mikolajsieluzycki** [comment]
Regular compaction compacts and updates compaction history. Both operations happen under the same synchronisation primitives (read locks/weight tracking etc.). Update history issued by S1 can be handled on S2 and if S1 (fast flushing with fast compaction) issues update history which is handled by more loaded shard S2, then S1 compaction is stalled as well. That's what the unit test does - half the threads issue 500 flushes of 1 mutation each (quick to generate, quick to flush and compact) and the other half issues 10 flushes of 400 mutations each. Generating 400 mutations using random generator takes long enough that the test reaches ~150 concurrent sstables on disk without reporting reactor stalls.

The proposed solution ensures we don't operate on the same sstables (by choosing smallest ones that haven't been compacted and aren't currently being compacted), skips the synchronisation and blocks flushing until the tables are compacted.

**Comment by avikivity** [comment]
It should be extremely rare for repair history to impact anything. It is just a memtable write, and if we are so congested that we can't write to a memtable, then we won't be able to write the schema updates either.

On the other hand, the schema table updates are the common cause of having too many sstables, since any schema update generates several memtable flushes. So I think the main problem is those flushes by schema table updates.

If we agree on that, is there still a reason for adding a new compaction type? Won't the regular flushing be enough, as long as we don't allow a new flush until compaction clears some backlog?

**Comment by mikolajsieluzycki** [comment]
If we just block on flush if we have too many sstables until compaction clears them up. we're risking latency spikes. It is entirely possible that the compaction under current rules will run prohibitively long if e.g. we compact a large sstable. This is a scenario where we gain most from compaction in terms of reducing amplification and disk usage, so it's reasonable that it's prioritised by regular compaction sstable choice. It's also a complete opposite of what we want to achieve here. We could alter the algorithm of choosing the sstables to compact, but this would likely hurt the common case to optimise a rare one. If we want to block flushes (which I think we should in extreme cases like this one), we must ensure that we block as little as possible. The code of the emergency compaction started as a clone of the regular one, but once I started analysing the requirements, I ended up removing synchronisation, changing the sstable choice algorithm, removing retries (which also caused different exception handling). If the changes were smaller, I'd lean towards doing some dependency injection/inheritance to share as much well tested code as possible and introducing a tiny modification where needed, but I think the presented solution is simpler.

**Comment by avikivity** [comment]
If we have lots of sstables, it means we have lots of small sstables. Having lots of large sstables means we've run out of disk space too.

Compaction runs concurrently for different size classes, so if we're compacting some large sstables together that doesn't block compacting smaller size classes.

Why is it not sufficient to wait for the ongoing compaction? We're practically guaranteed to have one running. There's no question of providing good latency under this type of workload, where the user is pushing schema updates faster than we can flush them.

**Comment by mikolajsieluzycki** [comment]
When we discussed possible solutions on the team call, @tgrabiec raised the latency spikes problem and @raphaelsc suggested the non-serialized emergency compaction to mitigate it. @tgrabiec did you have a specific scenario in mind where just blocking until current compaction finishes if we have too many sstables would be problematic? @raphaelsc do you have other arguments apart from the ones I raised above to use the custom compaction?

**Comment by avikivity** [comment]
I think it is overkill. To reduce latency, let's separate the patch that adds the blocking since that is critical, and the rest can be regarded as an optimization (unnecessary in my opinion, but we can discuss it).

**Comment by raphaelsc** [comment]
the idea of emergency compaction is similar to reactor::add_urgent_task().

we know that such accumulation of sstables happen usually on small tier

if there are few tables that need compaction on small tier, then table needing urgent compaction may have to wait while blocking flush

we want the table that blocked flush has actually started compaction work, not waiting on other tables to release the 'weight lock'. compaction on small tier is fast though

reading the code, looks like we should rework compaction_manager::reevaluate_postponed_compactions() to prioritize tables with highest L0 backlog

if we went to proceed with emergency idea, we could've introduced 'future<> compaction_manager::perform_urgent(replica::table* t)', which:
    creates regular_compaction_task in urgent mode, which runs compaction immediately if # of input runs returned by compaction strategy > max_threshold[1].
    
    [1]: compaction strategies already work to return bucket with highest amount of files

so avoiding a new compaction type that is rarely stressed

**Comment by avikivity** [comment]
The reason I think it's unnecessary is that compaction_manager would already be performing such a compaction, it would be the most efficient compaction it can find.

**Comment by tgrabiec** [comment]
Introducing blocking means we introduce a way for the table to lose
availability. If this is not coupled with compaction manager logic, the
unavailability can take an arbitrary amount of time. In some cases, it may
be worse than OOMing and restarting.

So the primary solution should be to have a compaction manager / scheduler
smoothly prevent us from this condition. If it's reliable, then we don't
need blocking.

**Comment by mikolajsieluzycki** [comment]
I agree that we should avoid blocking in general, but in the scenario presented in the unit test, you can skip blocking, statically set memtable flush shares to minimum and compaction to maximum and you will still end up with too many sstables. With that in mind, blocking would be executed in really exceptional situations. From what I read through the code, all strategies have recency/number of tables bias, which would mean that the compaction will operate on the just-flushed sstables (small and numerous), limiting the blocking time to bare minimum.

**Comment by avikivity** [comment]
Any amount of prioritizing (selecting the correct compaction to run first, and increasing shares) is still vulnerable to the producer being faster than the consumer. There are two scenarios:

 - we aren't able to increase compaction priority sufficiently, and then producer outruns the consumer and the node fails
 - we are able to increase the priority sufficiently, but eventually this is equivalent to losing availability

We need a fail-safe backstop (blocking) in case prioritization fails. This is to save the node even at the expense of availability.

Separately, we may need to improve prioritization. This might be emergency compaction, or just changing the existing selection and prioritization (we may want to increase shares if we have an sstable count backlog, not just compaction bytes backlog).

But let's split them from each other. They're there for different reasons. One is to protect the node, the other is to maintain throughput.

**Comment by mikolajsieluzycki** [comment]
Created a separate PR for just blocking flush until compaction catches up (if necessary): https://github.com/scylladb/scylla/pull/10717

**Pull request closed without merging**
