### PR TITLE
cql3: time_uuid_fcts: validate time UUID (v5)

### LINKED ISSUE #5552: Running "select toDate(max(mintimeuuid(writetime(COLUMN))))"  takes down node
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.2-0.20191127.9d78d848e
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): scylla centos aws ami

```bash
[centos@... ~]$ nodetool status
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  ...  ?          256          ?       ...-33f0b13251f9  2c
UN  ...   ?          256          ?      ...-dd5d366bb440  2c
UN  ...   38.11 MB   256          ?       ...-3dfdf86c881e  2c

[centos@... ~]$ cqlsh -u ...
Connected to ledgerlord at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh:testkeyspace> select toDate(max(mintimeuuid(writetime(title)))) from orgs ;
OperationTimedOut: errors={'127.0.0.1': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.1
cassandra@cqlsh:testkeyspace> select * from orgs ;
NoHostAvailable:```

From a different machine I see the node is down and doesn't come back up

```bash
$ nodetool status

Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  ...  2.39 MB    256          ?       ...-33f0b13251f9  2c
UN  ...  2.35 MB    256          ?       ...-dd5d366bb440  2c
DN  ...  38.11 MB   256          ?       ...-3dfdf86c881e  2c
```

In the logs I see a failed assertion
```bash
Jan 03 00:14:34 scylla[3555]: scylla: ./utils/UUID.hh:66: int64_t utils::UUID::timestamp() const: Assertion `version() == 1' failed.
Jan 03 00:14:34  scylla[3555]: Aborting on shard 2.
Jan 03 00:14:34 scylla[3555]: Backtrace:
Jan 03 00:14:34  scylla[3555]: 0x00000000041df5e2
Jan 03 00:14:34  scylla[3555]: 0x00000000040cc8f5
Jan 03 00:14:34  scylla[3555]: 0x00000000040ccbf5
Jan 03 00:14:34  scylla[3555]: 0x00000000040ccca3
Jan 03 00:14:34 scylla[3555]: 0x00007f456868002f
Jan 03 00:14:34 scylla[3555]: /opt/scylladb/libreloc/libc.so.6+0x000000000003853e
Jan 03 00:14:34 scylla[3555]: /opt/scylladb/libreloc/libc.so.6+0x0000000000022894
Jan 03 00:14:34 scylla[3555]: /opt/scylladb/libreloc/libc.so.6+0x0000000000022768
Jan 03 00:14:34 scylla[3555]: /opt/scylladb/libreloc/libc.so.6+0x00000000000309f5
Jan 03 00:14:34 scylla[3555]: 0x0000000001809cf2
Jan 03 00:14:34 scylla[3555]: 0x0000000001fa4d83
Jan 03 00:14:34 scylla[3555]: 0x0000000001fb4b55
Jan 03 00:14:34 scylla[3555]: 0x0000000001fad841
Jan 03 00:14:34 scylla[3555]: 0x000000000193ccd9
Jan 03 00:14:34 scylla[3555]: 0x0000000001941ca5
Jan 03 00:14:34 scylla[3555]: 0x00000000040c9dc1
Jan 03 00:14:34 scylla[3555]: 0x00000000040c9fde
Jan 03 00:14:34 scylla[3555]: 0x00000000041abd6d
Jan 03 00:14:34 scylla[3555]: 0x00000000041d63db
Jan 03 00:14:34 scylla[3555]: 0x000000000409809d
Jan 03 00:14:34 scylla[3555]: /opt/scylladb/libreloc/libpthread.so.0+0x000000000000858d
Jan 03 00:14:34 scylla[3555]: /opt/scylladb/libreloc/libc.so.6+0x00000000000fd6a2
Jan 03 00:15:33 systemd[1]: scylla-server.service: main process exited, code=killed, status=6/ABRT
Jan 03 00:15:33 systemd[1]: Stopped Run Scylla Housekeeping restart mode.
```
Later it core dumps
```bash
Jan 03 00:16:01 systemd-coredump[12848]: Process 3555 (scylla) of user 996 dumped core.

Stack trace of thread 3558:
#0  0x00007f4567f8553f raise (libc.so.6)
#1  0x00007f4567f6f95e abort (libc.so.6)
#2  0x00007f4567f6f769 __assert_fail_base.cold.0 (libc.so.6)
#3  0x00007f4567f7d9f6 __assert_fail (libc.so.6)
#4  0x0000000001809cf3 _ZThn80_N4cql39functions26native_scalar_function_forIZNS0_14time_uuid_fcts23make_timeuuidtodate_fctEvEUl24cql_serialization_formatRKSt6vectorISt8optionalIN7seastar13basic_sstringIajLj31ELb0EEEESaIS9_EEE_Lb1EE7executeES3_SD_ (scylla)
#5  0x0000000001fa4d84 _ZN4cql39selection24scalar_function_selector10get_outputE24cql_serialization_format (scylla)
#6  0x0000000001fb4b56 _ZN4cql39selection25selection_with_processing25selectors_with_processing14get_output_rowE24cql_serialization_format (scylla)
#7  0x0000000001fad842 _ZN4cql39selection18result_set_builder5buildEv (scylla)
#8  0x000000000193ccda _ZN4cql310statements16select_statement15process_resultsEN7seastar11foreign_ptrINS2_13lw_shared_ptrIN5query6resultEEEEENS4_INS5_12read_commandEEERKNS_13query_optionsENSt6chrono10time_pointI8gc_clockNSE_8durationIlSt5ratioILl1ELl1EEEEEE (scylla)
#9  0x0000000001941ca6 operator() (scylla)
#10 0x00000000040c9dc2 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
#11 0x00000000040c9fdf _ZN7seastar7reactor14run_some_tasksEv (scylla)
#12 0x00000000041abd6e _ZN7seastar7reactor14run_some_tasksEv (scylla)
#13 0x00000000041d63dc _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
#14 0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#15 0x00007f456867558e start_thread (libpthread.so.0)
#16 0x00007f456804a6a3 __clone (libc.so.6)

Stack trace of thread 3562:
#0  0x00007f456867edf4 read (libpthread.so.0)
#1  0x00000000040cacef _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
#2  0x00000000040cc332 operator() (scylla)
#3  0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#4  0x00007f456867558e start_thread (libpthread.so.0)
#5  0x00007f456804a6a3 __clone (libc.so.6)

Stack trace of thread 3560:
#0  0x00007f456867edf4 read (libpthread.so.0)
#1  0x00000000040cacef _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
#2  0x00000000040cc332 operator() (scylla)
#3  0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#4  0x00007f456867558e start_thread (libpthread.so.0)
#5  0x00007f456804a6a3 __clone (libc.so.6)

Stack trace of thread 3555:
#0  0x00007ffdd01f75ee n/a (linux-vdso.so.1)
#1  0x00007f4568058692 __clock_gettime (libc.so.6)
#2  0x00007f456836f0e5 _ZNSt6chrono3_V212steady_clock3nowEv (libstdc++.so.6)
#3  0x00000000041abddd _ZN7seastar7reactor3runEv (scylla)
#4  0x0000000004034197 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
#5  0x00000000040358e3 _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIJiEEEvEE (scylla)
#6  0x00000000007df12a main (scylla)
#7  0x00007f4567f71413 __libc_start_main (libc.so.6)
#8  0x000000000083f5be _start (scylla)

Stack trace of thread 3563:
#0  0x00007f456867edf4 read (libpthread.so.0)
#1  0x00000000040cacef _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
#2  0x00000000040cc332 operator() (scylla)
#3  0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#4  0x00007f456867558e start_thread (libpthread.so.0)
#5  0x00007f456804a6a3 __clone (libc.so.6)

 Stack trace of thread 3559:
#0  0x00007f4568044efd syscall (libc.so.6)
#1  0x000000000459b8a7 _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla)
#2  0x00000000041e9aa6 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla)
#3  0x00000000041ea5a1 _ZN7seastar19reactor_backend_aio16wait_and_processEiPK10__sigset_t (scylla)
#4  0x00000000040ca615 _ZN7seastar7reactor16wait_and_processEiPK10__sigset_t (scylla)
#5  0x00000000041abed6 _ZN7seastar7reactor3runEv (scylla)
#6  0x00000000041d63dc _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
#7  0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#8  0x00007f456867558e start_thread (libpthread.so.0)
#9  0x00007f456804a6a3 __clone (libc.so.6)

Stack trace of thread 3561:
#0  0x00007f456867edf4 read (libpthread.so.0)
#1  0x00000000040cacef _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
#2  0x00000000040cc332 operator() (scylla)
#3  0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#4  0x00007f456867558e start_thread (libpthread.so.0)
#5  0x00007f456804a6a3 __clone (libc.so.6)

Stack trace of thread 3557:
#0  0x00007f4568044efd syscall (libc.so.6)
 #1  0x000000000459b8a7 _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla)
#2  0x00000000041e9aa6 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla)
#3  0x00000000041ea5a1 _ZN7seastar19reactor_backend_aio16wait_and_processEiPK10__sigset_t (scylla)
#4  0x00000000040ca615 _ZN7seastar7reactor16wait_and_processEiPK10__sigset_t (scylla)
#5  0x00000000041abed6 _ZN7seastar7reactor3runEv (scylla)
#6  0x00000000041d63dc _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
#7  0x000000000409809e _ZNKSt8functionIFvvEEclEv (scylla)
#8  0x00007f456867558e start_thread (libpthread.so.0)
#9  0x00007f456804a6a3 __clone (libc.so.6)
```

### PR DESCRIPTION
**Pull request by bhalevy**
Throw an error in case we hit an invalid time UUID
rather than hitting an assert.

Fixes #5552

(Ref #5588 that was dequeued and fixed here)

Test: UUID_test, cql_query_test(debug)

In v5:
- utils/UUID_gen: avoid int overflow in make_nanos_since

### CODE REVIEW

**Comment by bhalevy** [comment]
unit(dev) also passed now

**Comment by psarna** [comment]
Just to confirm - was integer overflow the reason why this series previously failed on next?

Also, it looks like ee78feb1bf44a4ce15c7474df87f27b9878d7340 fixes a previous commit in this series (93c55cf3d5e551a42fe62fed8d02046e80d14450), doesn't it make the series non-bisectable? I think that either the two should be merged, or ee78feb1bf44a4ce15c7474df87f27b9878d7340 should only change `int64_t` to `uint64_t` and come before 93c55cf3d5e551a42fe62fed8d02046e80d14450.

**Comment by bhalevy** [comment]
> Just to confirm - was integer overflow the reason why this series previously failed on next?
> 
> Also, it looks like [ee78feb](https://github.com/scylladb/scylla/commit/ee78feb1bf44a4ce15c7474df87f27b9878d7340) fixes a previous commit in this series ([93c55cf](https://github.com/scylladb/scylla/commit/93c55cf3d5e551a42fe62fed8d02046e80d14450)), doesn't it make the series non-bisectable? I think that either the two should be merged, or [ee78feb](https://github.com/scylladb/scylla/commit/ee78feb1bf44a4ce15c7474df87f27b9878d7340) should only change `int64_t` to `uint64_t` and come before [93c55cf](https://github.com/scylladb/scylla/commit/93c55cf3d5e551a42fe62fed8d02046e80d14450).

@psarna yes, the int overflow during the test was the reason it failed on next (in debug mode that has ubsan)
I'm ok with a preliminary patch that changes nanos_since to uint64_t and then effectively squashing 93c55cf3d5e551a42fe62fed8d02046e80d14450 into ee78feb1bf44a4ce15c7474df87f27b9878d7340.

will prepare a new version...

**Comment by bhalevy** [comment]
In v6:
- cd3460cc88 utils/UUID_gen: make_nanos_since

**Comment by bhalevy** [comment]
Test with v6: unit(dev), UUID_test cql_query_test(debug)

**Pull request merged**
