### PR TITLE
repair: Relax node selection in bootstrap when nodes are less than RF

### PR DESCRIPTION
**Pull request by asias**
Consider a cluster with two nodes:

 - n1 (dc1)
 - n2 (dc2)

A third node is bootstrapped:

 - n3 (dc2)

The n3 fails to bootstrap as follows:

 [shard 0] init - Startup failed: std::runtime_error
 (bootstrap_with_repair: keyspace=system_distributed,
 range=(9183073555191895134, 9196226903124807343], no existing node in
 local dc)

The system_distributed keyspace is using SimpleStrategy with RF 3. For
the keyspace that does not use NetworkTopologyStrategy, we should not
require the source node to be in the same DC.

Fixes: #6744
Backports: 4.0, 4.1, 4.2

### CODE REVIEW

**Comment by bhalevy** [comment]
@tgrabiec please review

**Comment by avikivity** [comment]
Looks okay to me.

**Comment by asias** [comment]
ping.

**Comment by avikivity** [comment]
@asias I already noted I'm okay with it.

**Comment by asias** [comment]
> @asias I already noted I'm okay with it.

Thanks. Avi! You are fast ;-)

**Comment by bhalevy** [comment]
ping @tgrabiec can you please review and merge this pr?

**Comment by avikivity** [comment]
> > @asias I already noted I'm okay with it.
> 
> Thanks. Avi! You are fast ;-)

You're confusing me with someone else maybe.

**Comment by asias** [comment]
Merged in 38d964352da7b950abdadb5fc903e7105b3ca238.

**Comment by asias** [comment]
> Relying on replication strategy type is sad, it breaks the abstraction.

For the type check: 

strat.get_type() == locator::replication_strategy_type::network_topology

Perhaps, we can hide it with abstract_replication_strategy::is_dc_aware().

Another usage is harder: 

```
1732                         auto get_rf_in_local_dc = [&] () {
1733                             size_t rf_in_local_dc = strat.get_replication_factor();
1734                             if (strat.get_type() == locator::replication_strategy_type::network_topology) {
1735                                 auto nts = dynamic_cast<locator::network_topology_strategy*>(&strat);
1736                                 if (!nts) {
1737                                     throw std::runtime_error(format("bootstrap_with_repair: keyspace={}, range={}, failed to cast to network_topology_strategy",
1738                                             keyspace_name, desired_range));
1739                                 }
1740                                 rf_in_local_dc = nts->get_replication_factor(local_dc);
1741                             }
1742                             return rf_in_local_dc;
1743                         };
```

The get_replication_factor(sstring dc) version is available for the network strategy only.

**Comment by avikivity** [comment]
The abstraction is very poor in the first place.

Maybe a better way would be to make simple strategy erase the DC/rack property of a node, so it thinks that is running in a single DC and rack. All the other logic would remain the same between them (and could be moved out of the virtual functions).

See things like count_per_dc_endpoints and assure_sufficient_live_nodes_each_quorum. /cc @gleb-cloudius

**Pull request closed without merging**
