### PR TITLE
Alternator: should output empty map, not empty JSON

### LINKED ISSUE #6568: Alternator: should output empty map, not empty JSON
This is an issue raised in the past by @tzach and now discovered again by @fruch by running a real application which runs on DynamoDB:

Currently, a `PutItem` request returns an empty response (it is empty because #5027 hasn't been done yet). However, this empty response is output as a completely empty string, which is wrong - it should be an empty map, "{}".  The DynamoDB documentation https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.LowLevelAPI.html shows that the output should be a map, wrapped in "{" and "}", not bare items, so the empty map should look the same.

@fruch says that the JSON parser (which the application uses) doesn't translate the empty string we return to empty map as we would have liked.

### PR DESCRIPTION
**Pull request by fruch**
Fixes #6568

### CODE REVIEW

**Comment by fruch** [comment]
@nyh, I've tried adding a test for it, but seem like boto3 client is handling it nice.
the code that was having the issue wasn't using boto3, but botocore directly...

so I gave up on adding a test

**Comment by nyh** [comment]
@psarna wrote a test for it, `test/alternator/test_manual_requests.py`, `test_put_item_return_type`.
As you noted, boto3 can't test for this, it silently accepts the empty string.
So his test uses a manual request and tries to parse it with json.loads - and fails because as you correctly noted, the empty string cannot be parsed as a JSON object.

**Comment by nyh** [comment]
Note that @psarna also wrote his own patch for this (I didn't see yours...). 8fc3ca855eeb12a173ccf3bede499ce0fd71bff7. Committed yesterday.

**Comment by fruch** [comment]
Yeah I wasn't looking at next, and seem like his change is better anyhow

**Comment by fruch** [comment]
I've practiced reading a bit of C code... Need to shave the rust once in a while

**Comment by nyh** [comment]
Thanks. Your patch seems good. And Rust is a completely different language :-)

**Pull request closed without merging**
