### PR TITLE
[RFC] db,schema_tables: make schema merge failures fatal

### PR DESCRIPTION
**Pull request by psarna**
When a local schema merge fails, it generally means one of the
following:
1. system_schema local tables were not updated properly and another
   schema pull is in order
2. system_schema local tables were updated, but the in-memory schema
   representation wasn't. That's especially problematic, because
   schema digest is calculated from the contents of schema tables,
   which means that the node would advertise that it has an up-to-date
   schema, while in fact it does not.

Due to lack of a better option, when such failure is detected, the node
shoots itself in the head in order to trigger a restart, which will
reload schema information from local tables (which helps 2.)
and triggers schema pulls in case of inconsistencies (which helps 1.).

Refs #2805

Notice: This change is marked RFC in order to trigger a discussion - aborting operation is a little harsh, but on the other hand it's hard to come up with a better solution - suggestions are very welcome. The reasoning for an abort is as follows - when schema merging fails, the node is not up-to-date with the cluster schema, which makes it less usable. In some cases it will be aware of being not up-to-date and could trigger a schema pull, but in other cases it can't - because its own local schema tables already contain all the data and a digest computed from this data matches the newest schema digest in the cluster. In any of these two cases, a restart is likely to solve the problem. Theoretically, if the node is aware that its schema is not up-to-date, we do not need to kill it, but it's not easy to determine whether the data from system tables is up to date with the in-memory representation, so a safer choice is to prefer dying over hoping that a partial failure was handled correctly.
Also, note that failures **during** a schema merge should not be considered a common occurrence - it will generally be caused either by a bad_alloc, or by not being able to save something to local system tables, and both of these conditions suggest that the node is likely to die soon anyway.

### CODE REVIEW

**Comment by psarna** [comment]
> I think it does make sense to restart in this case: I think it's a principle of ours that if a node cannot be trusted to provide **correct** responses to requests, it's better than it doesn't run at than continue to run and provide wrong results. That being said, there is a danger here that maybe this problem can effect many nodes - and bring the entire cluster down, not just one node. Do we have a guess as to _why_ this happens? If it's a rare fluke that gets resolved by a reboot, we're safe.

My only guess is bad_alloc and other types of overload, but perhaps somebody has a different input.

> 
> Finally, I wonder if abort() is the right thing to do. It will generate a big core dump. Will it be useful? Maybe a clean exit() will be better here? But only if our startup script will restart Scylla even after a clean exit.

Actually, a core dump would be very welcome. We should generally never reach a situation when the system is so overloaded that it can't stand a schema change, and investigating such core dumps could help us pinpoint possible root causes.

**Comment by psarna** [comment]
> @tgrabiec I gave your proposal of refusing to update schema after a failure more thought, and I have reached the following conclusion: isn't it kind of what already happened in the original failure on which this pull request is based? One of the nodes kept failing the requests due to not being able to get proper schemas, and what ultimately helped was a restart, but that involved manual intervention - so it all boils down to a question whether we prefer that, or a forced restart, which may affect availability. I'm still not sure how likely it is for a node to actually fail during schema merge - right now the only viable candidate is an OOM state, in which case the node does not help much with keeping the availability up anyway, since it's struggling to survive.

@tgrabiec @nyh @avikivity I was pinged wrt. to this discussion, so here's my attempt to revive it. Does anyone has an opinion which way we should prefer?

**Comment by psarna** [comment]
Oh wait, I wasn't actually pinged on that... I just mixed up other issues. Regardless, some input would be welcome

**Comment by Pawel-Kr** [comment]
@tgrabiec @avikivity @nyh ping, please check @psarna's latest replies. Thanks!

**Comment by tgrabiec** [comment]
@Pawel-Kr I saw @psarna reply. It doesn't change my point, I think. Would users prefer automatic restart over the risk of losing availability?

We could maybe reduce the risk of availability loss and coordinate automatic restarts so that only one node restarts at a time. But still, those restarts may conflict with admin operations. For example, restarts will cause repair or bootstrap to fail.

**Comment by psarna** [comment]
> @Pawel-Kr I saw @psarna reply. It doesn't change my point, I think. Would users prefer automatic restart over the risk of losing availability?
> 
> We could maybe reduce the risk of availability loss and coordinate automatic restarts so that only one node restarts at a time. But still, those restarts may conflict with admin operations. For example, restarts will cause repair or bootstrap to fail.

@tgrabiec I'm also inclined to agree that availability loss is a real potential problem, especially that schema inconsistencies may have tendency to propagate to multiple nodes. My main claim in the comment https://github.com/scylladb/scylla/pull/9478#issuecomment-947360296 is that the behavior that you proposed - leaving the node in a blocked state, when it's unable to pull schema from other nodes is what already happens now - that's exactly the symptoms that the user reported. And our solution was to proceed with a rolling restart performed manually at their convenience, so if everybody agrees that this is what we recommend (I'm personally fine with it), then this issue is a no-op and we don't need to apply any changes - except perhaps updating the documentation that explains what to do when a node failed to update its local schema.

**Pull request closed without merging**
