### PR TITLE
repair: Fix range intersection for start_token and end_token option

### LINKED ISSUE #9560: repair: given_range_complement should not be a wrapping range
The range::subtract() was used as a trick to implement
range::intersection() when intersection was not available at that time.

The following code is problematic:

dht::token_range given_range_complement(tok_end, tok_start);

because dht::token_range should be non-wrapping range.

### PR DESCRIPTION
**Pull request by asias**
The range::subtract() was used as a trick to implement
range::intersection() when intersection was not available at that time.

The following code is problematic:

dht::token_range given_range_complement(tok_end, tok_start);

because dht::token_range should be non-wrapping range.

To fix, use compat::unwrap_into() to unwrap the range and use
the range::intersection() to calculate the intersection.

Note even if the given_range_complement is problematic, current code
generates correct intersections.

Example 1:
$ curl -X POST 'http://127.0.0.1:10000/storage_service/repair_async/keyspace1?startToken=5&endToken=100'

[shard 0] repair - starting user-requested
repair for keyspace keyspace1, repair id [id=1,
uuid=aa71a192-5967-4f05-99b8-5febd9d81d50], options {{ endToken -> 100}, { startToken -> 5}}

[shard 0] repair - start=5, end=100, given_range_complement=(100, 5], wrange=(100, 5], is_wrap_around=true,
ranges={(-inf, -7612759882658906007], (-7612759882658906007,
-6766703710995023384], (-6766703710995023384, 2918449800065200439],
(2918449800065200439, 8039072586540417979], (8039072586540417979,
+inf)}, intersections={(5, 100]}

[shard 0] repair - New method intersections={(5, 100]}

Example 2:

$ curl -X POST
'http://127.0.0.1:10000/storage_service/repair_async/keyspace1?startToken=100&endToken=5'

[shard 0] repair - starting user-requested
repair for keyspace keyspace1, repair id [id=1,
uuid=f6076438-015c-4bdc-8ebd-0a55664365fa], options {{ endToken -> 5}, { startToken -> 100}}

[shard 0] repair - start=100, end=5, given_range_complement=(5, 100], wrange=(5, 100], is_wrap_around=false,
ranges={(-inf, -7612759882658906007], (-7612759882658906007,
-6766703710995023384], (-6766703710995023384, 2918449800065200439],
(2918449800065200439, 8039072586540417979], (8039072586540417979,
+inf)}, intersections={
(-inf, -7612759882658906007],
(-7612759882658906007, -6766703710995023384],
(-6766703710995023384, 5],
(100, 2918449800065200439],
(2918449800065200439, 8039072586540417979],
(8039072586540417979, +inf)}

[shard 0] repair - New method intersections={
(-inf, -7612759882658906007],
(-7612759882658906007, -6766703710995023384],
(-6766703710995023384, 5],
(100, 2918449800065200439],
(2918449800065200439, 8039072586540417979],
(8039072586540417979, +inf)}

Fixes #9560

### CODE REVIEW

**Comment by asias** [comment]
@nyh Could you please take a look since you wrote the given_range_complement originally.

**Review by nyh — APPROVED** [review]
The new code looks good, but I didn't understand what implications does the old code's incorrectness have - and whether it could lead to user-visible bugs. Can we write a regression test that demonstrate such bugs?

**Comment by asias** [comment]
> The new code looks good, but I didn't understand what implications does the old code's incorrectness have - and whether it could lead to user-visible bugs. Can we write a regression test that demonstrate such bugs?

As I mentioned in the commit log. With / without this patch, the code generates the same intersection of ranges. So this will not lead to user-visible bugs.

**Comment by nyh** [comment]
> As I mentioned in the commit log. With / without this patch, the code generates the same intersection of ranges. So this will not lead to user-visible bugs.

I saw that example in the commit message, but didn't understand the explanation - if there was nothing wrong with the original code, why fix it? If there *is* something wrong, how did it not lead to wrong results?

**Comment by asias** [comment]
> > As I mentioned in the commit log. With / without this patch, the code generates the same intersection of ranges. So this will not lead to user-visible bugs.
> 
> I saw that example in the commit message, but didn't understand the explanation - if there was nothing wrong with the original code, why fix it? If there _is_ something wrong, how did it not lead to wrong results?

dht::token_range is nonwrapping_interval. It is wrong to pass start > end which nonwrapping_interval does not expect. 

472     // Can only be called if start <= end. IDL ctor.
473     nonwrapping_interval(optional<bound> start, optional<bound> end, bool singular = false)
474         : _interval(std::move(start), std::move(end), singular)
475     { }

The second reason is that it is better to use the provided intersection api instead of playing tricks.

**Pull request closed without merging**
